In [15972]:
# 1. Import libraries
import pandas as pd
import numpy as np   # ← REQUIRED for AGE

In [15973]:
# 2. Load the CSV
df = pd.read_csv("data/clinical_data_raw.csv")
# 3. Check the shape of the dataframe (dimensions)
df.shape
print ("Number of rows:", df.shape[0])
print ("Number of columns:", df.shape[1])
# 4. View the column names
df.columns

Number of rows: 1155000
Number of columns: 41

Index(['Patient_ID', 'patient_id', 'Age', ' age', 'Gender', 'gender ',
       'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI',
       'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate',
       'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme',
       'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name',
       'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs',
       'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date',
       'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'Notes',
       'Extra_Col_1', 'Extra_Col_2', 'unnamed_0'],
      dtype='str')

In [15974]:
# 5. View the first 5 rows
df.head()

,Patient_ID,patient_id,Age,age,Gender,gender,Ethnicity,Weight_kg,Weight_lbs,Height_cm,...,Smoking_Status,Alcohol_Use,Admission_Date,Treatment_Outcome,Adverse_Event,Readmission_30d,Notes,Extra_Col_1,Extra_Col_2,unnamed_0
0,687919,93.0,48.0,NaN,Female,NaN,Other,106.2,231.877387,170.2,...,true,-,NaN,0,NaN,0.0,NaN,NaN,NaN,0.159214
1,582916,958.0,63.0,NaN,unknown,NaN,Chinese,87.4,194.295528,174.4,...,Yes,no,2022/06/10,0,0,0.0,NaN,NaN,NaN,NaN
2,499828,510.0,999.0,NaN,0,NaN,Other,81.9,179.964120,179.1,...,Former,Heavy,"October 22, 2021",0,1,0.0,NaN,NaN,NaN,0.651556
3,281644,NaN,52.0,NaN,male,NaN,NaN,70.5,152.675132,167.1,...,current,NaN,2020-02-23,0,NaN,0.0,See chart,NaN,NaN,0.295824
4,736725,541.0,51.0,NaN,m,NaN,ASIAN,73.5,NaN,180.9,...,yes,Social,12/08/2023,0,0,0.0,NaN,NaN,NaN,0.163931

In [15975]:
# 6. Check data types
df.dtypes

Patient_ID             int64
patient_id           float64
Age                  float64
 age                 float64
Gender                   str
gender                   str
Ethnicity                str
Weight_kg            float64
Weight_lbs           float64
Height_cm            float64
BMI                  float64
blood_pressure           str
Systolic_BP          float64
Diastolic_BP         float64
Heart_Rate           float64
Temperature_F        float64
Hemoglobin           float64
WBC_Count            float64
ALT_Enzyme           float64
AST_Enzyme           float64
Creatinine           float64
eGFR                 float64
HbA1c                float64
Total_Cholesterol    float64
Drug_Name                str
drug_name                str
Dosage                   str
Duration_Days            str
Route                    str
Concurrent_Drugs     float64
Diagnosis                str
Smoking_Status           str
Alcohol_Use              str
Admission_Date           str
Treatment_Outcome        str
Adverse_Event            str
Readmission_30d      float64
Notes                    str
Extra_Col_1          float64
Extra_Col_2          float64
unnamed_0            float64
dtype: object

In [15976]:
# 7. Check missing values
df.isnull().sum()
#Calculate missing-value percentage
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
missing_pct.sort_values(ascending=False)

Extra_Col_1          100.00
Extra_Col_2          100.00
gender                97.57
 age                  95.48
Notes                 86.47
Admission_Date        29.03
Alcohol_Use           24.14
Smoking_Status        19.87
Route                 19.43
Gender                18.62
Ethnicity             17.61
drug_name             15.56
Height_cm             14.91
Duration_Days         14.08
Diagnosis             13.92
Dosage                13.72
Concurrent_Drugs      12.90
Drug_Name             12.83
Total_Cholesterol     12.47
Creatinine            12.43
Temperature_F         11.65
Heart_Rate            11.30
eGFR                  11.01
blood_pressure        10.70
WBC_Count             10.33
unnamed_0             10.28
Hemoglobin             9.48
Systolic_BP            8.99
patient_id             8.79
Adverse_Event          7.80
BMI                    7.45
Readmission_30d        7.26
Treatment_Outcome      6.11
Age                    6.06
Weight_lbs             5.55
AST_Enzyme             5.42
HbA1c                  5.41
Diastolic_BP           5.10
ALT_Enzyme             5.08
Weight_kg              5.02
Patient_ID             0.00
dtype: float64

2. Data Cleaning Steps

In [15977]:
# 2.1 Create a working copy for data cleaning

df_clean = df.copy()

In [15978]:
# 2.2 Remove confirmed empty columns (Column_1 and Column_2 are empty)

df_clean = df_clean.dropna(axis=1, how="all")
df_clean.shape

df_clean.columns.tolist()
print(df_clean.columns.tolist())

# Count of remaining columns
print(f"Remaining columns: {len(df_clean.columns)}")

['Patient_ID', 'patient_id', 'Age', ' age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'Notes', 'unnamed_0']
Remaining columns: 39

In [15979]:
# Capture columns BEFORE dropping
cols_before = df_clean.columns.tolist()
print(f"Columns before: {len(cols_before)}")

# Drop fully-empty columns
df_clean = df_clean.dropna(axis=1, how="all")

cols_after = df_clean.columns.tolist()
print(f"Columns after: {len(cols_after)}")

# Show exactly which columns were dropped
dropped_cols = set(cols_before) - set(cols_after)
print(f"Dropped columns ({len(dropped_cols)}): {dropped_cols}")

Columns before: 39
Columns after: 39
Dropped columns (0): set()

In [15980]:
# 2.3. Investigate obvious unwanted columns (Notes and unnamed_0) and their values

print("NOTES:")
print(df_clean["Notes"].value_counts(dropna=False))

print("\nUNNAMED_0:")
print(df_clean["unnamed_0"].describe())

print("\nMISSING VALUES:")
print(df_clean[["Notes", "unnamed_0"]].isna().sum())

NOTES:
Notes
NaN          998781
See chart    156219
Name: count, dtype: int64

UNNAMED_0:
count    1.036320e+06
mean     5.000417e-01
std      2.885999e-01
min      2.290873e-06
25%      2.503225e-01
50%      4.997954e-01
75%      7.500302e-01
max      9.999997e-01
Name: unnamed_0, dtype: float64

MISSING VALUES:
Notes        998781
unnamed_0    118680
dtype: int64

In [15981]:
#2.3-b
print("Notes distinct values:")
print(df_clean["Notes"].value_counts(dropna=False))

print("\nunnamed_0 distinct values:")
print(df_clean["unnamed_0"].nunique(dropna=True))

Notes distinct values:
Notes
NaN          998781
See chart    156219
Name: count, dtype: int64

unnamed_0 distinct values:
942125

### `Note` — EDA Note
Notes contains only NaN and "See chart" and provides no meaningful analytical information; therefore, it will be deleted.

### `unnamed_0` — EDA Note

* **942,125 distinct values** out of **1,036,320 non-null values**.
* **118,680 missing values**.
* Values range approximately **0–1**--- **Potential unwanted/technical column; verify purpose before deletion.

In [15982]:
#2.3-c Verify if the empty columns are still present in the dataframe after dropping them
print(df_clean.columns.tolist())

['Patient_ID', 'patient_id', 'Age', ' age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'Notes', 'unnamed_0']

In [15983]:
# 2.3-d Delete the unwanted columns (Notes)
df_clean = df_clean.drop(columns=["Notes"])
print("Notes" in df_clean.columns)
print(df_clean.columns.tolist())

# Number of columns remaining
print(f"Number of columns remaining: {len(df_clean.columns)}")

False
['Patient_ID', 'patient_id', 'Age', ' age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'unnamed_0']
Number of columns remaining: 38

#2.4 Check for duplicates columns in the dataframe
related_columns = [
    ("Patient_ID", "patient_id"),
    ("Age", " age"),
    ("Gender", "gender "),
    ("Drug_Name", "drug_name")

In [15984]:
#2.4-b  Age vs age

In [15985]:
# Sanity check: confirm this is the expected state of df_clean
print("Shape:", df_clean.shape)
print("Notes present:", "Notes" in df_clean.columns)
print("Age present:", "Age" in df_clean.columns, " age present:", " age" in df_clean.columns)

Shape: (1155000, 38)
Notes present: False
Age present: True  age present: True

In [15986]:
#2.4-b1  Age vs age
related_columns = [("Age", " age"),]
    
for col1, col2 in related_columns:
    print(f"\n{col1} vs {col2}")
    print("-" * 50)

    # Non-null counts
    print("Age non-null:", df_clean["Age"].notna().sum())
    print(" age non-null:", df_clean[" age"].notna().sum())

    # First 10 rows
    print("\nFirst 5 rows:")
    print(df_clean[[col1, col2]].head(5))

Age vs  age
--------------------------------------------------
Age non-null: 1085064
 age non-null: 52262

First 5 rows:
     Age   age
0   48.0   NaN
1   63.0   NaN
2  999.0   NaN
3   52.0   NaN
4   51.0   NaN

In [15987]:
print("NaN:", df_clean[" age"].isna().sum())

print("-:", (df_clean[" age"] == "-").sum())

print("0:", (df_clean[" age"] == 0).sum())

print("Empty:", (df_clean[" age"].astype(str).str.strip() == "").sum())

valid_numbers = (
    df_clean[" age"].notna()
    & (df_clean[" age"] != "-")
    & (df_clean[" age"] != 0)
    & (df_clean[" age"].astype(str).str.strip() != "")
)

print("Valid numbers:", valid_numbers.sum())

print("Total:", 
      df_clean[" age"].isna().sum()
      + (df_clean[" age"] == "-").sum()
      + (df_clean[" age"] == 0).sum()
      + (df_clean[" age"].astype(str).str.strip() == "").sum()
      + valid_numbers.sum())

NaN: 1102738
-: 0
0: 280
Empty: 0
Valid numbers: 51982
Total: 1155000

NaN: 1102738+0: 280+Valid numbers: 51982= Total: 1155000
Now we can focus on just age 51982 rows where it has valid numbers. 
Below shows the first 20 of the 51,982 valid " age" values and the corresponding Age value from the same rows.

In [15988]:
# Checking the corresponding  "Age" column  for Valid 'age' numbers: 51982
age_values = df_clean.loc[valid_numbers, "Age"]

print("NaN:", age_values.isna().sum())
print("0:", (age_values == 0).sum())
print("-:", (age_values == "-").sum())
print("Valid numbers:", age_values.notna().sum() - (age_values == 0).sum() - (age_values == "-").sum())

NaN: 3072
0: 0
-: 0
Valid numbers: 48910

In [15989]:
# Age Valid numbers: 48910: comparing after rounding and stripping whitespace
age1 = df_clean.loc[valid_numbers & df_clean["Age"].notna(), "Age"].astype(str).str.strip().astype(float).round()
age2 = df_clean.loc[valid_numbers & df_clean["Age"].notna(), " age"].astype(str).str.strip().astype(float).round()

same = age1 == age2

print("Same:", same.sum())
print("Different:", (~same).sum())

Same: 48910
Different: 0

-From Valid numbers: 51982 from age column , Age column has Valid numbers: 48910 and NaN: 3072. 
-for Age column- Valid numbers: 48910, after rounding both Age and age has same value.
-For 3072 Age NaN , age had valid no. these 3072 age vlaue will be moved to Age column and age column will be deleted.

In [15990]:
# 2.4-b4 Age vs age

# Fill missing Age values using valid values from ' age'
fill_age = (
    df_clean["Age"].isna()
    & valid_numbers
)

df_clean.loc[fill_age, "Age"] = df_clean.loc[fill_age, " age"]

print("Age values filled:", fill_age.sum())

# Verify that transferred values now match
verification = (
    df_clean.loc[fill_age, "Age"].round()
    == df_clean.loc[fill_age, " age"].astype(str).str.strip().astype(float).round()
)

print("Rows checked:", len(verification))
print("Matching after transfer:", verification.sum())
print("Still different:", (~verification).sum())

Age values filled: 3072
Rows checked: 3072
Matching after transfer: 3072
Still different: 0

In [15991]:
# Delete ' age'
df_clean = df_clean.drop(columns=[" age"])

print("' age' deleted:", " age" not in df_clean.columns)

print("Remaining columns:", df_clean.shape[1])

print("Remaining columns:", df_clean.columns.tolist())

' age' deleted: True
Remaining columns: 37
Remaining columns: ['Patient_ID', 'patient_id', 'Age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'unnamed_0']

age is deleted


### `age` — EDA & Cleaning Notes

**EDA**

* `" age"` contained **51,982 valid numeric values**.
* **3,072** had a corresponding missing `Age`.
* **48,910** had corresponding numeric `Age` values.
* All **48,910** matched after stripping spaces and rounding.

**Cleaning**

* Used the **3,072 valid `" age"` values** to fill missing `Age`.
* Verified all **3,072/3,072** transferred correctly.
* Deleted the redundant `" age"` column after verification.

Age - EDA and Cleaning

In [15992]:
# Age — EDA

print("Data type:", df_clean["Age"].dtype)
print("Total rows:", len(df_clean))
print("Missing values:", df_clean["Age"].isna().sum())

print("Minimum age:", df_clean["Age"].min())
print("Maximum age:", df_clean["Age"].max())

print("\nAge statistics:")
print(df_clean["Age"].describe())

print("\nUnrealistic values:")
print("Negative ages:", (df_clean["Age"] < 0).sum())
print("Age = 0:", (df_clean["Age"] == 0).sum())
print("Age > 120:", (df_clean["Age"] > 120).sum())

Data type: float64
Total rows: 1155000
Missing values: 66864
Minimum age: -31.0
Maximum age: 999.0974210556

Age statistics:
count    1.088136e+06
mean     5.839944e+01
std      6.352645e+01
min     -3.100000e+01
25%      4.200000e+01
50%      5.400000e+01
75%      6.700000e+01
max      9.990974e+02
Name: Age, dtype: float64

Unrealistic values:
Negative ages: 7133
Age = 0: 5554
Age > 120: 10619

In [15993]:
# Column AGE — CLEANING BLOCK

# 1. Replace unrealistic ages
df_clean.loc[df_clean["Age"] < 0, "Age"] = np.nan
df_clean.loc[df_clean["Age"] == 0, "Age"] = np.nan
df_clean.loc[df_clean["Age"] > 120, "Age"] = np.nan

# 3. Compute global median age from valid ages
median_age = df_clean["Age"].median()

# 4. Replace Age NaN with median age
df_clean.loc[df_clean["Age"].isna(), "Age"] = median_age

# 5. Verification
print("Median age used:", median_age)
print("Missing values:", df_clean["Age"].isna().sum())
print("Minimum age:", df_clean["Age"].min())
print("Maximum age:", df_clean["Age"].max())
print("Negative ages:", (df_clean["Age"] < 0).sum())
print("Age = 0:", (df_clean["Age"] == 0).sum())
print("Age > 120:", (df_clean["Age"] > 120).sum())
print("Data type:", df_clean["Age"].dtype)

Median age used: 55.0
Missing values: 0
Minimum age: 0.00041854952983
Maximum age: 120.0
Negative ages: 0
Age = 0: 0
Age > 120: 0
Data type: float64

In [15994]:
print("Age < 1:", (df_clean["Age"] < 1).sum())
print("Age < 5:", (df_clean["Age"] < 5).sum())

Age < 1: 23
Age < 5: 1572

Age cleaning is complete.

In [15995]:
#2.4-b5  Age vs age
print("\nNumber of columns:", len(df_clean.columns))
print("\nCurrent columns:")
print(df_clean.columns.tolist())

Number of columns: 37

Current columns:
['Patient_ID', 'patient_id', 'Age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'unnamed_0']


### Age — EDA & Data Cleaning Notes
**EDA**

* `Age` contains **1,155,000 records** and was initially stored as `float64`.
* Initially, **66,864 values were missing**.
* Initial age range was **-31 to 999.10**, indicating invalid and unrealistic values.
* Identified **7,133 negative ages**, **5,554 zero ages**, and **10,619 ages >120**.
* Initial median age was **54 years**.

**Data Cleaning**
* Converted `Age` to numeric; non-numeric values were converted to `NaN`.
* Replaced negative ages, age = 0, and ages >120 with `NaN`.
* Calculated the median from the remaining valid ages.
* Used the median age (**54**) to impute all remaining missing values.
* Final validation showed **0 missing**, **0 negative**, **0 zero**, and **0 ages >120**.
* **23 values below age 1** were retained because they may represent legitimate infant patients.
* Final age range is approximately **0.0004–120 years**.
* `Age` remains a numeric (`float64`) column.

##2.4-C  Gender vs gender
EDA from prvious analysis`

- `Gender`: 939,965 non-null (81.38%).
- `gender `:28,121  non-null (2.43%); 97.57% missing.
- 25,750 values match directly.
- The columns contain inconsistent representations, including differences in capitalization, whitespace, abbreviations, misspellings, and `0`/`1` values.
- **Decision:** Keep `Gender` as the primary column and use `gender ` to supplement missing values after standardizing and validating the categories.

In [15996]:
# Sanity check: confirm this is the expected state of df_clean before Gender step
print("Shape:", df_clean.shape)
print("Number of columns:", len(df_clean.columns))
print("\nCurrent columns:")
print(df_clean.columns.tolist())
print("Age present:", "Age" in df_clean.columns, "| ' age' present:", " age" in df_clean.columns)
print("Gender present:", "Gender" in df_clean.columns, "| 'gender ' present:", "gender " in df_clean.columns)

Shape: (1155000, 37)
Number of columns: 37

Current columns:
['Patient_ID', 'patient_id', 'Age', 'Gender', 'gender ', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'unnamed_0']
Age present: True | ' age' present: False
Gender present: True | 'gender ' present: True

Checking gender

In [15997]:
# gender — EDA

print("Data type:", df_clean["gender "].dtype)
print("Total rows:", len(df_clean))
print("Missing values:", df_clean["gender "].isna().sum())
print("Distinct categories:", df_clean["gender "].nunique())

print("\nCategory counts:")
print(df_clean["gender "].value_counts(dropna=False))

Data type: str
Total rows: 1155000
Missing values: 1126879
Distinct categories: 23

Category counts:
gender
NaN        1126879
0             1293
Other         1286
f             1274
Unknown       1268
male          1263
O             1243
m             1237
unknown       1231
              1230
other         1229
MALE          1218
Femal         1217
Mal           1214
F             1212
Male          1208
 Female       1207
1             1202
female        1197
-             1190
Male          1185
M             1178
FEMALE        1171
Female        1168
Name: count, dtype: int64

In [15998]:
# --- CLEAN gender COLUMN (Unknown → NaN) ---

import numpy as np

# Step 1: lowercase + strip
gender_lower = (
    df_clean["gender "]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Step 2: map all variants to standard categories
df_clean["gender "] = gender_lower.replace({
    # Male variants
    "male": "Male",
    "m": "Male",
    "mal": "Male",

    # Female variants
    "female": "Female",
    "f": "Female",
    "femal": "Female",

    # Other variants
    "other": "Other",
    "o": "Other",

    # Unknown / invalid → NaN
    "0": np.nan,
    "1": np.nan,
    "nan": np.nan,
    "unknown": np.nan,
    "unkwon": np.nan,
    "n/a": np.nan,
    "na": np.nan,
    "-": np.nan,
    "": np.nan,
    "none": np.nan
})

# Verification
print("Unique gender values:", df_clean["gender "].unique())

print("\nGender value counts:")
print(df_clean["gender "].value_counts(dropna=False))

# Check leftover invalid values
leftovers = df_clean[
    ~df_clean["gender "].isin(["Male", "Female", "Other"]) &
    df_clean["gender "].notna()
]["gender "].unique()

print("\nLeftover invalid variants:", leftovers)

Unique gender values: <StringArray>
[nan, 'Female', 'Other', 'Male']
Length: 4, dtype: str

Gender value counts:
gender
NaN       1134293
Male         8503
Female       8446
Other        3758
Name: count, dtype: int64

Leftover invalid variants: <StringArray>
[]
Length: 0, dtype: str

gender contains 1,126,879 missing values out of 1,155,000 records. Valid/non-missing: 28,121
The column contains multiple inconsistent representations of gender due to different capitalization, abbreviations, spacing, and typos.
Main categories are Male, Female, Other, and Unknown/missing.
Values such as M, m, Male, MALE, and Mal represent Male.
Values such as F, f, Female, FEMALE, and Femal represent Female.
Other/other and O represent Other.
Unknown, blanks, 0, and 1 are treated as missing (NaN) during cleaning.

Gender

In [15999]:
# Gender — EDA

print("Data type:", df_clean["Gender"].dtype)
print("Total rows:", len(df_clean))
print("Missing values:", df_clean["Gender"].isna().sum())
print("Distinct categories:", df_clean["Gender"].nunique())

print("\nCategory counts:")
print(df_clean["Gender"].value_counts(dropna=False))

Data type: str
Total rows: 1155000
Missing values: 215035
Distinct categories: 116

Category counts:
Gender
NaN           215035
               41158
1              40985
 Female        40968
male           40897
               ...
  -               40
  female          38
 Other            37
  M               36
 Femal            32
Name: count, Length: 117, dtype: int64

In [16000]:
# --- CLEAN GENDER COLUMN ---

import numpy as np

# Step 1: lowercase + strip spaces
gender_lower = (
    df_clean["Gender"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Step 2: standardize categories
df_clean["Gender"] = gender_lower.replace({

    # Male
    "male": "Male",
    "m": "Male",
    "mal": "Male",

    # Female
    "female": "Female",
    "f": "Female",
    "femal": "Female",

    # Other
    "other": "Other",
    "o": "Other",

    # Unknown / invalid → NaN
    "unknown": np.nan,
    "unkwon": np.nan,
    "0": np.nan,
    "1": np.nan,
    "-": np.nan,
    "n/a": np.nan,
    "na": np.nan,
    "none": np.nan,
    "": np.nan,
    "nan": np.nan
})

# Step 3: Verification
print("Gender value counts:")
print(df_clean["Gender"].value_counts(dropna=False))

print("\nLeftover invalid values:")
leftovers = df_clean[
    ~df_clean["Gender"].isin(["Male", "Female", "Other"]) &
    df_clean["Gender"].notna()
]["Gender"].unique()

print(leftovers)

Gender value counts:
Gender
NaN       461004
Female    286037
Male      285871
Other     122088
Name: count, dtype: int64

Leftover invalid values:
<StringArray>
[]
Length: 0, dtype: str

461,004 + 286,037 + 285,871 + 122,088 = 1,155,000
So yes, it exactly equals your total row count of 1,155,000. ✅

Your final Gender distribution is therefore:

NaN: 461,004
Female: 286,037
Male: 285,871
Other: 122,088
Total: 1,155,000

Gender — EDA Notes
Total records: 1,155,000
Missing: 215,035 initially
Valid values: 939,965 initially
The column contained 116 distinct categories due to inconsistent formatting, abbreviations, spacing, and typos.
Main intended categories were Male, Female, Other, and Unknown/missing.

Compare Gender and gender
for gender  Valid/non-missing: 28,121, records- after cleaning no. is reduced to 20707 ,(7,414 of the original 28,121 non-missing values in gender were converted to NaN during cleaning).
 corresponding Row in Gender will be checked.

In [16001]:
# Compare valid gender values

x = df_clean.loc[df_clean["gender "].notna(), ["Gender", "gender "]]

same = x["Gender"].astype("string").str.strip().str.lower() == \
       x["gender "].astype("string").str.strip().str.lower()

print("Rows checked:", len(x))
print("Same:", same.sum())
print("NaN in Gender:", x["Gender"].isna().sum())
missing_gender = df_clean[
    df_clean["Gender"].isna() & df_clean["gender "].notna()
][["Gender", "gender "]]

print(missing_gender.head(5))

Rows checked: 20707
Same: 19036
NaN in Gender: 1671
     Gender gender
165     NaN   Other
255     NaN   Other
489     NaN  Female
2251    NaN    Male
3053    NaN    Male

In [16002]:
# Transfer missing Gender values from gender, verify, then delete gender

mask = df_clean["Gender"].isna() & df_clean["gender "].notna()

# Transfer values
df_clean.loc[mask, "Gender"] = df_clean.loc[mask, "gender "]

# Verify transfer
print("Values transferred:", mask.sum())
print("Remaining missing Gender:", df_clean["Gender"].isna().sum())

# Delete redundant gender column
df_clean = df_clean.drop(columns=["gender "])

# Verify deletion
print("gender column exists:", "gender " in df_clean.columns)
print("Total columns:", len(df_clean.columns))

Values transferred: 1671
Remaining missing Gender: 459333
gender column exists: False
Total columns: 36

Standardized Male, Female, and Other variants.
Treated Unknown, blanks, 0, and 1 as missing.
After cleaning, 20,707 valid values remained.
Compared with Gender: 19,036 matched and 1,671 had missing Gender.
Transferred the 1,671 values to Gender.
Deleted the redundant gender column.

## 2.5 Admission Date

In [16003]:
# Sanity check: confirm state of df_clean before Admission_Date step
print("Shape:", df_clean.shape)
print("Number of columns:", len(df_clean.columns))
print("drug_name present:", "drug_name" in df_clean.columns, "(should be False)")
print("Drug_Name present:", "Drug_Name" in df_clean.columns, "(should be True)")
print("Admission_Date present:", "Admission_Date" in df_clean.columns)

Shape: (1155000, 36)
Number of columns: 36
drug_name present: True (should be False)
Drug_Name present: True (should be True)
Admission_Date present: True

Admission date

In [16004]:
# Admission_Date — EDA

s = df_clean["Admission_Date"]

print("Data type:", s.dtype)
print("Total rows:", len(s))

print("\nFirst 10 values:")
print(s.head(10))

print("\nNaN:", s.isna().sum())
print("Blank/space:", s.astype("string").str.strip().eq("").sum())
print("0:", s.astype("string").str.strip().eq("0").sum())
print("-:", s.astype("string").str.strip().eq("-").sum())

Data type: str
Total rows: 1155000

First 10 values:
0                 NaN
1          2022/06/10
2    October 22, 2021
3          2020-02-23
4          12/08/2023
5                 NaN
6        May 08, 2022
7    January 05, 2020
8          20/06/2023
9          28/08/2020
Name: Admission_Date, dtype: str

NaN: 335312
Blank/space: 0
0: 0
-: 0

In [16005]:
# Admission_Date — count valid date patterns

s = df_clean["Admission_Date"].astype("string").str.strip()

patterns = {
    "Year only (YYYY)": r"\d{4}",
    "YYYY/MM/DD": r"\d{4}/\d{2}/\d{2}",
    "YYYY-MM-DD": r"\d{4}-\d{2}-\d{2}",
    "DD/MM/YYYY": r"\d{2}/\d{2}/\d{4}",
    "DD-MM-YYYY": r"\d{2}-\d{2}-\d{4}",
    "DD.MM.YYYY": r"\d{2}\.\d{2}\.\d{4}",
    "Month DD, YYYY": r"[A-Za-z]+ \d{1,2}, \d{4}",
    "DD-Mon-YYYY": r"\d{2}-[A-Za-z]{3}-\d{4}",
}

print("Total rows:", len(s))
print("NaN:", s.isna().sum())

classified = pd.Series(False, index=s.index)

for name, pattern in patterns.items():
    mask = s.str.fullmatch(pattern, na=False)
    print(f"{name}: {mask.sum()}")
    classified |= mask

print("\nValues matching a known format:", classified.sum())
print("Values not matching known formats:",
      (s.notna() & ~classified).sum())

Total rows: 1155000
NaN: 335312
Year only (YYYY): 102797
YYYY/MM/DD: 102615
YYYY-MM-DD: 102337
DD/MM/YYYY: 102789
DD-MM-YYYY: 102230
DD.MM.YYYY: 101999
Month DD, YYYY: 102896
DD-Mon-YYYY: 102025

Values matching a known format: 819688
Values not matching known formats: 0

In [16006]:
# First 10 unclassified Admission_Date values

s = df_clean["Admission_Date"].astype("string").str.strip()

known_patterns = [
    r"\d{4}",
    r"\d{4}/\d{2}/\d{2}",
    r"\d{4}-\d{2}-\d{2}",
    r"\d{2}/\d{2}/\d{4}",
    r"\d{2}-\d{2}-\d{4}",
    r"\d{2}\.\d{2}\.\d{4}",
    r"[A-Za-z]+ \d{1,2}, \d{4}",
]

matched = pd.Series(False, index=s.index)

for pattern in known_patterns:
    matched |= s.str.fullmatch(pattern, na=False)

unclassified = s[s.notna() & ~matched]

print("Unclassified count:", len(unclassified))
print("\nFirst 10 unclassified values:")
print(unclassified.head(50))

Unclassified count: 102025

First 10 unclassified values:
12     29-Oct-2024
22     31-Jul-2025
24     22-Oct-2022
25     08-Dec-2024
32     31-Jan-2020
34     21-Mar-2023
36     15-Mar-2019
37     21-Nov-2024
40     29-Nov-2025
41     25-Mar-2024
78     23-Oct-2022
105    20-Dec-2020
108    13-Aug-2024
109    08-May-2020
119    25-May-2024
126    18-Mar-2022
141    17-Mar-2024
149    02-Sep-2019
154    01-Apr-2020
160    21-Apr-2020
161    05-Aug-2024
162    22-Nov-2023
168    29-Jan-2025
171    21-Oct-2018
180    28-Jul-2021
206    16-Dec-2020
215    17-Jan-2021
240    21-Aug-2020
244    28-Jan-2023
272    23-Aug-2021
303    03-Dec-2022
306    03-Dec-2018
307    15-Dec-2018
308    16-Jan-2024
322    21-May-2018
357    12-Oct-2019
367    20-Jan-2022
371    06-Apr-2022
372    15-Jun-2018
385    24-Jul-2022
396    01-Jun-2020
412    10-Oct-2024
448    13-Oct-2023
456    19-Jul-2019
460    20-Oct-2021
461    06-Mar-2021
475    28-Nov-2019
500    25-Dec-2024
505    08-Mar-2025
510    15-Feb-2019
Name: Admission_Date, dtype: string

In [16007]:
s = df_clean["Admission_Date"].astype("string").str.strip()

known_patterns = [
    r"\d{4}",
    r"\d{4}/\d{2}/\d{2}",
    r"\d{4}-\d{2}-\d{2}",
    r"\d{2}/\d{2}/\d{4}",
    r"\d{2}-\d{2}-\d{4}",
    r"\d{2}\.\d{2}\.\d{4}",
    r"[A-Za-z]+ \d{1,2}, \d{4}",
    r"\d{2}-[A-Za-z]{3}-\d{4}",
]

matched = pd.Series(False, index=s.index)

for pattern in known_patterns:
    matched |= s.str.fullmatch(pattern, na=False)

unclassified = s[s.notna() & ~matched]

print("Unclassified count:", len(unclassified))
print("\nFirst 30 unclassified values:")
print(unclassified.head(30).to_list())

Unclassified count: 0

First 30 unclassified values:
[]

this 8th format cover all formats in dataset

In [16008]:
import pandas as pd

s = df_clean["Admission_Date"].astype("string").str.strip()
dates = pd.Series(pd.NaT, index=s.index, dtype="datetime64[ns]")
matched = s.isna()

formats = [
    (r"\d{4}", "%Y"),
    (r"\d{4}/\d{2}/\d{2}", "%Y/%m/%d"),
    (r"\d{4}-\d{2}-\d{2}", "%Y-%m-%d"),
    (r"\d{2}/\d{2}/\d{4}", "%d/%m/%Y"),
    (r"\d{2}\.\d{2}\.\d{4}", "%d.%m.%Y"),
    (r"[A-Za-z]+ \d{1,2}, \d{4}", "%B %d, %Y"),
    (r"\d{2}-[A-Za-z]{3}-\d{4}", "%d-%b-%Y")
]

for pattern, fmt in formats:
    mask = s.str.fullmatch(pattern, na=False)
    parsed = pd.to_datetime(s[mask], format=fmt, errors="coerce")
    dates.loc[mask] = parsed
    matched |= mask

# Handle numeric hyphen dates when the day/month order is clear
mask = s.str.fullmatch(r"\d{2}-\d{2}-\d{4}", na=False)
parts = s[mask].str.split("-", expand=True)
first = parts[0].astype(int)
second = parts[1].astype(int)

day_first = mask.copy()
day_first.loc[mask] = (first > 12) | (second <= 12)

month_first = mask.copy()
month_first.loc[mask] = (second > 12) & (first <= 12)

# Parse only unambiguous dates
dates.loc[day_first[day_first].index] = pd.to_datetime(
    s[day_first], format="%d-%m-%Y", errors="coerce"
)
dates.loc[month_first[month_first].index] = pd.to_datetime(
    s[month_first], format="%m-%d-%Y", errors="coerce"
)

matched |= day_first | month_first

# Report results; do not replace the original column yet
remaining = s.notna() & dates.isna()

print("Total rows:", len(s))
print("Original missing values:", s.isna().sum())
print("Dates converted:", dates.notna().sum())
print("Remaining values:", remaining.sum())
print("\nRemaining examples:")
print(s[remaining].head(20))

Total rows: 1155000
Original missing values: 335312
Dates converted: 819688
Remaining values: 0

Remaining examples:
Series([], Name: Admission_Date, dtype: string)

In [16009]:
df_clean["Admission_Date"] = dates

print("Data type:", df_clean["Admission_Date"].dtype)
print("Missing dates:", df_clean["Admission_Date"].isna().sum())
print("Earliest date:", df_clean["Admission_Date"].min())
print("Latest date:", df_clean["Admission_Date"].max())

Data type: datetime64[ns]
Missing dates: 335312
Earliest date: 2018-01-01 00:00:00
Latest date: 2025-12-30 00:00:00

In [16010]:
col = "Admission_Date"

today = pd.Timestamp.today().normalize()

print("Future dates:", (df_clean[col] > today).sum())
print("Dates before 2000:", (df_clean[col] < pd.Timestamp("2000-01-01")).sum())

Future dates: 0
Dates before 2000: 0

### Admission_Date — EDA and Data Cleaning

**EDA**

* Total rows: 1,155,000
* Missing values: 335,312 (29.0%)
* Multiple date formats identified.
* Date range: 2018-01-01 to 2025-12-30.
* Future dates: 0
* Dates before 2000: 0

**Data Cleaning**

* Standardized all identified date formats.
* Converted year-only values to January 1 of the corresponding year.
* Preserved missing values (`NaT`).
* Converted the column to Pandas `datetime64[ns]`.
* Successfully converted 819,688 dates; zero values remained unconverted.
#NaN 335,312+ Real value 819,688=1,155,000

**Result:** The date column is standardized and ready for date-based analysis and feature engineering.

In [16011]:
# Sanity check: confirm state of df_clean before next step
print("Shape:", df_clean.shape)
print("Number of columns:", len(df_clean.columns))
print("Admission_Date dtype:", df_clean["Admission_Date"].dtype)
print("Admission_Year present:", "Admission_Year" in df_clean.columns)
print("\nCurrent columns:")
print(df_clean.columns.tolist())

Shape: (1155000, 36)
Number of columns: 36
Admission_Date dtype: datetime64[ns]
Admission_Year present: False

Current columns:
['Patient_ID', 'patient_id', 'Age', 'Gender', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'drug_name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d', 'unnamed_0']

Alcohol use

In [16012]:
col = "Alcohol_Use"

print("Data type:", df_clean[col].dtype)
print("Total rows:", len(df_clean))
print("Missing values:", df_clean[col].isna().sum())
print("Blank/space values:", df_clean[col].astype("string").str.strip().eq("").sum())
print("Unique values:", df_clean[col].nunique(dropna=True))

print("\nValue counts:")
print(df_clean[col].value_counts(dropna=False))

print("\nFirst 10 values:")
print(df_clean[col].head(10))

Data type: str
Total rows: 1155000
Missing values: 278813
Blank/space values: 0
Unique values: 16

Value counts:
Alcohol_Use
NaN                278813
daily               55344
-                   55050
none                55000
Occasional          54976
Yes                 54948
1-2 drinks/week     54919
yes                 54849
Social              54819
no                  54766
No                  54704
Heavy               54655
Daily               54593
occasional          54441
heavy               54396
Unknown             54392
social              54335
Name: count, dtype: int64

First 10 values:
0          -
1         no
2      Heavy
3        NaN
4     Social
5     Social
6    Unknown
7         no
8    Unknown
9          -
Name: Alcohol_Use, dtype: str

In [16013]:
col = "Alcohol_Use"

df_clean[col] = df_clean[col].astype("string").str.strip().str.lower()

mapping = {
    "no": "No",
    "none": "No",
    "-": "No",
    "yes": "Yes",
    "social": "Social",
    "occasional": "Occasional",
    "1-2 drinks/week": "1-2 drinks/week",
    "daily": "Daily",
    "heavy": "Heavy",
    "unknown": "Unknown"
}

df_clean[col] = df_clean[col].replace(mapping)
df_clean[col] = df_clean[col].fillna("Unknown")

In [16014]:
print("Missing values:", df_clean["Alcohol_Use"].isna().sum())
print("Unique values:", df_clean["Alcohol_Use"].nunique())

print("\nValue counts:")
print(df_clean["Alcohol_Use"].value_counts(dropna=False))

Missing values: 0
Unique values: 8

Value counts:
Alcohol_Use
Unknown            333205
No                 219520
Daily              109937
Yes                109797
Occasional         109417
Social             109154
Heavy              109051
1-2 drinks/week     54919
Name: count, dtype: Int64

In [16015]:
print(df_clean["Alcohol_Use"].value_counts(dropna=False))
print(df_clean["Alcohol_Use"].value_counts(dropna=False).sum())
print(len(df_clean))

Alcohol_Use
Unknown            333205
No                 219520
Daily              109937
Yes                109797
Occasional         109417
Social             109154
Heavy              109051
1-2 drinks/week     54919
Name: count, dtype: Int64
1155000
1155000

### Alcohol_Use — EDA and Data Cleaning Notes

**EDA Findings**

* Total rows: 1,155,000
* Original missing values: 278,813
* Original unique values: 16, including inconsistent capitalization and alternative labels.
* The column contained values such as `daily` / `Daily`, `yes` / `Yes`, `no` / `No`, `none`, `-`, and `1-2 drinks/week`.

**Data Cleaning Performed**

* Standardized text by removing leading/trailing whitespace and converting values to consistent capitalization.
* Mapped `none` and `-` to `No`, based on the assumption that both represent no alcohol consumption.
* Standardized capitalization for `Yes`, `Social`, `Occasional`, `Daily`, `Heavy`, and `Unknown`.
* Preserved `1-2 drinks/week` as a separate category from `Occasional` because it specifies a drinking frequency.
* Replaced missing values with `Unknown`.

**Validation Results**

* Total rows: 1,155,000
* Missing values after cleaning: 0
* Unique categories after cleaning: 8
* Unexpected values: 0
* Sum of category counts: 1,155,000

**Final Categories and Counts**

| Category        |         Count |
| --------------- | ------------: |
| Unknown         |       333,205 |
| No              |       219,520 |
| Daily           |       109,937 |
| Yes             |       109,797 |
| Occasional      |       109,417 |
| Social          |       109,154 |
| Heavy           |       109,051 |
| 1-2 drinks/week |        54,919 |
| **Total**       | **1,155,000** |

**Conclusion:** The `Alcohol_Use` column has been standardized and validated. All rows are accounted for, and no unexpected categories remain. The mappings of `none` and `-` to `No` are documented assumptions that should be retained in the project notes.

Smoking status

In [16016]:
# SMOKING_STATUS — MINIMAL INSPECTION

print("Data type:", df_clean["Smoking_Status"].dtype)

print("\nRaw values (first 10):")
print(df_clean["Smoking_Status"].head(10))

print("\nMissing values:")
print(df_clean["Smoking_Status"].isna().sum())

# All unique values, preserving missing values
print("\nAll unique values:")
print(pd.Series(df_clean["Smoking_Status"].astype("string").unique()))

# All unique values with counts, including missing values
print("\nAll unique values with counts:")
print(df_clean["Smoking_Status"].value_counts(dropna=False))

Data type: str

Raw values (first 10):
0       true
1        Yes
2     Former
3    current
4        yes
5          1
6         NO
7     former
8      Never
9     Former
Name: Smoking_Status, dtype: str

Missing values:
229460

All unique values:
0          true
1           Yes
2        Former
3       current
4           yes
5             1
6            NO
7        former
8         Never
9         false
10    Ex-smoker
11          YES
12            0
13      Current
14            y
15         <NA>
16    ex smoker
17            N
18            n
19            Y
20            -
21
22           No
23           no
24        never
25      Unknown
dtype: string

All unique values with counts:
Smoking_Status
NaN          229460
No            37384
Unknown       37324
Yes           37309
current       37299
false         37223
YES           37222
Current       37192
Y             37179
n             37097
NO            37078
0             37068
y             37049
yes           37025
ex smoker     36974
never         36944
-             36939
              36927
Ex-smoker     36912
Former        36831
true          36806
Never         36790
1             36768
no            36752
N             36738
former        36710
Name: count, dtype: int64

In [16017]:
# SMOKING_STATUS — CLEANING

smk = df_clean["Smoking_Status"].astype("string").str.strip().str.lower()

smk_map = {
    # Never
    "never": "Never",

    # No
    "no": "No",
    "n": "No",
    "0": "No",
    "false": "No",

    # Former
    "former": "Former",
    "ex-smoker": "Former",
    "ex smoker": "Former",

    # Yes
    "current": "Yes",
    "yes": "Yes",
    "true": "Yes",
    "y": "Yes",
    "1": "Yes",

    # Unknown
    "unknown": "Unknown",
    "na": "Unknown",
    "-": "Unknown",
    "": "Unknown"
}

df_clean["Smoking_Status"] = smk.map(smk_map).fillna("Unknown")

In [16018]:
# SMOKING_STATUS — VERIFICATION

print("Missing values:", df_clean["Smoking_Status"].isna().sum())
print("Unique categories:", df_clean["Smoking_Status"].nunique())

print("\nCategory counts:")
print(df_clean["Smoking_Status"].value_counts(dropna=False))

Missing values: 0
Unique categories: 5

Category counts:
Smoking_Status
Unknown    340650
Yes        333849
No         259340
Former     147427
Never       73734
Name: count, dtype: int64

### Smoking_Status — EDA and Data Cleaning Notes

**EDA Findings**

* Total rows: 1,155,000
* Original missing values: 229,460
* Original values contained inconsistent capitalization, alternative labels, and blank/dash entries.

**Data Cleaning Performed**

* Removed leading/trailing whitespace and standardized text to lowercase before mapping.
* Standardized smoking indicators into five categories: `Never`, `No`, `Former`, `Yes`, and `Unknown`.
* Mapped `ex-smoker` and `ex smoker` to `Former`.
* Mapped `current`, `yes`, `true`, `y`, and `1` to `Yes`.
* Mapped `no`, `n`, `0`, and `false` to `No`.
* Replaced missing, blank, dash, and unrecognized values with `Unknown`.

Route

In [16019]:
# ROUTE — INITIAL INSPECTION

col = "Route"

print("Data type:", df_clean[col].dtype)

print("\nRaw values (first 10):")
print(df_clean[col].head(10))

print("\nMissing values:", df_clean[col].isna().sum())

print("\nAll unique values:")
print(pd.Series(df_clean[col].astype("string").unique()))

print("\nAll unique values with counts:")
print(df_clean[col].value_counts(dropna=False))

Data type: str

Raw values (first 10):
0             NaN
1             NaN
2              iv
3            oral
4              SC
5     intravenous
6              im
7    subcutaneous
8            Oral
9         inhaled
Name: Route, dtype: str

Missing values: 224379

All unique values:
0              <NA>
1                iv
2              oral
3                SC
4       intravenous
           ...
130    intravenous
131       topical
132              -
133       TOPICAL
134         inhaled
Length: 135, dtype: string

All unique values with counts:
Route
NaN               224379
Ophthalmic         35992
ORAL               35979
Topical            35954
                   35933
                   ...
 Intramuscular        33
Ophthalmic            33
 NA                   32
-                     31
intravenous           28
Name: count, Length: 135, dtype: int64

In [16020]:
# 9. ROUTE — CLEANING AND VERIFICATION

col = "Route"

# Step 1: Standardize text
route = df_clean[col].astype("string").str.strip().str.lower()

# Step 2: Map equivalent route labels
route_map = {
    "iv": "IV",
    "intravenous": "IV",
    "im": "IM",
    "intramuscular": "IM",
    "sc": "SC",
    "subcutaneous": "SC",
    "oral": "Oral",
    "topical": "Topical",
    "inhaled": "Inhaled",
    "ophthalmic": "Ophthalmic",
    "rectal": "Rectal"
}

# Step 3: Apply mapping
df_clean[col] = route.map(route_map).fillna(route)

# Step 4: Standardize unknown and missing values
unknown_values = ["unknown", "", "-", "na", "n/a"]

df_clean[col] = df_clean[col].replace(unknown_values, "Unknown")
df_clean[col] = df_clean[col].fillna("Unknown")

# Step 5: Verify results
print("Missing values:", df_clean[col].isna().sum())
print("Unique categories:", df_clean[col].nunique())

print("\nCategory counts:")
print(df_clean[col].value_counts(dropna=False))

print("\nAll unique values:")
print(df_clean[col].unique())

print("\nSum of category counts:",
      df_clean[col].value_counts(dropna=False).sum())
print("Total rows:", len(df_clean))

Missing values: 0
Unique categories: 9

Category counts:
Route
Unknown       331862
IV            143153
SC            143108
IM            143072
Oral          107735
Topical       107337
Inhaled        71564
Rectal         71000
Ophthalmic     36169
Name: count, dtype: int64

All unique values:
<StringArray>
[   'Unknown',         'IV',       'Oral',         'SC',         'IM',
    'Inhaled',     'Rectal', 'Ophthalmic',    'Topical']
Length: 9, dtype: str

Sum of category counts: 1155000
Total rows: 1155000

### Route — EDA and Data Cleaning Notes

**EDA Findings**

* Total rows: 1,155,000
* Original missing values: 224,379
* Original unique values: 135, including inconsistent capitalization, whitespace, abbreviations, and unspecified values.

**Data Cleaning Performed**

* Removed leading and trailing whitespace and standardized text for consistent matching.
* Standardized equivalent route labels:

  * `iv`, `intravenous` → `IV`
  * `im`, `intramuscular` → `IM`
  * `sc`, `subcutaneous` → `SC`
* Standardized capitalization for `Oral`, `Topical`, `Inhaled`, `Ophthalmic`, and `Rectal`.
* Replaced missing values, blanks, `-`, `na`, `n/a`, and `unknown` with `Unknown`.

**Validation Results**

* Missing values after cleaning: 0
* Final unique categories: 9
* Sum of category counts: 1,155,000
* Data type: String

**Final Category Counts**

| Category   |         Count |
| ---------- | ------------: |
| Unknown    |       331,862 |
| IV         |       143,153 |
| SC         |       143,108 |
| IM         |       143,072 |
| Oral       |       107,735 |
| Topical    |       107,337 |
| Inhaled    |        71,564 |
| Rectal     |        71,000 |
| Ophthalmic |        36,169 |
| **Total**  | **1,155,000** |

**Conclusion:** The `Route` column has been standardized and validated. All rows are accounted for, with unspecified or missing route information grouped under `Unknown`.

11. Ethinicity

In [16021]:

# ETHNICITY — INITIAL INSPECTION

col = "Ethnicity"

print("Data type:", df_clean[col].dtype)

print("\nFirst 10 raw values:")
print(df_clean[col].head(10))

print("\nMissing values:", df_clean[col].isna().sum())

print("\nUnique values:")
print(sorted(df_clean[col].dropna().astype("string").unique().tolist()))

print("\nUnique value count:", df_clean[col].nunique(dropna=False))

print("\nValue counts (including missing values):")
print(df_clean[col].value_counts(dropna=False))

Data type: str

First 10 raw values:
0               Other
1             Chinese
2               Other
3                 NaN
4               ASIAN
5    African American
6            HISPANIC
7               other
8                   -
9               White
Name: Ethnicity, dtype: str

Missing values: 203355

Unique values:
[' ', '-', 'AA', 'ASIAN', 'African American', 'Asian', 'Black', 'CAUCASIAN', 'Caucasian', 'Chinese', 'HISPANIC', 'Hispanic', 'Indian', 'Japanese', 'Latino', 'Mixed', 'Native American', 'Other', 'Pacific Islander', 'Prefer not to say', 'Unknown', 'White', 'african american', 'asian', 'black', 'caucasian', 'hispanic', 'latina', 'other', 'white']

Unique value count: 31

Value counts (including missing values):
Ethnicity
NaN                  203355
Native American       32219
hispanic              32070
ASIAN                 32033
Latino                31948
white                 31944
caucasian             31890
Hispanic              31847
asian                 31833
African American      31806
Chinese               31786
african american      31779
White                 31755
Pacific Islander      31735
HISPANIC              31726
CAUCASIAN             31723
Japanese              31716
black                 31715
latina                31655
-                     31651
AA                    31649
Black                 31633
Unknown               31601
Asian                 31581
Prefer not to say     31581
                      31568
Indian                31542
Caucasian             31519
Other                 31500
other                 31410
Mixed                 31230
Name: count, dtype: int64

In [16022]:

# ETHNICITY — CLEANING

col = "Ethnicity"

# Standardize text
eth = df_clean[col].astype("string").str.strip().str.lower()

# Mapping dictionary
ethnicity_map = {
    # Asian
    "asian": "Asian",
    "chinese": "Asian",
    "japanese": "Asian",

    # Black
    "black": "Black",

    # White
    "white": "White",
    "caucasian": "White",

    # Hispanic
    "hispanic": "Hispanic",
    "latino": "Hispanic",
    "latina": "Hispanic",

    # African American
    "african american": "African American",
    "aa": "African American",

    # Other categories
    "indian": "Indian",
    "native american": "Native American",
    "pacific islander": "Pacific Islander",
    "other": "Other",
    "mixed": "Mixed",
    "prefer not to say": "Prefer not to say",
    "unknown": "Unknown",

    # Non-informative values
    "": "Unknown",
    "-": "Unknown"
}

# Check unmapped values BEFORE applying the mapping
unmapped = eth[~eth.isin(ethnicity_map.keys()) & eth.notna()]

print("Unmapped values:")
print(unmapped.value_counts())

# Apply mapping
df_clean[col] = eth.map(ethnicity_map).fillna("Unknown")

Unmapped values:
Series([], Name: count, dtype: Int64)

In [16023]:

# ETHNICITY — FINAL VERIFICATION

col = "Ethnicity"

print("Data type:", df_clean[col].dtype)

print("\nMissing values:", df_clean[col].isna().sum())

print("\nCategory counts:")
print(df_clean[col].value_counts(dropna=False))

expected_categories = [
    "Asian", "Black", "White", "Hispanic", "African American",
    "Native American", "Pacific Islander", "Indian", "Other",
    "Mixed", "Prefer not to say", "Unknown"
]

unexpected = df_clean.loc[
    ~df_clean[col].isin(expected_categories), col
]

print("\nUnexpected values:")
print(unexpected.value_counts())

print("\nNumber of unexpected rows:", len(unexpected))
print("Total rows:", len(df_clean))
print("Unique categories:", df_clean[col].nunique())

Data type: str

Missing values: 0

Category counts:
Ethnicity
Unknown              298175
Hispanic             159246
Asian                158949
White                158831
African American      95234
Black                 63348
Other                 62910
Native American       32219
Pacific Islander      31735
Prefer not to say     31581
Indian                31542
Mixed                 31230
Name: count, dtype: int64

Unexpected values:
Series([], Name: count, dtype: int64)

Number of unexpected rows: 0
Total rows: 1155000
Unique categories: 12

drug_name

In [16024]:
# Inspect drug_name column

col = "drug_name"
s = df_clean[col].astype("string")
trimmed = s.str.strip()

print("Data type:", df_clean[col].dtype)
print("Total rows:", len(df_clean))
print("NaN:", s.isna().sum())
print("0:", trimmed.eq("0").fillna(False).sum())
print("-:", trimmed.eq("-").fillna(False).sum())
print("Empty/whitespace:", trimmed.eq("").fillna(False).sum())

print("\nDistinct non-missing values:", df_clean[col].nunique())
print("\nAll distinct non-missing values:")
print(sorted(s.dropna().unique().tolist()))

print("\nFirst 20 values:")
print(df_clean[col].head(20).to_string())

print("\nValue counts including missing:")
print(df_clean[col].value_counts(dropna=False))

Data type: str
Total rows: 1155000
NaN: 179740
0: 0
-: 13022
Empty/whitespace: 12805

Distinct non-missing values: 76

All distinct non-missing values:
[' ', '-', '--', 'AMOXICILLIN', 'ATORVASTATIN', 'Albuterol', 'Amlodipine', 'Amoxicilin', 'Amoxicillin', 'Amoxycillin', 'Atorvastain', 'Atorvastatin', 'Azithromycin', 'Ciprofloxacin', 'Clopidogrel', 'Doxycycline', 'Duloxetine', 'Escitalopram', 'Fluticasone', 'Furosemide', 'GABAPENTIN', 'Gabapentin', 'Gabapentine', 'Hydrochlorothiazide', 'IBUPROFEN', 'INSULIN GLARGINE', 'Ibuprofen', 'Ibuprophen', 'Insulin  Glargine', 'Insulin Glargine', 'LISINOPRIL', 'Levothyroxine', 'Lisinipril', 'Lisinopril', 'Losartan', 'METFORMIN', 'Met formin', 'Metformin', 'Metformine', 'Metoprolol', 'Montelukast', 'OMEPRAZOLE', 'Omeprazol', 'Omeprazole', 'Pantoprazole', 'Prednisone', 'Rosuvastatin', 'Sertraline', 'Simvastatin', 'TRAMADOL', 'Tramadol', 'Tramadole', 'UNKNOWN', 'WARFARIN', 'Warfarin', 'Warfarine', 'amoxicillin', 'amoxycillin', 'atorvastatin', 'atorvastatine', 'gabapentin', 'gabapentine', 'ibuprofen', 'ibuprofin', 'insulin glargine', 'lisino pril', 'lisinopril', 'metformin', 'metformine', 'na', 'none', 'omeprazol', 'omeprazole', 'tramadol', 'warfarin', 'warfarine']

First 20 values:
0           Sertraline
1                  NaN
2           gabapentin
3          Atorvastain
4           Gabapentin
5          gabapentine
6           metformine
7     insulin glargine
8          AMOXICILLIN
9                  NaN
10           warfarine
11          Metoprolol
12           metformin
13           Omeprazol
14         Amoxicillin
15        Rosuvastatin
16         amoxycillin
17                 NaN
18         AMOXICILLIN
19         Amoxicillin

Value counts including missing:
drug_name
NaN            179740
Omeprazole      13171
Warfarine       13153
amoxicillin     13120
Albuterol       13114
                ...
METFORMIN       12608
Amoxycillin     12606
na              12599
Tramadol        12559
Metoprolol      12481
Name: count, Length: 77, dtype: int64

In [16025]:
col = "Drug_Name"
s = df_clean[col].astype("string")
trimmed = s.str.strip()

print("Data type:", df_clean[col].dtype)
print("Total rows:", len(df_clean))
print("NaN:", s.isna().sum())
print("0:", trimmed.eq("0").fillna(False).sum())
print("-:", trimmed.eq("-").fillna(False).sum())
print("Empty/whitespace:", trimmed.eq("").fillna(False).sum())

print("\nDistinct non-missing values:", df_clean[col].nunique())
print("\nAll distinct non-missing values:")
print(sorted(s.dropna().unique().tolist()))

print("\nFirst 20 values:")
print(df_clean[col].head(20).to_string())

print("\nValue counts including missing:")
print(df_clean[col].value_counts(dropna=False))

Data type: str
Total rows: 1155000
NaN: 148206
0: 0
-: 13535
Empty/whitespace: 13133

Distinct non-missing values: 392

All distinct non-missing values:
[' ', '  -', '  -  ', '  --', '  --  ', '  AMOXICILLIN', '  AMOXICILLIN  ', '  ATORVASTATIN', '  ATORVASTATIN  ', '  Albuterol', '  Albuterol  ', '  Amlodipine', '  Amlodipine  ', '  Amoxicilin', '  Amoxicilin  ', '  Amoxicillin', '  Amoxicillin  ', '  Amoxycillin', '  Amoxycillin  ', '  Atorvastain', '  Atorvastain  ', '  Atorvastatin', '  Atorvastatin  ', '  Azithromycin', '  Azithromycin  ', '  Ciprofloxacin', '  Ciprofloxacin  ', '  Clopidogrel', '  Clopidogrel  ', '  Doxycycline', '  Doxycycline  ', '  Duloxetine', '  Duloxetine  ', '  Escitalopram', '  Escitalopram  ', '  Fluticasone', '  Fluticasone  ', '  Furosemide', '  Furosemide  ', '  GABAPENTIN', '  GABAPENTIN  ', '  Gabapentin', '  Gabapentin  ', '  Gabapentine', '  Gabapentine  ', '  Hydrochlorothiazide', '  Hydrochlorothiazide  ', '  IBUPROFEN', '  IBUPROFEN  ', '  INSULIN GLARGINE', '  INSULIN GLARGINE  ', '  Ibuprofen', '  Ibuprofen  ', '  Ibuprophen', '  Ibuprophen  ', '  Insulin  Glargine', '  Insulin  Glargine  ', '  Insulin Glargine', '  Insulin Glargine  ', '  LISINOPRIL', '  LISINOPRIL  ', '  Levothyroxine', '  Levothyroxine  ', '  Lisinipril', '  Lisinipril  ', '  Lisinopril', '  Lisinopril  ', '  Losartan', '  Losartan  ', '  METFORMIN', '  METFORMIN  ', '  Met formin', '  Met formin  ', '  Metformin', '  Metformin  ', '  Metformine', '  Metformine  ', '  Metoprolol', '  Metoprolol  ', '  Montelukast', '  Montelukast  ', '  N/A', '  N/A  ', '  NA', '  NA  ', '  None', '  None  ', '  OMEPRAZOLE', '  OMEPRAZOLE  ', '  Omeprazol', '  Omeprazol  ', '  Omeprazole', '  Omeprazole  ', '  Pantoprazole', '  Pantoprazole  ', '  Prednisone', '  Prednisone  ', '  Rosuvastatin', '  Rosuvastatin  ', '  Sertraline', '  Sertraline  ', '  Simvastatin', '  Simvastatin  ', '  TRAMADOL', '  TRAMADOL  ', '  Tramadol', '  Tramadol  ', '  Tramadole', '  Tramadole  ', '  UNKNOWN', '  UNKNOWN  ', '  WARFARIN', '  WARFARIN  ', '  Warfarin', '  Warfarin  ', '  Warfarine', '  Warfarine  ', '  amoxicillin', '  amoxicillin  ', '  amoxycillin', '  amoxycillin  ', '  atorvastatin', '  atorvastatin  ', '  atorvastatine', '  atorvastatine  ', '  gabapentin', '  gabapentin  ', '  gabapentine', '  gabapentine  ', '  ibuprofen', '  ibuprofen  ', '  ibuprofin', '  ibuprofin  ', '  insulin glargine', '  insulin glargine  ', '  lisino pril', '  lisino pril  ', '  lisinopril', '  lisinopril  ', '  metformin', '  metformin  ', '  metformine', '  metformine  ', '  n/a', '  n/a  ', '  na', '  na  ', '  none', '  none  ', '  omeprazol', '  omeprazol  ', '  omeprazole', '  omeprazole  ', '  tramadol', '  tramadol  ', '  warfarin', '  warfarin  ', '  warfarine', '  warfarine  ', ' -', ' --', ' AMOXICILLIN', ' ATORVASTATIN', ' Albuterol', ' Amlodipine', ' Amoxicilin', ' Amoxicillin', ' Amoxycillin', ' Atorvastain', ' Atorvastatin', ' Azithromycin', ' Ciprofloxacin', ' Clopidogrel', ' Doxycycline', ' Duloxetine', ' Escitalopram', ' Fluticasone', ' Furosemide', ' GABAPENTIN', ' Gabapentin', ' Gabapentine', ' Hydrochlorothiazide', ' IBUPROFEN', ' INSULIN GLARGINE', ' Ibuprofen', ' Ibuprophen', ' Insulin  Glargine', ' Insulin Glargine', ' LISINOPRIL', ' Levothyroxine', ' Lisinipril', ' Lisinopril', ' Losartan', ' METFORMIN', ' Met formin', ' Metformin', ' Metformine', ' Metoprolol', ' Montelukast', ' N/A', ' NA', ' None', ' OMEPRAZOLE', ' Omeprazol', ' Omeprazole', ' Pantoprazole', ' Prednisone', ' Rosuvastatin', ' Sertraline', ' Simvastatin', ' TRAMADOL', ' Tramadol', ' Tramadole', ' UNKNOWN', ' WARFARIN', ' Warfarin', ' Warfarine', ' amoxicillin', ' amoxycillin', ' atorvastatin', ' atorvastatine', ' gabapentin', ' gabapentine', ' ibuprofen', ' ibuprofin', ' insulin glargine', ' lisino pril', ' lisinopril', ' metformin', ' metformine', ' n/a', ' na', ' none', ' omeprazol', ' omeprazole', ' tramadol', ' warfarin', ' warfarine', '-', '- ', '--', '-- ', 'AMOXICILLIN', 'AMOXICILLIN ', 'ATORVASTATIN', 'ATORVASTATIN ', 'Albuterol', 'Albuterol ', 'Amlodipine', 'Amlodipine ', 'Amoxicilin', 'Amoxicilin ', 'Amoxicillin', 'Amoxicillin ', 'Amoxycillin', 'Amoxycillin ', 'Atorvastain', 'Atorvastain ', 'Atorvastatin', 'Atorvastatin ', 'Azithromycin', 'Azithromycin ', 'Ciprofloxacin', 'Ciprofloxacin ', 'Clopidogrel', 'Clopidogrel ', 'Doxycycline', 'Doxycycline ', 'Duloxetine', 'Duloxetine ', 'Escitalopram', 'Escitalopram ', 'Fluticasone', 'Fluticasone ', 'Furosemide', 'Furosemide ', 'GABAPENTIN', 'GABAPENTIN ', 'Gabapentin', 'Gabapentin ', 'Gabapentine', 'Gabapentine ', 'Hydrochlorothiazide', 'Hydrochlorothiazide ', 'IBUPROFEN', 'IBUPROFEN ', 'INSULIN GLARGINE', 'INSULIN GLARGINE ', 'Ibuprofen', 'Ibuprofen ', 'Ibuprophen', 'Ibuprophen ', 'Insulin  Glargine', 'Insulin  Glargine ', 'Insulin Glargine', 'Insulin Glargine ', 'LISINOPRIL', 'LISINOPRIL ', 'Levothyroxine', 'Levothyroxine ', 'Lisinipril', 'Lisinipril ', 'Lisinopril', 'Lisinopril ', 'Losartan', 'Losartan ', 'METFORMIN', 'METFORMIN ', 'Met formin', 'Met formin ', 'Metformin', 'Metformin ', 'Metformine', 'Metformine ', 'Metoprolol', 'Metoprolol ', 'Montelukast', 'Montelukast ', 'N/A ', 'NA ', 'None ', 'OMEPRAZOLE', 'OMEPRAZOLE ', 'Omeprazol', 'Omeprazol ', 'Omeprazole', 'Omeprazole ', 'Pantoprazole', 'Pantoprazole ', 'Prednisone', 'Prednisone ', 'Rosuvastatin', 'Rosuvastatin ', 'Sertraline', 'Sertraline ', 'Simvastatin', 'Simvastatin ', 'TRAMADOL', 'TRAMADOL ', 'Tramadol', 'Tramadol ', 'Tramadole', 'Tramadole ', 'UNKNOWN', 'UNKNOWN ', 'WARFARIN', 'WARFARIN ', 'Warfarin', 'Warfarin ', 'Warfarine', 'Warfarine ', 'amoxicillin', 'amoxicillin ', 'amoxycillin', 'amoxycillin ', 'atorvastatin', 'atorvastatin ', 'atorvastatine', 'atorvastatine ', 'gabapentin', 'gabapentin ', 'gabapentine', 'gabapentine ', 'ibuprofen', 'ibuprofen ', 'ibuprofin', 'ibuprofin ', 'insulin glargine', 'insulin glargine ', 'lisino pril', 'lisino pril ', 'lisinopril', 'lisinopril ', 'metformin', 'metformin ', 'metformine', 'metformine ', 'n/a ', 'na', 'na ', 'none', 'none ', 'omeprazol', 'omeprazol ', 'omeprazole', 'omeprazole ', 'tramadol', 'tramadol ', 'warfarin', 'warfarin ', 'warfarine', 'warfarine ']

First 20 values:
0           Sertraline
1                  NaN
2           gabapentin
3          Atorvastain
4           Gabapentin
5          gabapentine
6           metformine
7     insulin glargine
8          AMOXICILLIN
9             TRAMADOL
10           warfarine
11          Metoprolol
12           metformin
13           Omeprazol
14         Amoxicillin
15        Rosuvastatin
16                 NaN
17    INSULIN GLARGINE
18         AMOXICILLIN
19         Amoxicillin

Value counts including missing:
Drug_Name
NaN                 148206
amoxicillin          13520
-                    13464
Albuterol            13453
Omeprazole           13448
                     ...
Furosemide               9
  Azithromycin           9
Azithromycin             9
Pantoprazole             7
  Metformine             6
Name: count, Length: 393, dtype: int64

In [16026]:
import pandas as pd

drug_columns = ["Drug_Name", "drug_name"]

drug_mapping = {
    "amoxicilin": "amoxicillin",
    "amoxycillin": "amoxicillin",
    "atorvastain": "atorvastatin",
    "atorvastatine": "atorvastatin",
    "gabapentine": "gabapentin",
    "ibuprophen": "ibuprofen",
    "ibuprofin": "ibuprofen",
    "lisinipril": "lisinopril",
    "lisino pril": "lisinopril",
    "met formin": "metformin",
    "metformine": "metformin",
    "omeprazol": "omeprazole",
    "tramadole": "tramadol",
    "warfarine": "warfarin",
    "insulin  glargine": "insulin glargine",
}

missing_values = ["", "-", "--", "n/a", "na", "none", "unknown"]

for col in drug_columns:
    df_clean[col] = (
        df_clean[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace(missing_values, pd.NA)
        .replace(drug_mapping)
    )

In [16027]:
for col in drug_columns:
    s = df_clean[col].astype("string")
    trimmed = s.str.strip()

    print(f"\n{'=' * 40}")
    print(f"Column: {col}")
    print("=" * 40)

    print("Data type:", df_clean[col].dtype)
    print("Total rows:", len(df_clean))
    print("NaN:", s.isna().sum())
    print("0:", trimmed.eq("0").fillna(False).sum())
    print("-:", trimmed.eq("-").fillna(False).sum())
    print("Empty/whitespace:", trimmed.eq("").fillna(False).sum())

    print("\nDistinct non-missing values:", df_clean[col].nunique())
    print("\nAll distinct non-missing values:")
    print(sorted(df_clean[col].dropna().unique().tolist()))

    print("\nFirst 20 values:")
    print(df_clean[col].head(20).to_string())

    print("\nValue counts including missing:")
    print(df_clean[col].value_counts(dropna=False))

========================================
Column: Drug_Name
========================================
Data type: string
Total rows: 1155000
NaN: 228089
0: 0
-: 0
Empty/whitespace: 0

Distinct non-missing values: 30

All distinct non-missing values:
['albuterol', 'amlodipine', 'amoxicillin', 'atorvastatin', 'azithromycin', 'ciprofloxacin', 'clopidogrel', 'doxycycline', 'duloxetine', 'escitalopram', 'fluticasone', 'furosemide', 'gabapentin', 'hydrochlorothiazide', 'ibuprofen', 'insulin glargine', 'levothyroxine', 'lisinopril', 'losartan', 'metformin', 'metoprolol', 'montelukast', 'omeprazole', 'pantoprazole', 'prednisone', 'rosuvastatin', 'sertraline', 'simvastatin', 'tramadol', 'warfarin']

First 20 values:
0           sertraline
1                 <NA>
2           gabapentin
3         atorvastatin
4           gabapentin
5           gabapentin
6            metformin
7     insulin glargine
8          amoxicillin
9             tramadol
10            warfarin
11          metoprolol
12           metformin
13          omeprazole
14         amoxicillin
15        rosuvastatin
16                <NA>
17    insulin glargine
18         amoxicillin
19         amoxicillin

Value counts including missing:
Drug_Name
<NA>                   228089
amoxicillin             79477
metformin               79111
warfarin                66851
omeprazole              66777
gabapentin              66238
ibuprofen               65919
lisinopril              65856
atorvastatin            65808
insulin glargine        53017
tramadol                52397
albuterol               13520
levothyroxine           13456
ciprofloxacin           13441
pantoprazole            13425
hydrochlorothiazide     13415
clopidogrel             13396
duloxetine              13392
amlodipine              13333
prednisone              13303
fluticasone             13293
rosuvastatin            13263
doxycycline             13246
montelukast             13222
azithromycin            13169
simvastatin             13154
escitalopram            13142
losartan                13141
sertraline              13096
furosemide              13094
metoprolol              12959
Name: count, dtype: Int64

========================================
Column: drug_name
========================================
Data type: string
Total rows: 1155000
NaN: 256872
0: 0
-: 0
Empty/whitespace: 0

Distinct non-missing values: 30

All distinct non-missing values:
['albuterol', 'amlodipine', 'amoxicillin', 'atorvastatin', 'azithromycin', 'ciprofloxacin', 'clopidogrel', 'doxycycline', 'duloxetine', 'escitalopram', 'fluticasone', 'furosemide', 'gabapentin', 'hydrochlorothiazide', 'ibuprofen', 'insulin glargine', 'levothyroxine', 'lisinopril', 'losartan', 'metformin', 'metoprolol', 'montelukast', 'omeprazole', 'pantoprazole', 'prednisone', 'rosuvastatin', 'sertraline', 'simvastatin', 'tramadol', 'warfarin']

First 20 values:
0           sertraline
1                 <NA>
2           gabapentin
3         atorvastatin
4           gabapentin
5           gabapentin
6            metformin
7     insulin glargine
8          amoxicillin
9                 <NA>
10            warfarin
11          metoprolol
12           metformin
13          omeprazole
14         amoxicillin
15        rosuvastatin
16         amoxicillin
17                <NA>
18         amoxicillin
19         amoxicillin

Value counts including missing:
drug_name
<NA>                   256872
amoxicillin             76911
metformin               76496
omeprazole              64796
warfarin                64777
gabapentin              64399
ibuprofen               63924
lisinopril              63901
atorvastatin            63806
insulin glargine        51300
tramadol                50708
albuterol               13114
levothyroxine           13052
duloxetine              13027
pantoprazole            13005
hydrochlorothiazide     12976
ciprofloxacin           12944
amlodipine              12924
fluticasone             12918
clopidogrel             12911
simvastatin             12898
prednisone              12824
doxycycline             12812
rosuvastatin            12804
montelukast             12803
azithromycin            12741
losartan                12740
escitalopram            12719
sertraline              12712
furosemide              12705
metoprolol              12481
Name: count, dtype: Int64

In [16028]:
valid_drug_name = df_clean['drug_name'].notna()

drug_name_missing = df_clean.loc[valid_drug_name, 'Drug_Name'].isna().sum()

matched = (
    df_clean.loc[valid_drug_name, 'drug_name']
    == df_clean.loc[valid_drug_name, 'Drug_Name']
).fillna(False)

print("Valid drug_name values:", valid_drug_name.sum())
print("Matched values:", matched.sum())
print("Different or missing Drug_Name:", (~matched).sum())
print("Missing Drug_Name:", drug_name_missing)

Valid drug_name values: 898128
Matched values: 834052
Different or missing Drug_Name: 64076
Missing Drug_Name: 64076

In [16029]:
different_rows = df_clean.loc[
    df_clean['drug_name'].notna()
    & df_clean['Drug_Name'].isna(),
    ['drug_name', 'Drug_Name']
]

print(different_rows.head(20))

        drug_name Drug_Name
16    amoxicillin      <NA>
30    doxycycline      <NA>
55     lisinopril      <NA>
67     prednisone      <NA>
72    amoxicillin      <NA>
78      albuterol      <NA>
138   clopidogrel      <NA>
147  atorvastatin      <NA>
158   doxycycline      <NA>
170    omeprazole      <NA>
171     ibuprofen      <NA>
174      warfarin      <NA>
207      tramadol      <NA>
226    lisinopril      <NA>
246    metoprolol      <NA>
252    lisinopril      <NA>
290     metformin      <NA>
294    gabapentin      <NA>
311    omeprazole      <NA>
324    prednisone      <NA>

In [16030]:
mask = df_clean['Drug_Name'].isna() & df_clean['drug_name'].notna()

transfer_count = mask.sum()
df_clean.loc[mask, 'Drug_Name'] = df_clean.loc[mask, 'drug_name']

confirmed = (
    df_clean.loc[mask, 'Drug_Name']
    == df_clean.loc[mask, 'drug_name']
).fillna(False)

print("Values transferred:", transfer_count)
print("Transfer confirmed:", confirmed.sum())
print("Transfer failures:", transfer_count - confirmed.sum())
print("Remaining missing Drug_Name in transferred rows:",
      df_clean.loc[mask, 'Drug_Name'].isna().sum())

Values transferred: 64076
Transfer confirmed: 64076
Transfer failures: 0
Remaining missing Drug_Name in transferred rows: 0

In [16031]:
# Standardize Drug_Name in the existing column
df["Drug_Name"] = (
    df["Drug_Name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

# Correct spelling variants
drug_mapping = {
    "amoxicilin": "amoxicillin",
    "amoxycillin": "amoxicillin",
    "atorvastain": "atorvastatin",
    "atorvastatine": "atorvastatin",
    "gabapentine": "gabapentin",
    "ibuprophen": "ibuprofen",
    "ibuprofin": "ibuprofen",
    "lisinipril": "lisinopril",
    "lisino pril": "lisinopril",
    "met formin": "metformin",
    "metformine": "metformin",
    "omeprazol": "omeprazole",
    "tramadole": "tramadol",
    "warfarine": "warfarin"
}

df["Drug_Name"] = df["Drug_Name"].replace(drug_mapping)

# Standardize missing-value labels
invalid_names = ["", "-", "--", "n/a", "na", "none", "unknown"]

df["Drug_Name"] = df["Drug_Name"].replace(invalid_names, pd.NA)

# Validate results
print("Distinct valid drug names:", df["Drug_Name"].nunique())
print("\nStandardized drug names and row counts:")

print(
    df["Drug_Name"]
    .value_counts(dropna=False)
    .to_string()
)

Distinct valid drug names: 30

Standardized drug names and row counts:
Drug_Name
<NA>                   228089
amoxicillin             79477
metformin               79111
warfarin                66851
omeprazole              66777
gabapentin              66238
ibuprofen               65919
lisinopril              65856
atorvastatin            65808
insulin glargine        53017
tramadol                52397
albuterol               13520
levothyroxine           13456
ciprofloxacin           13441
pantoprazole            13425
hydrochlorothiazide     13415
clopidogrel             13396
duloxetine              13392
amlodipine              13333
prednisone              13303
fluticasone             13293
rosuvastatin            13263
doxycycline             13246
montelukast             13222
azithromycin            13169
simvastatin             13154
escitalopram            13142
losartan                13141
sertraline              13096
furosemide              13094
metoprolol              12959

In [16032]:
# Get distinct Drug_Name values
distinct_drugs = df["Drug_Name"].dropna().astype("string").str.strip().unique()

print("Total distinct Drug_Name:", len(distinct_drugs))
print(*sorted(distinct_drugs), sep="\n")

Total distinct Drug_Name: 30
albuterol
amlodipine
amoxicillin
atorvastatin
azithromycin
ciprofloxacin
clopidogrel
doxycycline
duloxetine
escitalopram
fluticasone
furosemide
gabapentin
hydrochlorothiazide
ibuprofen
insulin glargine
levothyroxine
lisinopril
losartan
metformin
metoprolol
montelukast
omeprazole
pantoprazole
prednisone
rosuvastatin
sertraline
simvastatin
tramadol
warfarin

In [16033]:
df_clean.drop(columns=['drug_name'], inplace=True)

print("drug_name column deleted:", 'drug_name' not in df_clean.columns)

drug_name column deleted: True

### 1. `Drug_Name`

* EDA: Identified missing values, inconsistent capitalization, whitespace, and spelling variations.

* Data cleaning: Trimmed whitespace, converted to lowercase, standardized known misspellings, and filled 64,076 missing values from `drug_name`.

### 2. `drug_name`

* EDA: Compared cleaned values against `Drug_Name`; identified 834,052 matches and 64,076 valid values where `Drug_Name` was missing.

* Data cleaning: Standardized whitespace, capitalization, missing-value markers, and known misspellings; transferred 64,076 values to `Drug_Name`, verified the transfer, and deleted the redundant column.

Height_cm

In [16034]:
# Inspect Height_cm column

col = df_clean["Height_cm"]

print("Data type:", col.dtype)
print("Total rows:", len(df_clean))
print("NaN:", col.isna().sum())
print("Zero:", (col == 0).sum())
print("Negative:", (col < 0).sum())
print("<120 cm:", (col < 120).sum())
print(">220 cm:", (col > 220).sum())

print("'-' values:", (col.astype(str).str.strip() == "-").sum())
print("Empty/whitespace:", (col.astype(str).str.strip() == "").sum())
print("Non-numeric values:", col.apply(lambda x: isinstance(x, str)).sum())

print("\nDistinct non-missing values:", col.nunique())
print("\nFirst 20 values:")
print(col.head(20).to_string())

print("\nValue counts including missing (top 20):")
print(col.value_counts(dropna=False).head(20).to_string())

Data type: float64
Total rows: 1155000
NaN: 172218
Zero: 9757
Negative: 0
<120 cm: 19553
>220 cm: 12
'-' values: 0
Empty/whitespace: 0
Non-numeric values: 0

Distinct non-missing values: 9873

First 20 values:
0     170.2
1     174.4
2     179.1
3     167.1
4     180.9
5     170.4
6       NaN
7       NaN
8     167.9
9     168.2
10      NaN
11    168.2
12    181.7
13    164.8
14    180.0
15    176.0
16    152.2
17    154.6
18    164.5
19    181.2

Value counts including missing (top 20):
Height_cm
NaN      172218
0.0        9757
171.7      3317
168.9      3300
172.4      3280
168.5      3278
170.2      3270
172.1      3268
168.3      3264
168.2      3257
170.5      3245
173.7      3244
171.9      3237
171.0      3230
171.4      3230
171.1      3230
169.2      3225
170.6      3225
171.8      3225
169.5      3225

In [16035]:
# Clean Height_cm column

col = "Height_cm"

# Replace heights outside the acceptable range (50–220 cm) with NaN
invalid_height = (df_clean[col] < 50) | (df_clean[col] > 220)
df_clean.loc[invalid_height, col] = float("nan")

# Validate cleaning
print("Values below 50 cm:", (df_clean[col] < 50).sum())
print("Values above 220 cm:", (df_clean[col] > 220).sum())
print("Zero values:", (df_clean[col] == 0).sum())
print("Missing values:", df_clean[col].isna().sum())
print("Minimum valid height:", df_clean[col].min())
print("Maximum valid height:", df_clean[col].max())

Values below 50 cm: 0
Values above 220 cm: 0
Zero values: 0
Missing values: 191769
Minimum valid height: 112.3
Maximum valid height: 220.0

In [16036]:
col = df_clean["Height_cm"]

print("Total rows:", len(df_clean))
print("Valid values:", col.notna().sum())
print("Missing values:", col.isna().sum())
print("Zero values remaining:", (col == 0).sum())
print("Minimum valid height:", col.min())
print("Maximum valid height:", col.max())

Total rows: 1155000
Valid values: 963231
Missing values: 191769
Zero values remaining: 0
Minimum valid height: 112.3
Maximum valid height: 220.0

### Height_cm — EDA

* Total rows: 1,155,000

* Original missing values: 172,218

* Zero values: 9,757

* Values below 120 cm: 19,553

* Values above 220 cm: 12

### Height_cm — Data Cleaning

* Replaced values below 50 cm and above 220 cm with `NaN`.

* Converted zero values to `NaN` and preserved existing missing values.

* Retained heights within 50–220 cm inclusive.

* Final validation: 963,231 valid values; 191,769 missing values; zero values remaining: 0; final height range: 112.3–220.0 cm.

Duration_Days

In [16037]:
# Duration_Days — SAFE INSPECTION (no float conversion)

col = df_clean["Duration_Days"]

print("Data type:", col.dtype)

print("\nRaw values (first 50):")
print(col.head(50))

print("\nDistinct value counts:")
print(col.value_counts(dropna=False))

# Non-numeric detection using regex extract
extracted = col.astype(str).str.extract(r'(\d+\.?\d*)')
non_numeric_mask = extracted[0].isna()

print("\nNon-numeric values:")
print(col[non_numeric_mask].head(50))

# High values (>365) — numeric extraction only
numeric_extracted = pd.to_numeric(extracted[0], errors="coerce")
high_values = col[numeric_extracted > 365]

print("\nHigh values (>365):")
print(high_values.head(50))

Data type: str

Raw values (first 50):
0      21
1     120
2     365
3     120
4     365
5       7
6     365
7      30
8     180
9     NaN
10    365
11     21
12      7
13    NaN
14    120
15    NaN
16    180
17     30
18     14
19     30
20    365
21     90
22    NaN
23      7
24     30
25    NaN
26    NaN
27    NaN
28     14
29    365
30    NaN
31     14
32    NaN
33    NaN
34     90
35    120
36     14
37     21
38     30
39    NaN
40    NaN
41    365
42    180
43    180
44    365
45     60
46     21
47     90
48     30
49     30
Name: Duration_Days, dtype: str

Distinct value counts:
Duration_Days
NaN         162672
30          109390
7           109269
365         109226
21          109104
90          109027
180         108964
14          108902
120         108743
60          108547
chronic       1983
-1            1927
9999          1844
0             1828
lifetime      1805
ongoing       1769
Name: count, dtype: int64

Non-numeric values:
9          NaN
13         NaN
15         NaN
22         NaN
25         NaN
26         NaN
27         NaN
30         NaN
32         NaN
33         NaN
39         NaN
40         NaN
51         NaN
56         NaN
67         NaN
70         NaN
76         NaN
86         NaN
100        NaN
103        NaN
104        NaN
114        NaN
143        NaN
147        NaN
148        NaN
158        NaN
161        NaN
163        NaN
176        NaN
182        NaN
185        NaN
186        NaN
188        NaN
190        NaN
196        NaN
211        NaN
215        NaN
222        NaN
227        NaN
230        NaN
231        NaN
233        NaN
258        NaN
264        NaN
271    chronic
273        NaN
274        NaN
287        NaN
293        NaN
297        NaN
Name: Duration_Days, dtype: str

High values (>365):
313      9999
832      9999
1104     9999
1384     9999
1570     9999
1992     9999
2431     9999
2739     9999
4099     9999
5055     9999
5065     9999
6149     9999
8686     9999
9681     9999
10049    9999
12284    9999
13581    9999
15917    9999
16741    9999
16867    9999
17162    9999
17311    9999
17771    9999
19800    9999
20796    9999
23454    9999
23480    9999
24253    9999
24592    9999
24910    9999
26419    9999
27392    9999
30069    9999
30210    9999
31161    9999
32180    9999
32429    9999
33181    9999
33420    9999
33652    9999
34714    9999
34833    9999
35248    9999
36112    9999
37516    9999
39249    9999
39434    9999
41272    9999
41712    9999
42239    9999
Name: Duration_Days, dtype: str

In [16038]:
# Duration_Days — CLEANING

df_clean["Duration_Days"] = df_clean["Duration_Days"].replace(
    ["0", "-1", "9999"], float("nan")
)

print("Updated value counts:")
print(df_clean["Duration_Days"].value_counts(dropna=False))

Updated value counts:
Duration_Days
NaN         168271
30          109390
7           109269
365         109226
21          109104
90          109027
180         108964
14          108902
120         108743
60          108547
chronic       1983
lifetime      1805
ongoing       1769
Name: count, dtype: int64

### Duration_Days — EDA and Data Cleaning

**EDA findings**
- Data type: `str`
- Missing values: 162,672
- Special text values: `chronic` (1,983), `lifetime` (1,805), `ongoing` (1,769)
- Invalid numeric values identified: `0` (1,828), `-1` (1,927), `9999` (1,844)

**Cleaning performed**
- Replaced `0`, `-1`, and `9999` with `NaN`.
- Retained existing missing values and the text categories unchanged.
- Preserved all other values as strings.

**Validation**
- Final missing values: 168,271
- Newly converted to `NaN`: 5,599
- Total rows: 1,155,000

Diagnosis

In [16039]:
# Diagnosis — SAFE INSPECTION (no type conversion)

col = df_clean["Diagnosis"]

print("Data type:", col.dtype)

print("\nRaw values (first 50):")
print(col.head(50))

print("\nDistinct value counts:")
print(col.value_counts(dropna=False))

print("\nNon-numeric values are not applicable to this text column.")

Data type: str

Raw values (first 50):
0                        htn
1               Osteoporosis
2             Hypothyroidism
3                    Unknown
4                        NaN
5                          -
6               hypertension
7                     Asthma
8       Rheumatoid Arthritis
9                       afib
10                 Pneumonia
11                 Pneumonia
12                       NaN
13                   Unknown
14                       DVT
15                       dm2
16                      GERD
17                         -
18                    Asthma
19                 Pneumonia
20                      T2DM
21                      COPD
22                       HTN
23                      AFIB
24                Depression
25                      T2DM
26                      afib
27    Chronic Kidney Disease
28                      COPD
29                       CHF
30                       HTN
31                       CHF
32                       NaN
33                       CHF
34              Hypertension
35                         -
36                      GERD
37                       NaN
38                       NaN
39                  Migraine
40                      COPD
41              Hypertension
42                      AFIB
43                       CKD
44                         -
45                       DM2
46    Chronic Kidney Disease
47       Atrial Fibrillation
48                    Asthma
49                       htn
Name: Diagnosis, dtype: str

Distinct value counts:
Diagnosis
NaN                     160802
T2DM                     28684
Rheumatoid Arthritis     28623
Anxiety                  28571
Type 2 Diabetes          28508
                         ...
  UTI                       26
COPD                        25
  -                         24
  Epilepsy                  23
 Unknown                    19
Name: count, Length: 180, dtype: int64

Non-numeric values are not applicable to this text column.

In [16040]:
# Diagnosis — CORRECTED DATA CLEANING

# Backup original column (if not already backed up)
if "Diagnosis_original" not in df_clean.columns:
    df_clean["Diagnosis_original"] = df_clean["Diagnosis"]

# Remove leading/trailing whitespace and standardize case
df_clean["Diagnosis"] = df_clean["Diagnosis"].str.strip().str.lower()

# Replace placeholders with NaN
df_clean["Diagnosis"] = df_clean["Diagnosis"].replace(
    ["-", "0", "", "unknown", "n/a"], float("nan")
)

# Standardize equivalent diagnoses
diagnosis_mapping = {
    "htn": "Hypertension",
    "hypertension": "Hypertension",
    "afib": "Atrial Fibrillation",
    "atrial fibrillation": "Atrial Fibrillation",
    "dm2": "Type 2 Diabetes",
    "t2dm": "Type 2 Diabetes",
    "type 2 diabetes": "Type 2 Diabetes",
    "ckd": "Chronic Kidney Disease",
    "chronic kidney disease": "Chronic Kidney Disease",
    "oa": "Osteoarthritis",
    "osteoarthritis": "Osteoarthritis",
    "gerd": "GERD",
    "copd": "COPD",
    "chf": "Heart Failure",
    "heart failure": "Heart Failure",
    "hld": "Hyperlipidemia",
    "hyperlipidemia": "Hyperlipidemia",
    "dvt": "DVT",
    "uti": "UTI"
}

df_clean["Diagnosis"] = df_clean["Diagnosis"].replace(diagnosis_mapping)

# Validation
print("Missing values:", df_clean["Diagnosis"].isna().sum())
print("\nDistinct values:", df_clean["Diagnosis"].nunique(dropna=False))
print("\nValue counts:")
print(df_clean["Diagnosis"].value_counts(dropna=False))

Missing values: 217955

Distinct values: 21

Value counts:
Diagnosis
NaN                       217955
Type 2 Diabetes           142407
Hypertension              114105
Atrial Fibrillation        85295
Chronic Kidney Disease     56711
Osteoarthritis             56709
Heart Failure              56568
Hyperlipidemia             56439
rheumatoid arthritis       28772
anxiety                    28711
asthma                     28573
GERD                       28506
COPD                       28482
hypothyroidism             28343
DVT                        28341
depression                 28337
migraine                   28335
osteoporosis               28252
pneumonia                  28215
epilepsy                   28021
UTI                        27923
Name: count, dtype: int64

In [16041]:
df_clean = df_clean.drop(columns=["Diagnosis_original"])

### EDA

- Data type: `str`
- Original distinct values: 180
- Original missing values: 160,802
- Inconsistent capitalization, whitespace, abbreviations, and placeholders identified.

### Data Cleaning

- Removed leading/trailing whitespace and standardized capitalization.
- Replaced `-`, `0`, `Unknown`, and `N/A` with `NaN`.
- Standardized equivalent diagnoses, including HTN/Hypertension, AFIB/Atrial Fibrillation, DM2/T2DM/Type 2 Diabetes, CKD/Chronic Kidney Disease, OA/Osteoarthritis, CHF/Heart Failure, and HLD/Hyperlipidemia.
- Final distinct values: 21, including `NaN`.
- Final missing values: 217,955.

Dosage

In [16042]:
# Dosage — SAFE INSPECTION 

col = df_clean["Dosage"]
text = col.astype("string").str.strip()
numeric = pd.to_numeric(text, errors="coerce")

print("Data type:", col.dtype)



print("\nDistinct value counts:")
print(col.value_counts(dropna=False))

print("\nInspection counts:")
print("NaN:", col.isna().sum())
print("0:", numeric.eq(0).sum())
print("-:", text.eq("-").sum())
print("Empty/whitespace:", text.eq("").sum())
print("Valid numeric values:", numeric.notna().sum())

print("\nNon-numeric dosage descriptions:")
non_numeric = text.notna() & text.ne("") & numeric.isna()
print(text[non_numeric].value_counts(dropna=False))

Data type: str

Distinct value counts:
Dosage
NaN              158427
20                89484
500               89459
200               89303
750               89244
25                89161
250               89076
10                88883
5                 88813
1000              88787
50                88668
100               88623
-1                 1512
100 mg             1499
as needed          1486
250mg daily        1465
unknown            1433
PRN                1416
2x daily 50mg      1405
0                  1383
two tablets        1379
                   1377
1/2 tab            1376
50mg               1341
Name: count, dtype: int64

Inspection counts:
NaN: 158427
0: 1383
-: 0
Empty/whitespace: 1377
Valid numeric values: 982396

Non-numeric dosage descriptions:
Dosage
100 mg           1499
as needed        1486
250mg daily      1465
unknown          1433
PRN              1416
2x daily 50mg    1405
two tablets      1379
1/2 tab          1376
50mg             1341
Name: count, dtype: Int64

In [16043]:
# Dosage — convert clear mg formats and standardize invalid values

# Allow numeric values to be assigned while text remains
df_clean["Dosage"] = df_clean["Dosage"].astype("object")

dosage = df_clean["Dosage"].astype("string").str.strip().str.lower()

# Convert clear text formats (assumed mg/day)
dosage_conversions = {
    "100 mg": 100,
    "50mg": 50,
    "250mg daily": 250,
    "2x daily 50mg": 100
}

for text_value, numeric_value in dosage_conversions.items():
    df_clean.loc[dosage.eq(text_value), "Dosage"] = numeric_value

# Convert invalid or non-quantifiable entries to NaN
dosage = df_clean["Dosage"].astype("string").str.strip().str.lower()
invalid_values = ["-1", "0", "", "as needed", "prn", "unknown"]

df_clean.loc[dosage.isin(invalid_values), "Dosage"] = float("nan")

In [16044]:
reference_strength = {
    "amoxicillin": 500,
    "atorvastatin": 20,
    "albuterol": 2,
    "amlodipine": 5,
    "azithromycin": 250,
    "ciprofloxacin": 500,
    "clopidogrel": 75,
    "doxycycline": 100,
    "duloxetine": 30,
    "escitalopram": 10,
    "fluticasone": None,
    "furosemide": 40,
    "gabapentin": 300,
    "hydrochlorothiazide": 25,
    "ibuprofen": 200,
    "insulin glargine": None,
    "levothyroxine": 0.05,
    "lisinopril": 10,
    "losartan": 50,
    "metformin": 500,
    "metoprolol": 50,
    "montelukast": 10,
    "omeprazole": 20,
    "pantoprazole": 40,
    "prednisone": 10,
    "rosuvastatin": 10,
    "sertraline": 50,
    "simvastatin": 20,
    "tramadol": 50,
    "warfarin": 5
}

In [16045]:
print("tablet_patterns:", "tablet_patterns" in globals())
print("dosage_text:", "dosage_text" in globals())
print("reference_strength:", "reference_strength" in globals())

tablet_patterns: True
dosage_text: True
reference_strength: True

In [16046]:
# Dosage — convert tablet-count descriptions to assumed mg/day

dosage = df_clean["Dosage"].astype("string").str.strip().str.lower()
drug = df_clean["Drug_Name"].astype("string").str.strip().str.lower()

strength = drug.map(reference_strength)

two_tabs = dosage.eq("two tablets")
half_tab = dosage.eq("1/2 tab")

convert_mask = strength.notna() & (two_tabs | half_tab)

df_clean.loc[convert_mask, "Dosage"] = (
    strength.loc[convert_mask]
    * two_tabs.loc[convert_mask].astype(float).mul(2).add(
        half_tab.loc[convert_mask].astype(float).mul(0.5)
    )
)

print("Converted two tablets:", (convert_mask & two_tabs).sum())
print("Converted 1/2 tab:", (convert_mask & half_tab).sum())
print(
    "Tablet descriptions remaining:",
    df_clean["Dosage"].astype("string").str.strip().str.lower()
    .isin(["two tablets", "1/2 tab"]).sum()
)

Converted two tablets: 1070
Converted 1/2 tab: 1106
Tablet descriptions remaining: 579

In [16047]:
dosage = df_clean["Dosage"].astype("string").str.strip().str.lower()

remaining = dosage.isin(["two tablets", "1/2 tab"])

print(df_clean.loc[remaining, "Drug_Name"].value_counts(dropna=False))

Drug_Name
<NA>                406
insulin glargine    145
fluticasone          28
Name: count, dtype: Int64

In [16048]:
drugs = ["insulin glargine", "fluticasone"]

for drug_name in drugs:
    print(f"\n{drug_name}:")
    mask = df_clean["Drug_Name"].astype("string").str.strip().str.lower().eq(drug_name)
    print(df_clean.loc[mask, "Dosage"].value_counts(dropna=False))

insulin glargine:
Dosage
NaN            8108
20             4503
1000           4438
250            4400
10             4396
500            4379
50             4359
750            4353
5              4339
200            4329
100            4312
25             4296
100             136
1/2 tab          81
250              67
two tablets      64
50               53
Name: count, dtype: int64

fluticasone:
Dosage
NaN            2008
750            1129
20             1129
25             1123
5              1116
500            1113
200            1109
50             1101
100            1079
1000           1078
250            1074
10             1064
100              31
50               25
1/2 tab          15
two tablets      13
250              13
Name: count, dtype: int64

In [16049]:
# Set unconvertible tablet descriptions to NaN for these two drugs

mask = (
    df_clean["Drug_Name"].astype("string").str.strip().str.lower()
    .isin(["insulin glargine", "fluticasone"])
    & df_clean["Dosage"].astype("string").str.strip().str.lower()
      .isin(["two tablets", "1/2 tab"])
)

df_clean.loc[mask, "Dosage"] = float("nan")

print("Converted to NaN:", mask.sum())

Converted to NaN: 173

In [16050]:
# Dosage — verification only (no changes)

dosage = df_clean["Dosage"].astype("string").str.strip()

print("Data type:", df_clean["Dosage"].dtype)
print("NaN:", df_clean["Dosage"].isna().sum())
print("Empty/whitespace:", dosage.eq("").sum())
print("Remaining non-numeric values:",
      (dosage.notna() & dosage.ne("") &
       ~dosage.str.fullmatch(r"[+-]?\d+(\.\d+)?", na=False)).sum())

Data type: object
NaN: 167207
Empty/whitespace: 0
Remaining non-numeric values: 406

In [16051]:
dosage = df_clean["Dosage"].astype("string").str.strip()

non_numeric = (
    dosage.notna()
    & dosage.ne("")
    & ~dosage.str.fullmatch(r"[+-]?\d+(\.\d+)?", na=False)
)

print(df_clean.loc[non_numeric, "Dosage"].value_counts(dropna=False))

Dosage
two tablets    232
1/2 tab        174
Name: count, dtype: int64

In [16052]:
print(
    df_clean.loc[non_numeric, ["Drug_Name", "Dosage"]]
    .value_counts(dropna=False)
    .to_string()
)

Drug_Name  Dosage
<NA>       two tablets    232
           1/2 tab        174

In [16053]:
# Convert remaining non-numeric Dosage values to NaN
df_clean.loc[non_numeric, "Dosage"] = float("nan")

# Verify
dosage = df_clean["Dosage"].astype("string").str.strip()
remaining_non_numeric = (
    dosage.notna()
    & dosage.ne("")
    & ~dosage.str.fullmatch(r"[+-]?\d+(\.\d+)?", na=False)
)

print("Remaining non-numeric values:", remaining_non_numeric.sum())
print("NaN:", df_clean["Dosage"].isna().sum())

Remaining non-numeric values: 0
NaN: 167613

In [16054]:
df_clean["Dosage"] = df_clean["Dosage"].astype(float)

print("Final data type:", df_clean["Dosage"].dtype)

Final data type: float64

### Data-cleaning note: `Assumed_Reference_Strength_mg`

The following reference strengths are provisional modeling assumptions, not verified strengths for individual patient records.

Standardized drug name	Assumed reference strength (mg/tablet or capsule)
amoxicillin	500
atorvastatin	20
albuterol	N/A — formulation-specific
amlodipine	5
azithromycin	250
ciprofloxacin	500
clopidogrel	75
doxycycline	100
duloxetine	30
escitalopram	10
fluticasone	N/A — formulation-specific
furosemide	40
gabapentin	300
hydrochlorothiazide	25
ibuprofen	200
insulin glargine	N/A — injection, measured in units
levothyroxine	0.1 (100 mcg)
lisinopril	10
losartan	50
metformin	500
metoprolol	50
montelukast	10
omeprazole	20
pantoprazole	40
prednisone	5
rosuvastatin	10
sertraline	50
simvastatin	20
tramadol	50
warfarin	5

Methodology note: These values represent selected reference strengths for data standardization and modeling. Actual patient-level product strengths were not verified. Strengths can vary by product, formulation, and market. `N/A` indicates that a single tablet-based reference strength is not appropriate. Levothyroxine is expressed in mg after converting 100 mcg to 0.1 mg. Any conversion of tablet counts to estimated mg must be identified as assumption-based, not a confirmed prescribed dose.

Dosage column cleaning is partially complete. Tablet-count entries with recognized drug names and defined reference strengths have been converted to estimated mg. Before marking the column fully cleaned, validate the remaining text values, missing values, and rows with unknown drug names or reference strengths.

### EDA
- Inspected numeric dosage values, missing values, invalid values, and text-based dosage descriptions.
- Identified entries such as `100 mg`, `50mg`, `250mg daily`, `2x daily 50mg`, `two tablets`, `1/2 tab`, `as needed`, `PRN`, and `unknown`.
- Checked tablet-count descriptions against drug-specific assumed reference strengths.

### Data Cleaning
- Preserved existing numeric dosage values, using mg/day as the working assumption.
- Converted recognized text-based dosage formats to numeric values.
- Converted zero, negative values, `as needed`, `PRN`, `unknown`, and blank entries to `NaN`.
- Converted `two tablets` and `1/2 tab` to estimated mg where a drug-specific reference strength was available.
- Set remaining unconvertible tablet descriptions to `NaN` when the drug name or reference strength was unavailable.
- Updated the existing `Dosage` column; no additional output column was created.
- Converted `Dosage` to `float`.

**Final Validation**
- Remaining non-numeric values: 0
- Missing values (`NaN`): 167,613
- Final data type: `float`

**Limitation:** Reference strengths and mg/day interpretations are documented working assumptions based on the available practice dataset, not verified patient-specific doses.

**Status:** Cleaning and validation complete for the defined workflow.

Concurrent_Drugs

In [16055]:
# Concurrent_Drugs — EDA

col = df["Concurrent_Drugs"]

print("Total rows:", len(col))
print("Missing values:", col.isna().sum())
print("Non-missing values:", col.notna().sum())
print("Unique values:", col.nunique())

print("\nMost frequent values:")
print(col.value_counts(dropna=False).head(20))

print("\nSample entries:")
print(col.dropna().head(20).to_string(index=False))

Total rows: 1155000
Missing values: 149040
Non-missing values: 1005960
Unique values: 19

Most frequent values:
Concurrent_Drugs
 2.0     223422
 3.0     222972
 4.0     167648
 1.0     149340
 NaN     149040
 5.0      99578
 6.0      50352
 0.0      49517
 7.0      21215
 8.0       8058
 9.0       2709
 50.0      2589
-1.0       2533
-5.0       2474
 99.0      2460
 10.0       822
 11.0       206
 12.0        52
 13.0         7
 14.0         6
Name: count, dtype: int64

Sample entries:
3.0
5.0
4.0
7.0
3.0
2.0
1.0
4.0
5.0
5.0
4.0
1.0
5.0
3.0
2.0
5.0
3.0
4.0
2.0
4.0

In [16056]:
# Inspect rows containing suspected outliers
outliers = [-1, -5, 50, 99]

cols = [
    "Patient_ID",
    "Concurrent_Drugs",
    "Drug_Name",
    "Dosage"
]

print(
    df.loc[
        df["Concurrent_Drugs"].isin(outliers),
        cols
    ].head(30).to_string(index=False)
)

 Patient_ID  Concurrent_Drugs        Drug_Name Dosage
     361685              -5.0        albuterol     20
    1030410              50.0         warfarin   1000
     166408              -1.0       lisinopril     10
     452146              50.0         tramadol    750
     474347              -1.0         warfarin   1000
      11359              50.0      simvastatin     20
     943088              50.0        metformin   1000
     820967              50.0         tramadol     10
     997091              -1.0             <NA>     20
      38993              -1.0       duloxetine     50
     764164              -1.0     escitalopram    100
     190690              99.0       amlodipine    250
     915721              99.0       gabapentin     10
     513966              -5.0        metformin     20
     355431              99.0       metoprolol    500
     656160              -5.0 insulin glargine     10
     722413              50.0             <NA>     20
     740988              99.0       lisinopril    750
     536527              -1.0       lisinopril     10
     330647              50.0     atorvastatin   1000
     446538              -1.0       omeprazole     50
     931042              -1.0     pantoprazole    NaN
     589217              -1.0             <NA>     10
     991143              99.0             <NA>    500
     891461              99.0        ibuprofen    NaN
     749013              99.0       omeprazole      5
     563111              50.0     escitalopram    100
     816431              -1.0         tramadol     50
     781339              50.0        metformin     50
     215732              -5.0         losartan    750

In [16057]:
outliers = [-5, -1, 50, 99]

print(
    df.loc[
        df["Concurrent_Drugs"].isin(outliers)
    ].groupby("Concurrent_Drugs").agg(
        Rows=("Patient_ID", "size"),
        Unique_Patients=("Patient_ID", "nunique"),
        Missing_Drug_Name=("Drug_Name", lambda x: x.isna().sum())
    )
)

                  Rows  Unique_Patients  Missing_Drug_Name
Concurrent_Drugs
-5.0              2474             2222                466
-1.0              2533             2308                516
 50.0             2589             2355                515
 99.0             2460             2261                471

In [16058]:
# Replace negative counts only
df.loc[df["Concurrent_Drugs"] < 0, "Concurrent_Drugs"] = np.nan

# Validate
print("Missing values:", df["Concurrent_Drugs"].isna().sum())
print("Negative values:", (df["Concurrent_Drugs"] < 0).sum())

Missing values: 154047
Negative values: 0

In [16059]:
col = df_clean["Concurrent_Drugs"]
numeric = pd.to_numeric(col, errors="coerce")

print("Data type:", col.dtype)
print("\nValue counts:")
print(col.value_counts(dropna=False).sort_index())

print("\nNegative values:", numeric.lt(0).sum())
print("50:", numeric.eq(50).sum())
print("99:", numeric.eq(99).sum())
print("NaN:", col.isna().sum())

Data type: float64

Value counts:
Concurrent_Drugs
-5.0       2474
-1.0       2533
 0.0      49517
 1.0     149340
 2.0     223422
 3.0     222972
 4.0     167648
 5.0      99578
 6.0      50352
 7.0      21215
 8.0       8058
 9.0       2709
 10.0       822
 11.0       206
 12.0        52
 13.0         7
 14.0         6
 50.0      2589
 99.0      2460
 NaN     149040
Name: count, dtype: int64

Negative values: 5007
50: 2589
99: 2460
NaN: 149040

In [16060]:
# Concurrent_Drugs — apply the agreed cleaning rule

df_clean.loc[df_clean["Concurrent_Drugs"] < 0, "Concurrent_Drugs"] = float("nan")

# Verify
print("Negative values remaining:", df_clean["Concurrent_Drugs"].lt(0).sum())
print("50:", df_clean["Concurrent_Drugs"].eq(50).sum())
print("99:", df_clean["Concurrent_Drugs"].eq(99).sum())
print("NaN:", df_clean["Concurrent_Drugs"].isna().sum())

Negative values remaining: 0
50: 2589
99: 2460
NaN: 154047

In [16061]:
# Concurrent_Drugs — final verification (no changes)

col = df_clean["Concurrent_Drugs"]

print("Data type:", col.dtype)
print("Total rows:", len(col))
print("Missing values:", col.isna().sum())
print("Negative values:", col.lt(0).sum())
print("Zero values:", col.eq(0).sum())
print("Value 50 (flagged):", col.eq(50).sum())
print("Value 99 (flagged):", col.eq(99).sum())
print("Valid non-negative values:", col[col.ge(0)].count())
print("Minimum non-negative value:", col[col.ge(0)].min())
print("Maximum non-negative value:", col[col.ge(0)].max())

Data type: float64
Total rows: 1155000
Missing values: 154047
Negative values: 0
Zero values: 49517
Value 50 (flagged): 2589
Value 99 (flagged): 2460
Valid non-negative values: 1000953
Minimum non-negative value: 0.0
Maximum non-negative value: 99.0

Recheck
**EDA — Concurrent_Drugs**
- Total rows: 1,155,000
- Initially missing: 149,040 (12.90%)
- Most frequent counts: 2 (223,422), 3 (222,972), and 4 (167,648).
- Identified negative values (−1: 2,533; −5: 2,474) and unusually high values (50: 2,589; 99: 2,460).

**Data Cleaning**
- Negative counts identified as invalid and replaced with missing values.
- Values 50 and 99 flagged for verification against source documentation.
- Existing patient records retained; no rows deleted.

### Concurrent_Drugs — Final Verification

EDA

- Total rows: 1,155,000
- Initially missing: 149,040 (12.90%)
- Most frequent values: 2 (223,422), 3 (222,972), 4 (167,648)
- Identified invalid negative values: −1 (2,533), −5 (2,474)
- Flagged unusually high values: 50 (2,589), 99 (2,460)

Data Cleaning

- Replaced all negative values with `NaN`.
- Retained values 50 and 99 for source verification; no additional changes made.
- Retained all patient records; no rows deleted.

Final Validation

- Data type: `float64`
- Missing values: 154,047 (13.34%)
- Negative values remaining: 0
- Zero values: 49,517
- Value 50: 2,589
- Value 99: 2,460
- Valid non-negative values: 1,000,953
- Minimum: 0
- Maximum: 99

Status: Cleaning and validation complete for the agreed rules. Values 50 and 99 remain flagged, not confirmed errors.

Total_Cholesterol

In [16062]:
col = df["Total_Cholesterol"]
text = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("Total rows:", len(col))
print("NaN:", col.isna().sum())
print("0:", text.eq("0").sum())
print("-:", text.eq("-").sum())
print("--:", text.eq("--").sum())
print("Negative values:", col.lt(0).sum())
print("Unique values:", col.nunique())
print("Empty/whitespace:", text.eq("").sum())
print("Other non-missing rows:", (
    col.notna() & ~text.isin(["0", "-", "--", ""])
).sum())
print("Total reconciliation:", (
    col.isna().sum()
    + text.isin(["0", "-", "--", ""]).sum()
    + (col.notna() & ~text.isin(["0", "-", "--", ""])).sum()
))
print(df["Total_Cholesterol"].head(50).to_string(index=False))

Data type: float64
Total rows: 1155000
NaN: 143994
0: 0
-: 0
--: 0
Negative values: 2573
Unique values: 396
Empty/whitespace: 0
Other non-missing rows: 1011006
Total reconciliation: 1155000
164.0
251.0
244.0
  NaN
 99.0
121.0
300.0
237.0
232.0
194.0
  NaN
231.0
148.0
255.0
218.0
169.0
176.0
  NaN
165.0
176.0
246.0
238.0
137.0
279.0
232.0
290.0
131.0
232.0
204.0
215.0
150.0
165.0
  NaN
195.0
133.0
168.0
194.0
224.0
  NaN
177.0
164.0
183.0
238.0
193.0
  NaN
230.0
214.0
212.0
208.0
207.0

In [16063]:
# Total_Cholesterol — CLEANING

# Convert negative values to NaN
df_clean.loc[df_clean["Total_Cholesterol"] < 0, "Total_Cholesterol"] = np.nan

# Calculate median using only values between 70 and 400
good_tc_mask = (
    df_clean["Total_Cholesterol"].notna() &
    (df_clean["Total_Cholesterol"] >= 70) &
    (df_clean["Total_Cholesterol"] <= 400)
)

median_tc = df_clean.loc[good_tc_mask, "Total_Cholesterol"].median()
print("Median Total Cholesterol (70–400):", median_tc)

# Replace missing values and values outside 70–400 with the median
invalid_tc = (
    df_clean["Total_Cholesterol"].isna() |
    (df_clean["Total_Cholesterol"] < 70) |
    (df_clean["Total_Cholesterol"] > 400)
)

df_clean.loc[invalid_tc, "Total_Cholesterol"] = median_tc

# Validation
print("Remaining NaN:", df_clean["Total_Cholesterol"].isna().sum())
print("Remaining values <70:", (df_clean["Total_Cholesterol"] < 70).sum())
print("Remaining values >400:", (df_clean["Total_Cholesterol"] > 400).sum())

Median Total Cholesterol (70–400): 200.0
Remaining NaN: 0
Remaining values <70: 0
Remaining values >400: 0

### EDA and Data-Cleaning Notes — `Total_Cholesterol`

**EDA**
- Data type: `float64`
- Total rows: 1,155,000
- Missing values: 143,994
- Negative values: 2,573
- Zero values: 0
- Unique values: 396
- Values were inspected; several observed values were close to 200.

**Data Cleaning**
- Values below 70 and above 400 were treated as invalid for this cleaning step.
- Median calculated using non-missing values within the range 70–400: **200.0**.
- Missing values, values below 70, and values above 400 were replaced with the median of 200.0.
- Final validation:
  - Remaining missing values: 0
  - Remaining values below 70: 0
  - Remaining values above 400: 0

**Modelling note:** Median imputation preserves the row count but assigns the same value to records with missing or out-of-range cholesterol. Its effect on model performance should be evaluated during modelling.

Creatinine

In [16064]:
# Creatinine — STANDARD INSPECTION

col = df_clean["Creatinine"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("Total rows:", len(col))
print("NaN count:", col.isna().sum())
print("0 count:", (col == 0).sum())
print("- count:", (values == "-").sum())
print("-- count:", (values == "--").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = (
    col.isna() |
    values.isin(["-", "--", ""])
)

print("Valid-value count:", (~placeholders).sum())
print(
    "Total reconciliation:",
    col.isna().sum()
    + values.isin(["-", "--", ""]).sum()
    + (~placeholders & col.notna()).sum()
)

# Additional Creatinine-specific inspection

print("\nRaw values (first 50):")
print(col.head(50).to_string(index=False))

print("\nNegative values:", (col < 0).sum())

print("\nLow values (<0.3):")
print(col.loc[col < 0.3].head(50).to_string(index=False))

print("\nHigh values (>10):")
print(col.loc[col > 10].head(50).to_string(index=False))

Data type: float64
Total rows: 1155000
NaN count: 143619
0 count: 2525
- count: 0
-- count: 0
Empty/whitespace count: 0
Valid-value count: 1011381
Total reconciliation: 1155000

Raw values (first 50):
 NaN
0.95
0.52
1.63
1.18
1.41
0.76
 NaN
1.34
0.54
0.75
1.80
 NaN
1.02
0.76
0.41
1.17
1.31
0.96
1.09
1.44
1.63
1.11
 NaN
0.68
1.40
1.12
2.06
1.58
2.05
 NaN
1.87
1.55
1.06
1.00
2.05
0.96
1.41
1.29
1.42
 NaN
 NaN
 NaN
0.76
1.62
1.02
0.62
0.55
1.09
1.04

Negative values: 2487

Low values (<0.3):
 0.00
 0.22
 0.00
 0.00
-1.00
-1.00
 0.27
 0.27
 0.00
-1.00
 0.00
 0.00
-1.00
 0.00
-1.00
 0.00
 0.00
 0.00
-1.00
-1.00
-1.00
-1.00
 0.28
-1.00
-1.00
 0.00
-1.00
-1.00
-1.00
 0.00
 0.00
 0.29
-1.00
-1.00
-1.00
 0.00
 0.00
 0.00
 0.00
 0.00
 0.29
-1.00
 0.00
-1.00
-1.00
-1.00
 0.00
-1.00
-1.00
 0.00

High values (>10):
50.0
99.0
99.0
50.0
50.0
50.0
50.0
50.0
99.0
99.0
99.0
50.0
50.0
50.0
99.0
50.0
99.0
50.0
99.0
99.0
99.0
50.0
99.0
99.0
99.0
50.0
99.0
50.0
99.0
99.0
50.0
99.0
50.0
50.0
50.0
50.0
50.0
50.0
99.0
50.0
50.0
99.0
99.0
50.0
99.0
99.0
50.0
50.0
50.0
99.0

In [16065]:
# Creatinine — Additional inspection of suspicious values

print("Values <0.3:")
print(df_clean.loc[df_clean["Creatinine"] < 0.3, "Creatinine"].value_counts().sort_index())

print("\nValues >10:")
print(df_clean.loc[df_clean["Creatinine"] > 10, "Creatinine"].value_counts().sort_index())

Values <0.3:
Creatinine
-1.00    2487
 0.00    2525
 0.14       1
 0.17       1
 0.18       1
 0.19       3
 0.20       6
 0.21      10
 0.22      15
 0.23      23
 0.24      34
 0.25      37
 0.26      51
 0.27      78
 0.28      94
 0.29     117
Name: count, dtype: int64

Values >10:
Creatinine
50.0    2622
99.0    2468
Name: count, dtype: int64

In [16066]:
# CREATININE — CLEANING

# Identify invalid values
invalid_cr = (
    df_clean["Creatinine"].isna() |
    (df_clean["Creatinine"] == -1) |
    (df_clean["Creatinine"] == 0) |
    (df_clean["Creatinine"].isin([50, 99]))
)

# Calculate median using values from 0.3 to 10, inclusive
good_cr_mask = (
    df_clean["Creatinine"].notna() &
    (df_clean["Creatinine"] >= 0.3) &
    (df_clean["Creatinine"] <= 10)
)

median_cr = df_clean.loc[good_cr_mask, "Creatinine"].median()
print("Median Creatinine (0.3–10):", median_cr)

# Replace invalid values with median
df_clean.loc[invalid_cr, "Creatinine"] = median_cr

# Validation
print("Remaining NaN:", df_clean["Creatinine"].isna().sum())
print("Remaining -1:", (df_clean["Creatinine"] == -1).sum())
print("Remaining zeros:", (df_clean["Creatinine"] == 0).sum())
print("Remaining 50:", (df_clean["Creatinine"] == 50).sum())
print("Remaining 99:", (df_clean["Creatinine"] == 99).sum())
print("Remaining values <0.3:", (df_clean["Creatinine"] < 0.3).sum())
print("Remaining values >10:", (df_clean["Creatinine"] > 10).sum())

Median Creatinine (0.3–10): 1.11
Remaining NaN: 0
Remaining -1: 0
Remaining zeros: 0
Remaining 50: 0
Remaining 99: 0
Remaining values <0.3: 471
Remaining values >10: 0

### EDA and Data-Cleaning Notes — `Creatinine`

**EDA**
- Data type: `float64`
- Total rows: 1,155,000
- Missing values: 143,619
- Zero values: 2,525
- Negative values: 2,487, all recorded as `-1`
- Values below 0.3: 3,430, including zeros, negatives, and low positive values
- Values above 10: 5,090, consisting of `50` (2,622 rows) and `99` (2,468 rows)
- Empty/whitespace and text placeholders (`-`, `--`): 0

**Data Cleaning**
- Existing missing values, `-1`, `0`, `50`, and `99` were treated as invalid.
- Median calculated using values from 0.3 to 10, inclusive: **1.11**.
- Invalid values were replaced with the median of 1.11.
- Positive values between 0.3 and 10 were retained unchanged.
- Positive values below 0.3 were also retained unchanged.

**Final Validation**
- Remaining missing values: 0
- Remaining `-1`, `0`, `50`, and `99`: 0
- Remaining values below 0.3: 471
- Remaining values above 10: 0

**Assumptions and Limitations**
- Measurement units and a data dictionary were unavailable.
- The 0.3–10 range and the treatment of 50 and 99 as invalid values are provisional cleaning assumptions, not clinically validated rules.

TEMPERATURE_F

In [16067]:
# TEMPERATURE_F — STANDARD INSPECTION

col = df_clean["Temperature_F"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("Total rows:", len(col))
print("NaN count:", col.isna().sum())
print("0 count:", (col == 0).sum())
print("- count:", (values == "-").sum())
print("-- count:", (values == "--").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])

print("Valid-value count:", (~placeholders).sum())
print(
    "Total reconciliation:",
    col.isna().sum()
    + values.isin(["-", "--", ""]).sum()
    + (~placeholders & col.notna()).sum()
)

# Additional temperature-specific inspection

print("\nRaw values (first 50):")
print(col.head(50).to_string(index=False))

print("\nNegative values:", (col < 0).sum())

print("\nLow values (<95 F):")
print(col.loc[col < 95].head(50).to_string(index=False))

print("\nHigh values (>105 F):")
print(col.loc[col > 105].head(50).to_string(index=False))

Data type: float64
Total rows: 1155000
NaN count: 134530
0 count: 2614
- count: 0
-- count: 0
Empty/whitespace count: 0
Valid-value count: 1020470
Total reconciliation: 1155000

Raw values (first 50):
 98.6
 98.0
 99.1
100.1
 99.0
100.1
 97.7
 98.0
 98.3
 98.8
 97.5
 97.3
 97.0
 99.0
 99.7
 99.2
 98.7
 98.7
 99.9
 98.3
 97.5
  NaN
 97.9
 99.0
 99.8
 98.9
100.1
100.6
 98.2
 98.5
 98.6
 97.6
 98.9
 98.3
 98.3
 98.5
  NaN
 99.5
 97.8
 98.1
 98.8
 99.2
 97.7
  NaN
 97.8
100.2
 99.4
100.4
 97.9
  NaN

Negative values: 0

Low values (<95 F):
70.0
 0.0
 0.0
70.0
 0.0
70.0
 0.0
 0.0
 0.0
70.0
70.0
 0.0
70.0
 0.0
 0.0
70.0
70.0
 0.0
 0.0
 0.0
 0.0
70.0
70.0
70.0
 0.0
 0.0
 0.0
 0.0
 0.0
70.0
70.0
 0.0
70.0
 0.0
 0.0
 0.0
70.0
70.0
70.0
70.0
 0.0
70.0
70.0
70.0
 0.0
 0.0
 0.0
 0.0
 0.0
70.0

High values (>105 F):
110.0
110.0
110.0
115.0
110.0
110.0
110.0
110.0
115.0
115.0
110.0
115.0
115.0
110.0
110.0
115.0
115.0
115.0
110.0
115.0
110.0
110.0
115.0
115.0
115.0
115.0
115.0
110.0
110.0
115.0
110.0
115.0
110.0
115.0
110.0
115.0
110.0
110.0
115.0
110.0
110.0
115.0
110.0
115.0
110.0
115.0
110.0
115.0
110.0
115.0

In [16068]:
# Temperature_F — Additional inspection of suspicious values

print("Values below 95°F:")
print(
    df_clean.loc[df_clean["Temperature_F"] < 95, "Temperature_F"]
    .value_counts()
    .sort_index()
)

print("\nValues above 105°F:")
print(
    df_clean.loc[df_clean["Temperature_F"] > 105, "Temperature_F"]
    .value_counts()
    .sort_index()
)

Values below 95°F:
Temperature_F
0.0     2614
70.0    2565
94.7       1
94.8       2
Name: count, dtype: int64

Values above 105°F:
Temperature_F
110.0    2500
115.0    2509
Name: count, dtype: int64

In [16069]:
# Inspect rows with Temperature_F = 94.7 or 94.8

print(
    df_clean.loc[
        df_clean["Temperature_F"].isin([94.7, 94.8])
    ].to_string()
)

         Patient_ID  patient_id   Age  Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm   BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol         Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs        Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome Adverse_Event  Readmission_30d  unnamed_0
1009959      543333       526.0  62.0  Female   Unknown       75.1  168.760982        NaN  24.0         164/76        164.0          76.0        68.0           94.7        19.3     9063.0        22.3        19.9        0.92   NaN    7.4              180.0  insulin glargine    20.0            21    IM               3.0              NaN        Unknown          No            NaT                 0             0              0.0   0.287614
1032521      123269       338.0  52.0     NaN    Indian       61.6  129.401557      167.8  21.9            NaN        132.0          82.0        53.0           94.8        13.6    11769.0        18.8        18.8        1.53   NaN    6.4              206.0         metformin   250.0            90    SC               3.0  Type 2 Diabetes             No         Yes     2018-12-09                 1             0              0.0   0.498946
1089698      123269       338.0  52.0     NaN    Indian       61.6  129.401557      167.8  21.9            NaN        132.0          82.0        53.0           94.8        13.6    11769.0        18.8        18.8        1.53   NaN    6.4              206.0         metformin   250.0            90    SC               3.0  Type 2 Diabetes             No         Yes     2018-12-09                 1             0              0.0   0.498946

In [16070]:
# TEMPERATURE_F — CLEANING

# General reference range: 95–105°F
valid_temp = (
    df_clean["Temperature_F"].between(95, 105) |
    df_clean["Temperature_F"].isin([94.7, 94.8])
)

# Convert out-of-range values to NaN; preserve existing NaN
df_clean.loc[
    df_clean["Temperature_F"].notna() & ~valid_temp,
    "Temperature_F"
] = np.nan

# Validation
print("Remaining NaN:", df_clean["Temperature_F"].isna().sum())
print("94.7 retained:", (df_clean["Temperature_F"] == 94.7).sum())
print("94.8 retained:", (df_clean["Temperature_F"] == 94.8).sum())
print("Below 95°F:", (df_clean["Temperature_F"] < 95).sum())
print("Above 105°F:", (df_clean["Temperature_F"] > 105).sum())

Remaining NaN: 144718
94.7 retained: 1
94.8 retained: 2
Below 95°F: 3
Above 105°F: 0

### Temperature_F — EDA and Data Cleaning Notes

- **Data type:** float64
- **Total records:** 1,155,000
- **Originally missing values:** 134,530 (11.65%)
- **Cleaning rule:** Used a general reference range of 95–105°F. Values outside this range were converted to NaN, while 94.7°F (1 record) and 94.8°F (2 records) were retained as exceptions.
- **Final missing values:** 144,718 (12.53%), including originally missing and newly invalidated readings.
- **Imputation:** None; NaN values were retained for later modelling decisions.
- **Validation:** No values remain above 105°F; the three retained readings below 95°F are 94.7°F and 94.8°F.
- **Modelling consideration:** Evaluate missing-value handling during model preparation; fit any imputation strategy on training data only.

Heart_Rate

In [16071]:
# HEART_RATE — STANDARD INSPECTION

col = df_clean["Heart_Rate"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("Total rows:", len(col))
print("NaN count:", col.isna().sum())
print("0 count:", (col == 0).sum())
print("- count:", (values == "-").sum())
print("-- count:", (values == "--").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])

print("Valid-value count:", (~placeholders).sum())

# Range inspection
print("Negative values:", (col < 0).sum())
print("Values below 30 bpm:", (col < 30).sum())
print("Values above 220 bpm:", (col > 220).sum())

print("\nRaw values (first 50):")
print(values.head(50))

Data type: float64
Total rows: 1155000
NaN count: 130529
0 count: 2594
- count: 0
-- count: 0
Empty/whitespace count: 0
Valid-value count: 1024471
Negative values: 2581
Values below 30 bpm: 6472
Values above 220 bpm: 5064

Raw values (first 50):
0      62.0
1      71.0
2     104.0
3      55.0
4      44.0
5      <NA>
6      58.0
7      43.0
8      84.0
9      <NA>
10     84.0
11     65.0
12    114.0
13     85.0
14     <NA>
15     69.0
16     40.0
17     69.0
18     <NA>
19     60.0
20     62.0
21     58.0
22     94.0
23     71.0
24     74.0
25     81.0
26     83.0
27     80.0
28     81.0
29     <NA>
30     87.0
31     58.0
32     <NA>
33     <NA>
34     63.0
35     92.0
36     <NA>
37     82.0
38     67.0
39     90.0
40     56.0
41     70.0
42     73.0
43     75.0
44     65.0
45     94.0
46     60.0
47     53.0
48     51.0
49     <NA>
Name: Heart_Rate, dtype: string

In [16072]:
# HEART_RATE — UNUSUAL VALUE FREQUENCIES (TOP 10)

print("Top 10 values below 30 bpm:")
print(
    df_clean.loc[df_clean["Heart_Rate"] < 30, "Heart_Rate"]
    .value_counts()
    .sort_index()
    .head(10)
)

print("\nTop 10 values above 220 bpm:")
print(
    df_clean.loc[df_clean["Heart_Rate"] > 220, "Heart_Rate"]
    .value_counts()
    .sort_index()
    .head(10)
)

Top 10 values below 30 bpm:
Heart_Rate
-1.0     2581
 0.0     2594
 6.0        2
 8.0        2
 9.0        2
 10.0       1
 11.0       2
 12.0       3
 13.0       5
 14.0       7
Name: count, dtype: int64

Top 10 values above 220 bpm:
Heart_Rate
300.0    2554
500.0    2510
Name: count, dtype: int64

In [16073]:
# HEART_RATE — REVIEW SELECTED RECORDS

selected_hr = df_clean["Heart_Rate"].isin([-1, 0, 300, 500])

print("Selected records:", selected_hr.sum())

print(
    df_clean.loc[
        selected_hr,
        ["Patient_ID", "patient_id", "Age", "Gender", "Heart_Rate",
         "Temperature_F", "blood_pressure", "Systolic_BP",
         "Diastolic_BP", "Diagnosis", "Drug_Name"]
    ].head(20).to_string(index=False)
)

Selected records: 10239
 Patient_ID  patient_id  Age Gender  Heart_Rate  Temperature_F blood_pressure  Systolic_BP  Diastolic_BP           Diagnosis           Drug_Name
     396879         NaN 33.0  Other        -1.0           98.7         138/81        138.0          81.0     Type 2 Diabetes        azithromycin
     467777       538.0 71.0    NaN       500.0           98.3         125/93        125.0          93.0     Type 2 Diabetes          lisinopril
      10012       377.0 70.0    NaN       500.0          100.3         116/45        116.0          45.0            epilepsy         simvastatin
     936143       630.0 61.0   Male       500.0           97.6         103/96        103.0          96.0                 NaN                <NA>
     632665       488.0 45.0    NaN        -1.0           98.2         139/89        139.0          89.0                 NaN                <NA>
     401745         NaN 50.0    NaN        -1.0           98.1         224/84          NaN          84.0      Osteoarthritis            warfarin
     699638       836.0 32.0   Male        -1.0           99.0         122/73        122.0          73.0     Type 2 Diabetes         doxycycline
     676484       932.0 97.0  Other         0.0           99.2         169/60        169.0           NaN                 NaN           metformin
     218008       240.0 50.0   Male         0.0           98.3         108/91        108.0          91.0        Hypertension          omeprazole
     986444        82.0 66.0 Female        -1.0           99.4         141/94        141.0          94.0                GERD            tramadol
     225416       717.0 23.0    NaN       500.0           96.8            NaN        117.0          67.0        osteoporosis          lisinopril
     438066       176.0 24.0 Female       300.0           99.3         165/58        165.0          58.0          depression           ibuprofen
     704513       364.0 79.0 Female        -1.0           98.6        106/114        106.0         114.0 Atrial Fibrillation hydrochlorothiazide
     586350       507.0 30.0    NaN       300.0           98.4         132/64        132.0          64.0      Hyperlipidemia                <NA>
      80687       255.0 43.0    NaN       500.0           98.9         122/80        122.0          80.0      Hyperlipidemia         doxycycline
     676302       279.0 51.0    NaN       500.0           98.9        143/107        143.0         107.0                 NaN    insulin glargine
     678702       900.0 43.0    NaN        -1.0           98.7            NaN        162.0          73.0              asthma         fluticasone
      32337        26.0 51.0 Female       300.0           98.7            NaN        146.0          82.0                 NaN           ibuprofen
     812396       922.0 47.0 Female       300.0           99.1         135/84        135.0          84.0                 NaN            warfarin
     922923       845.0 49.0   Male         0.0           99.7         147/67        147.0          67.0      Osteoarthritis           metformin

In [16074]:
# HEART_RATE — DISTINCT VALUES OUTSIDE SCREENING LIMITS

print("Distinct values below 30 bpm:")
print(
    df_clean.loc[df_clean["Heart_Rate"] < 30, "Heart_Rate"]
    .value_counts()
    .sort_index()
)

print("\nDistinct values above 220 bpm:")
print(
    df_clean.loc[df_clean["Heart_Rate"] > 220, "Heart_Rate"]
    .value_counts()
    .sort_index()
)

Distinct values below 30 bpm:
Heart_Rate
-1.0     2581
 0.0     2594
 6.0        2
 8.0        2
 9.0        2
 10.0       1
 11.0       2
 12.0       3
 13.0       5
 14.0       7
 15.0      13
 16.0       9
 17.0      18
 18.0      18
 19.0      21
 20.0      30
 21.0      47
 22.0      63
 23.0      66
 24.0      90
 25.0      99
 26.0     149
 27.0     181
 28.0     212
 29.0     257
Name: count, dtype: int64

Distinct values above 220 bpm:
Heart_Rate
300.0    2554
500.0    2510
Name: count, dtype: int64

In [16075]:
# HEART_RATE — DATA CLEANING

# Convert values below 30 bpm and identified extreme values to NaN
invalid_hr = (
    (df_clean["Heart_Rate"] < 30) |
    (df_clean["Heart_Rate"].isin([300, 500]))
)

df_clean.loc[invalid_hr, "Heart_Rate"] = np.nan

# Validation
print("Remaining values below 30 bpm:", (df_clean["Heart_Rate"] < 30).sum())
print("Remaining 300:", (df_clean["Heart_Rate"] == 300).sum())
print("Remaining 500:", (df_clean["Heart_Rate"] == 500).sum())
print("Total NaN:", df_clean["Heart_Rate"].isna().sum())

Remaining values below 30 bpm: 0
Remaining 300: 0
Remaining 500: 0
Total NaN: 142065

#EDA
-Data type: float64
- Total records: 1,155,000
- Original missing values: 130,529 (11.30%)
- Zero values: 2,594
- Negative values: 2,581
- Values below 30 bpm: 6,472
- Values above 220 bpm: 5,064, including repeated values of 300 bpm (2,554) and 500 bpm (2,510).

# Data Cleaning
Converted all heart-rate values below 30 bpm and values of 300 and 500 bpm to NaN.

Final missing values: 142,065 (12.30%).

No median imputation performed; NaN values retained for modelling.
Values at or aove 30bpm were otherwise left unchanged.

eGFR

In [16076]:
# eGFR — STANDARD INSPECTION

col = df_clean["eGFR"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("0 count:", (col == 0).sum())
print("- count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])

print("Valid-value count:", (~placeholders).sum())

# Range inspection
print("Negative values:", (col < 0).sum())
print("Values below 5:", (col < 5).sum())
print("Values above 200:", (col > 200).sum())

Data type: float64
NaN count: 127167
0 count: 14
- count: 0
Empty/whitespace count: 0
Valid-value count: 1027833
Negative values: 6570
Values below 5: 7752
Values above 200: 2580

In [16077]:
# eGFR — DISTINCT VALUE FREQUENCIES (TOP 10)

print("Top 10 distinct values below 5:")
print(
    df_clean.loc[df_clean["eGFR"] < 5, "eGFR"]
    .value_counts()
    .sort_index()
    .head(10)
)

print("\nTop 10 distinct values above 200:")
print(
    df_clean.loc[df_clean["eGFR"] > 200, "eGFR"]
    .value_counts()
    .sort_index()
    .head(10)
)

Top 10 distinct values below 5:
eGFR
-39.5    1
-36.7    1
-36.3    1
-34.8    4
-34.1    2
-32.8    1
-32.4    1
-31.3    1
-31.0    2
-30.6    1
Name: count, dtype: int64

Top 10 distinct values above 200:
eGFR
201.9       1
999.0    2579
Name: count, dtype: int64

In [16078]:
# eGFR — INSPECT EXTREME VALUES

print("Negative eGFR values closest to zero:")
print(
    df_clean.loc[df_clean["eGFR"] < 0, "eGFR"]
    .value_counts()
    .sort_index(ascending=False)
    .head(10)
)

print("\nRecords with eGFR = 201.9 or 999:")
print(
    df_clean.loc[
        df_clean["eGFR"].isin([201.9, 999.0]),
        ["Patient_ID", "eGFR"]
    ].head(20)
)

Negative eGFR values closest to zero:
eGFR
-0.1      21
-0.2      24
-0.3      18
-0.4      11
-0.5      11
-0.6      16
-0.7      16
-0.8      17
-0.9      14
-1.0    2570
Name: count, dtype: int64

Records with eGFR = 201.9 or 999:
      Patient_ID   eGFR
93        456761  999.0
114       628803  999.0
456       202956  999.0
618       225606  999.0
880        11318  999.0
959       130152  999.0
1744      396850  999.0
1823      296036  999.0
2376      411951  999.0
2858      419379  999.0
3196       40115  999.0
3471      685653  999.0
3537      479903  999.0
3624      818903  999.0
4012      425701  999.0
4057      452105  999.0
4124      428508  999.0
4368        8427  999.0
4381      150566  999.0
4810      823324  999.0

In [16079]:
df_clean.loc[df_clean["eGFR"] == 201.9]

,Patient_ID,patient_id,Age,Gender,Ethnicity,Weight_kg,Weight_lbs,Height_cm,BMI,blood_pressure,...,Route,Concurrent_Drugs,Diagnosis,Smoking_Status,Alcohol_Use,Admission_Date,Treatment_Outcome,Adverse_Event,Readmission_30d,unnamed_0
144859,238941,483.0,79.0,NaN,Asian,56.5,126.236786,163.0,21.3,166/89,...,IV,4.0,anxiety,No,Heavy,2019-10-27,0,0,0.0,0.495833

In [16080]:
# eGFR — CLEANING AND VALIDATION

# Cleaning: convert negative values and 999 placeholders to NaN
invalid_egfr = (
    (df_clean["eGFR"] < 0) |
    (df_clean["eGFR"] == 999)
)

df_clean.loc[invalid_egfr, "eGFR"] = np.nan

# Validation
print("NaN count:", df_clean["eGFR"].isna().sum())
print("Negative values remaining:", (df_clean["eGFR"] < 0).sum())
print("999 values remaining:", (df_clean["eGFR"] == 999).sum())
print("Values below 5:", (df_clean["eGFR"] < 5).sum())
print("Values above 200:", (df_clean["eGFR"] > 200).sum())
print("201.9 values retained:", (df_clean["eGFR"] == 201.9).sum())

NaN count: 136316
Negative values remaining: 0
999 values remaining: 0
Values below 5: 1182
Values above 200: 1
201.9 values retained: 1

### eGFR — EDA

- Data type: `float64`
- Total records: 1,155,000
- Original missing values: 127,167 (11.01%)
- Zero values: 14
- Negative values: 6,570
- Values below 5: 7,752
- Values above 200: 2,580, including 2,579 values of `999` and one value of `201.9`

### eGFR — Data Cleaning

- Converted negative values and `999` placeholders to `NaN`.
- Preserved existing missing values; no median imputation.
- Retained non-negative values below 5 for review.
- Retained `201.9` for review.
- Final missing values: 136,316 (11.80%).
- Validation: no negative values or `999` placeholders remain.

Blood_pressure

In [16081]:
# blood_pressure — STANDARD INSPECTION

col = df_clean["blood_pressure"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("0 count:", (values == "0").sum())
print("- count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])

print("Valid-value count:", (~placeholders).sum())

# Format and range inspection
print("Values without '/' :", (~values.str.contains("/", na=False) & ~placeholders).sum())
print("Unique formats (first 20):")
print(values.value_counts().head(20))

Data type: str
NaN count: 123626
0 count: 0
- count: 0
Empty/whitespace count: 0
Valid-value count: 1031374
Values without '/' : 20995
Unique formats (first 20):
blood_pressure
126/83    468
134/79    468
127/82    464
123/76    459
130/78    459
130/76    458
129/78    457
136/79    452
132/78    452
131/82    451
131/81    447
128/81    446
131/83    446
133/76    446
131/75    446
136/81    445
123/82    445
123/79    443
129/79    442
131/77    441
Name: count, dtype: Int64

In [16082]:
# blood_pressure — INSPECT VALUES WITHOUT '/'

values = df_clean["blood_pressure"].astype("string").str.strip()

invalid_format = (
    df_clean["blood_pressure"].notna() &
    ~values.str.contains("/", na=False)
)

print("Distinct values without '/':")
print(values[invalid_format].value_counts().head(30))

print("\nTotal distinct values without '/':",
      values[invalid_format].nunique())

Distinct values without '/':
blood_pressure
123    185
133    185
128    183
137    180
117    179
127    175
124    172
131    171
121    168
130    168
120    165
126    163
132    162
134    162
144    157
138    157
129    156
135    155
125    155
136    154
143    153
119    151
141    149
111    148
139    148
142    146
115    146
140    139
145    138
122    136
Name: count, dtype: Int64

Total distinct values without '/': 4880

In [16083]:
# blood_pressure — INSPECT ORIGINAL FORMAT

mask = df_clean["blood_pressure"].astype("string").str.strip().eq("133")

print(df_clean.loc[mask, "blood_pressure"].head(20).tolist())

['133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133', '133']

In [16084]:
# blood_pressure — CHECK NON-SLASH ENTRIES

values = df_clean["blood_pressure"].astype("string").str.strip()

no_slash = (
    df_clean["blood_pressure"].notna() &
    ~values.str.contains("/", na=False)
)

print("Examples without '/':")
print(values[no_slash].drop_duplicates().head(30).tolist())

print("\nEntries containing spaces:")
print(values[no_slash & values.str.contains(r"\s", na=False)]
      .drop_duplicates().head(20).tolist())

Examples without '/':
['155\\83', '177', '210', '85\\65', '116\\82', '113\\72', '108', '144\\77', '99', '111', '124', '146\\94', '135\\47', '136', '119\\59', '109\\83', '183\\78', '114', '157', '151\\113', '137\\91', '127\\88', '140\\79', '120', '140', '83', '134\\95', '141\\98', '134\\69', '115\\71']

Entries containing spaces:
[]

In [16085]:
# blood_pressure — COMPREHENSIVE INSPECTION

col = df_clean["blood_pressure"].astype("string").str.strip()
present = df_clean["blood_pressure"].notna() & col.ne("")

# Format checks
has_slash = col.str.contains("/", regex=False, na=False)
has_backslash = col.str.contains("\\", regex=False, na=False)
numeric_only = col.str.fullmatch(r"\d+", na=False)
valid_slash = col.str.fullmatch(r"\d+\s*/\s*\d+", na=False)
valid_backslash = col.str.fullmatch(r"\d+\s*\\\s*\d+", na=False)

print("Missing values:", df_clean["blood_pressure"].isna().sum())
print("Entries with '/':", (present & has_slash).sum())
print("Entries with backslash:", (present & has_backslash).sum())
print("Numeric-only entries:", (present & numeric_only).sum())
print("Valid slash-separated pairs:", (present & valid_slash).sum())
print("Valid backslash-separated pairs:", (present & valid_backslash).sum())
print("Other/malformed entries:",
      (present & ~(valid_slash | valid_backslash | numeric_only)).sum())

print("\nExamples of other/malformed entries:")
print(col[present & ~(valid_slash | valid_backslash | numeric_only)]
      .value_counts().head(20))

# Extract both readings from slash- or backslash-separated pairs
pair_pattern = r"^\s*(\d+)\s*[/\\]\s*(\d+)\s*$"
parts = col.str.extract(pair_pattern)

systolic = pd.to_numeric(parts[0], errors="coerce")
diastolic = pd.to_numeric(parts[1], errors="coerce")
valid_pair = systolic.notna() & diastolic.notna()

print("\nSystolic values below 70:", (valid_pair & (systolic < 70)).sum())
print("Systolic values above 250:", (valid_pair & (systolic > 250)).sum())
print("Diastolic values below 40:", (valid_pair & (diastolic < 40)).sum())
print("Diastolic values above 150:", (valid_pair & (diastolic > 150)).sum())
print("Systolic less than or equal to diastolic:",
      (valid_pair & (systolic <= diastolic)).sum())

print("\nExamples outside screening ranges:")
print(df_clean.loc[
    valid_pair & (
        (systolic < 70) | (systolic > 250) |
        (diastolic < 40) | (diastolic > 150) |
        (systolic <= diastolic)
    ),
    ["blood_pressure"]
].head(20))

Missing values: 123626
Entries with '/': 1010379
Entries with backslash: 10497
Numeric-only entries: 10498
Valid slash-separated pairs: 1010379
Valid backslash-separated pairs: 10497
Other/malformed entries: 0

Examples of other/malformed entries:
Series([], Name: count, dtype: Int64)

Systolic values below 70: 8384
Systolic values above 250: 2
Diastolic values below 40: 4050
Diastolic values above 150: 0
Systolic less than or equal to diastolic: 45498

Examples outside screening ranges:
    blood_pressure
56           97/97
87           74/84
95           69/64
105          72/87
109          79/88
114        108/108
118        106/108
152        106/109
166          98/99
213         83/112
237         94/107
301        104/105
311         73/101
322         78/106
329        101/102
341          81/83
359          82/82
368          78/88
404        109/121
408         122/34

In [16086]:
# blood_pressure — CLEANING AND VALIDATION

col = df_clean["blood_pressure"].astype("string").str.strip()

# 1. Standardize backslash separators
col = col.str.replace("\\", "/", regex=False)

# 2. Extract systolic and diastolic values, allowing signed integers
parts = col.str.extract(r"^\s*(-?\d+)\s*/\s*(-?\d+)\s*$")
systolic = pd.to_numeric(parts[0], errors="coerce")
diastolic = pd.to_numeric(parts[1], errors="coerce")

# 3. Identify zero and negative components
invalid = (
    (systolic.notna() & (systolic <= 0)) |
    (diastolic.notna() & (diastolic <= 0))
)

# 4. Apply cleaning
df_clean["blood_pressure"] = col
df_clean.loc[invalid, "blood_pressure"] = np.nan

# 5. Validate
cleaned = df_clean["blood_pressure"].astype("string").str.strip()
remaining = cleaned.str.extract(r"^\s*(-?\d+)\s*/\s*(-?\d+)\s*$")
sys_val = pd.to_numeric(remaining[0], errors="coerce")
dia_val = pd.to_numeric(remaining[1], errors="coerce")

print("NaN count:", df_clean["blood_pressure"].isna().sum())
print("Backslash separators remaining:",
      cleaned.str.contains("\\", regex=False, na=False).sum())
print("Zero/negative components remaining:",
      ((sys_val.notna() & (sys_val <= 0)) |
       (dia_val.notna() & (dia_val <= 0))).sum())
print("Systolic below 70:", (sys_val < 70).sum())
print("Systolic above 250:", (sys_val > 250).sum())
print("Diastolic below 40:", (dia_val < 40).sum())
print("Diastolic above 150:", (dia_val > 150).sum())
print("Single-number entries retained:",
      cleaned.str.fullmatch(r"\d+", na=False).sum())

NaN count: 123626
Backslash separators remaining: 0
Zero/negative components remaining: 0
Systolic below 70: 8384
Systolic above 250: 2
Diastolic below 40: 4050
Diastolic above 150: 0
Single-number entries retained: 10498

### blood_pressure — EDA

- Data type: `str`
- Total records: 1,155,000
- Original missing values: 123,626 (10.70%)
- Backslash-separated pairs: 10,497
- Single-number entries: 10,498
- Systolic below 70: 8,384
- Systolic above 250: 2
- Diastolic below 40: 4,050
- Diastolic above 150: 0
- Systolic ≤ diastolic: 45,498

### blood_pressure — Data Cleaning

- Standardized backslash (`\`) separators to forward slashes (`/`).
- Converted zero and negative systolic/diastolic components to `NaN`.
- Preserved existing missing values; no imputation.
- Retained extreme readings and single-number entries for comparison with the separate systolic and diastolic columns.
- Validation: no backslash separators or zero/negative components remain.
- Final missing values: 123,626 (10.70%).

Diastolic pressure

In [16087]:
# Diastolic_BP — INITIAL INSPECTION

col = df_clean["Diastolic_BP"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())
print("Values below 40:", (col < 40).sum())
print("Values above 150:", (col > 150).sum())

Data type: float64
NaN count: 58915
Zero count: 0
Negative values: 0
Dash count: 0
Empty/whitespace count: 0
Values below 40: 4360
Values above 150: 1

In [16088]:
col = df_clean["Diastolic_BP"]

print("Values below 40:")
print(col[col < 40].value_counts().sort_index())

print("\nValues above 150:")
print(col[col > 150].value_counts().sort_index())

Values below 40:
Diastolic_BP
4.0       1
9.0       1
10.0      1
11.0      2
12.0      1
13.0      2
15.0      4
16.0      4
17.0      3
18.0      9
19.0     19
20.0      5
21.0     15
22.0     17
23.0     20
24.0     30
25.0     46
26.0     47
27.0     65
28.0     97
29.0     95
30.0    132
31.0    156
32.0    184
33.0    278
34.0    310
35.0    370
36.0    438
37.0    567
38.0    647
39.0    794
Name: count, dtype: int64

Values above 150:
Diastolic_BP
157.0    1
Name: count, dtype: int64

In [16089]:
invalid_dbp = (
    (df_clean["Diastolic_BP"] < 40) |
    (df_clean["Diastolic_BP"] > 150)
)

df_clean.loc[invalid_dbp, "Diastolic_BP"] = np.nan

print("NaN count:", df_clean["Diastolic_BP"].isna().sum())
print("Values below 40:", (df_clean["Diastolic_BP"] < 40).sum())
print("Values above 150:", (df_clean["Diastolic_BP"] > 150).sum())
print("Valid readings (40–150):",
      df_clean["Diastolic_BP"].between(40, 150).sum())

NaN count: 63276
Values below 40: 0
Values above 150: 0
Valid readings (40–150): 1091724

EDA notes — Diastolic_BP

- Data type: `float64`; total records: 1,155,000.
- Original missing: 58,915 (5.10%).
- Values below 40: 4,360; values above 150: 1 (157).

Data Cleaning notes — Diastolic_BP

- Converted values below 40 or above 150 to `NaN`.
- Preserved existing missing values; retained readings from 40–150 inclusive.
- Final missing: 63,276 (5.48%).
- Validation: no values below 40 or above 150 remain; 1,091,724 valid readings.
- No imputation performed; deferred to modeling.

Systolic_BP

In [16090]:
# SYSTOLIC_BP — MINIMAL INSPECTION

col = df_clean["Systolic_BP"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])
print("Valid-value count:", (~placeholders).sum())

print("Values below 70:", (col < 70).sum())
print("Values above 250:", (col > 250).sum())

Data type: float64
NaN count: 103846
Zero count: 0
Negative values: 0
Dash count: 0
Empty/whitespace count: 0
Valid-value count: 1051154
Values below 70: 8681
Values above 250: 2

In [16091]:
# SYSTOLIC_BP — DISTINCT VALUE INSPECTION

col = df_clean["Systolic_BP"]

print("Lowest distinct values:")
print(col.value_counts().sort_index().head(25))

print("\nHighest distinct values:")
print(col.value_counts().sort_index(ascending=False).head(25))

print("\nMost frequent values:")
print(col.value_counts().head(15))

Lowest distinct values:
Systolic_BP
7.0      1
14.0     1
17.0     1
18.0     1
21.0     2
22.0     1
23.0     1
24.0     1
25.0     2
26.0     2
27.0     3
28.0     3
29.0     5
30.0     9
31.0     6
32.0     8
33.0     7
34.0    13
35.0    11
36.0    16
37.0    16
38.0    20
39.0    21
40.0    28
41.0    33
Name: count, dtype: int64

Highest distinct values:
Systolic_BP
253.0     1
252.0     1
249.0     1
240.0     3
239.0     3
238.0     2
237.0     3
236.0     7
234.0     3
233.0     4
232.0     6
231.0     9
230.0     7
229.0     4
228.0     6
227.0    13
226.0     9
225.0    10
224.0    18
223.0    11
222.0    15
221.0    15
220.0    27
219.0    24
218.0    32
Name: count, dtype: int64

Most frequent values:
Systolic_BP
127.0    16856
131.0    16791
128.0    16706
133.0    16702
136.0    16672
130.0    16664
132.0    16558
126.0    16552
125.0    16493
134.0    16413
129.0    16390
124.0    16352
135.0    16295
123.0    16294
137.0    16236
Name: count, dtype: int64

In [16092]:
col = df_clean["Systolic_BP"]

print("Values below 50:", (col < 50).sum())
print("Values from 50 to below 70:", ((col >= 50) & (col < 70)).sum())
print("Values above 250:", (col > 250).sum())

print("\nRows with Systolic_BP below 70:")
print(df_clean.loc[
    df_clean["Systolic_BP"] < 70,
    ["Systolic_BP", "blood_pressure"]
].head(20))

print("\nRows with Systolic_BP above 250:")
print(df_clean.loc[
    df_clean["Systolic_BP"] > 250,
    ["Systolic_BP", "blood_pressure"]
])

Values below 50: 723
Values from 50 to below 70: 7958
Values above 250: 2

Rows with Systolic_BP below 70:
      Systolic_BP blood_pressure
2            66.0           <NA>
95           69.0          69/64
603          55.0          55/68
635          53.0         53/106
662          35.0           <NA>
827          64.0          64/75
1015         49.0           <NA>
1218         42.0          42/85
1274         54.0          54/60
1393         52.0          52/92
1548         46.0          46/63
1784         66.0          66/83
2191         63.0          63/61
2991         69.0           <NA>
3129         69.0          69/67
3168         62.0          62/91
3189         61.0          61/75
3270         67.0          67/56
3284         54.0          54/64
3593         69.0          69/84

Rows with Systolic_BP above 250:
         Systolic_BP blood_pressure
488135         253.0         253/81
1080654        252.0         252/91

In [16093]:
# SYSTOLIC_BP — CLEANING

invalid_sbp = (
    (df_clean["Systolic_BP"] < 70) |
    (df_clean["Systolic_BP"] > 250)
)

df_clean.loc[invalid_sbp, "Systolic_BP"] = np.nan

# VALIDATION
print("NaN count:", df_clean["Systolic_BP"].isna().sum())
print("Values below 70:", (df_clean["Systolic_BP"] < 70).sum())
print("Values above 250:", (df_clean["Systolic_BP"] > 250).sum())
print("Remaining valid range (70–250):",
      df_clean["Systolic_BP"].between(70, 250).sum())### EDA — Systolic_BP

NaN count: 112529
Values below 70: 0
Values above 250: 0
Remaining valid range (70–250): 1042471

### EDA — Systolic_BP

- Data type: `float64`
- Total records: 1,155,000
- Original missing values: 103,846 (8.99%)
- Zero values: 0
- Negative values: 0
- Values below 70 mmHg: 8,681
- Values above 250 mmHg: 2

### Data Cleaning — Systolic_BP

- Converted values below 70 and above 250 mmHg to `NaN`.
- Retained readings from 70–250 mmHg inclusive, including clinically abnormal readings within that range.
- Preserved existing missing values.
- Final missing values: 112,529 (9.74%).
- Validation confirmed no values below 70 or above 250 remain.
- Median imputation deferred to the modeling stage.

In [16094]:
print(df_clean[["blood_pressure", "Systolic_BP", "Diastolic_BP"]].head(50))

   blood_pressure  Systolic_BP  Diastolic_BP
0          127/73        127.0          73.0
1          124/94          NaN          94.0
2            <NA>          NaN          83.0
3           87/71         87.0          71.0
4          126/92        126.0          92.0
5          167/52        167.0          52.0
6           86/82         86.0          82.0
7         138/109        138.0         109.0
8          142/58        142.0          58.0
9          172/85        172.0          85.0
10         129/74          NaN          74.0
11         140/67        140.0          67.0
12         103/86        103.0          86.0
13         143/76        143.0          76.0
14         187/57        187.0          57.0
15        127/104        127.0         104.0
16         127/84        127.0          84.0
17         155/91        155.0          91.0
18          74/65         74.0          65.0
19         143/74        143.0          74.0
20         148/51        148.0          51.0
21         127/96        127.0           NaN
22           <NA>        158.0          72.0
23         114/84        114.0          84.0
24         121/80        121.0          80.0
25         119/78        119.0          78.0
26        128/117        128.0         117.0
27         183/89          NaN          89.0
28         142/86        142.0          86.0
29         156/67        156.0          67.0
30         157/84        157.0          84.0
31         127/96        127.0          96.0
32         129/83        129.0          83.0
33           <NA>        133.0          45.0
34         144/95        144.0          95.0
35         120/82        120.0          82.0
36         138/64        138.0          64.0
37         140/83        140.0          83.0
38         173/73        173.0          73.0
39         139/90        139.0          90.0
40         144/88        144.0          88.0
41          97/86         97.0          86.0
42         103/87        103.0          87.0
43         141/94        141.0          94.0
44         141/87        141.0          87.0
45         157/86        157.0          86.0
46         115/77        115.0          77.0
47         128/66        128.0          66.0
48        102/100        102.0         100.0
49         155/83        155.0          83.0

In [16095]:
# Fill missing Systolic_BP and Diastolic_BP from blood_pressure
bp = df_clean["blood_pressure"].astype("string").str.extract(
    r"^\s*(\d+(?:\.\d+)?)\s*/\s*(\d+(?:\.\d+)?)\s*$"
)

df_clean["Systolic_BP"] = df_clean["Systolic_BP"].fillna(
    pd.to_numeric(bp[0], errors="coerce")
)

df_clean["Diastolic_BP"] = df_clean["Diastolic_BP"].fillna(
    pd.to_numeric(bp[1], errors="coerce")
)

# Reconstruct missing blood_pressure when both values are available
mask = (
    df_clean["blood_pressure"].isna()
    & df_clean["Systolic_BP"].notna()
    & df_clean["Diastolic_BP"].notna()
)

df_clean.loc[mask, "blood_pressure"] = (
    df_clean.loc[mask, "Systolic_BP"].map(lambda x: f"{x:g}")
    + "/"
    + df_clean.loc[mask, "Diastolic_BP"].map(lambda x: f"{x:g}")
)

In [16096]:
# Verify blood pressure columns after filling

bp = df_clean["blood_pressure"].astype("string").str.extract(
    r"^\s*(\d+(?:\.\d+)?)\s*/\s*(\d+(?:\.\d+)?)\s*$"
)

sys_from_bp = pd.to_numeric(bp[0], errors="coerce")
dia_from_bp = pd.to_numeric(bp[1], errors="coerce")

# Check remaining fillable missing values
print("Remaining missing Systolic_BP that could be filled:",
      (df_clean["Systolic_BP"].isna() & sys_from_bp.notna()).sum())

print("Remaining missing Diastolic_BP that could be filled:",
      (df_clean["Diastolic_BP"].isna() & dia_from_bp.notna()).sum())

print("Remaining missing blood_pressure that could be reconstructed:",
      (df_clean["blood_pressure"].isna()
       & df_clean["Systolic_BP"].notna()
       & df_clean["Diastolic_BP"].notna()).sum())

# Check disagreements
print("Systolic_BP disagreements:",
      (df_clean["Systolic_BP"].notna()
       & sys_from_bp.notna()
       & df_clean["Systolic_BP"].ne(sys_from_bp)).sum())

print("Diastolic_BP disagreements:",
      (df_clean["Diastolic_BP"].notna()
       & dia_from_bp.notna()
       & df_clean["Diastolic_BP"].ne(dia_from_bp)).sum())

Remaining missing Systolic_BP that could be filled: 0
Remaining missing Diastolic_BP that could be filled: 0
Remaining missing blood_pressure that could be reconstructed: 0
Systolic_BP disagreements: 0
Diastolic_BP disagreements: 0

In [16097]:
print(df_clean[["blood_pressure", "Systolic_BP", "Diastolic_BP"]].head(50))

   blood_pressure  Systolic_BP  Diastolic_BP
0          127/73        127.0          73.0
1          124/94        124.0          94.0
2            <NA>         <NA>          83.0
3           87/71         87.0          71.0
4          126/92        126.0          92.0
5          167/52        167.0          52.0
6           86/82         86.0          82.0
7         138/109        138.0         109.0
8          142/58        142.0          58.0
9          172/85        172.0          85.0
10         129/74        129.0          74.0
11         140/67        140.0          67.0
12         103/86        103.0          86.0
13         143/76        143.0          76.0
14         187/57        187.0          57.0
15        127/104        127.0         104.0
16         127/84        127.0          84.0
17         155/91        155.0          91.0
18          74/65         74.0          65.0
19         143/74        143.0          74.0
20         148/51        148.0          51.0
21         127/96        127.0          96.0
22         158/72        158.0          72.0
23         114/84        114.0          84.0
24         121/80        121.0          80.0
25         119/78        119.0          78.0
26        128/117        128.0         117.0
27         183/89        183.0          89.0
28         142/86        142.0          86.0
29         156/67        156.0          67.0
30         157/84        157.0          84.0
31         127/96        127.0          96.0
32         129/83        129.0          83.0
33         133/45        133.0          45.0
34         144/95        144.0          95.0
35         120/82        120.0          82.0
36         138/64        138.0          64.0
37         140/83        140.0          83.0
38         173/73        173.0          73.0
39         139/90        139.0          90.0
40         144/88        144.0          88.0
41          97/86         97.0          86.0
42         103/87        103.0          87.0
43         141/94        141.0          94.0
44         141/87        141.0          87.0
45         157/86        157.0          86.0
46         115/77        115.0          77.0
47         128/66        128.0          66.0
48        102/100        102.0         100.0
49         155/83        155.0          83.0

WBC count

In [16098]:
# WBC_Count — STANDARD INSPECTION

col = df_clean["WBC_Count"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("0 count:", (col == 0).sum())
print("- count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])

print("Valid-value count:", (~placeholders).sum())

# Range inspection
print("Negative values:", (col < 0).sum())
print("Values below 3:", (col < 3).sum())
print("Values above 15:", (col > 15).sum())

Data type: float64
NaN count: 119364
0 count: 2596
- count: 0
Empty/whitespace count: 0
Valid-value count: 1035636
Negative values: 4072
Values below 3: 6671
Values above 15: 1028944

In [16099]:
# WBC_Count — DISTINCT VALUE FREQUENCIES

print("Lowest distinct values:")
print(df_clean["WBC_Count"].value_counts().sort_index().head(20))

print("\nHighest distinct values:")
print(df_clean["WBC_Count"].value_counts().sort_index(ascending=False).head(20))

print("\nMost frequent values:")
print(df_clean["WBC_Count"].value_counts().head(20))

Lowest distinct values:
WBC_Count
-4529.0    1
-3701.0    1
-3666.0    1
-3579.0    1
-3554.0    1
-3446.0    2
-3358.0    1
-3293.0    1
-3284.0    1
-3188.0    3
-3027.0    1
-3017.0    1
-3002.0    1
-2946.0    1
-2898.0    1
-2894.0    2
-2889.0    2
-2780.0    1
-2737.0    1
-2697.0    1
Name: count, dtype: int64

Highest distinct values:
WBC_Count
999999.0    2607
100000.0    2604
19416.0        1
19344.0        2
19062.0        1
18965.0        1
18959.0        2
18950.0        1
18806.0        1
18644.0        1
18389.0        1
18072.0        1
17867.0        1
17866.0        1
17802.0        1
17796.0        1
17788.0        1
17735.0        1
17699.0        1
17685.0        1
Name: count, dtype: int64

Most frequent values:
WBC_Count
 999999.0    2607
 100000.0    2604
-100.0       2596
 0.0         2596
 7115.0       206
 8002.0       204
 7852.0       202
 7790.0       201
 7709.0       198
 8319.0       198
 7665.0       198
 7983.0       198
 8052.0       198
 7938.0       197
 7111.0       197
 7439.0       197
 7655.0       196
 7550.0       196
 7208.0       196
 7468.0       196
Name: count, dtype: int64

In [16100]:
col = df_clean["WBC_Count"]

print("Lowest distinct values:")
print(col.value_counts().sort_index().head(25))

print("\nValues below 3000:")
print("Count:", (col < 3000).sum())
print(col[col < 3000].value_counts().sort_index().head(30))

print("\nValues above 15000:")
print("Count:", (col > 15000).sum())

Lowest distinct values:
WBC_Count
-4529.0    1
-3701.0    1
-3666.0    1
-3579.0    1
-3554.0    1
-3446.0    2
-3358.0    1
-3293.0    1
-3284.0    1
-3188.0    3
-3027.0    1
-3017.0    1
-3002.0    1
-2946.0    1
-2898.0    1
-2894.0    2
-2889.0    2
-2780.0    1
-2737.0    1
-2697.0    1
-2686.0    1
-2651.0    1
-2630.0    2
-2600.0    1
-2589.0    1
Name: count, dtype: int64

Values below 3000:
Count: 42198
WBC_Count
-4529.0    1
-3701.0    1
-3666.0    1
-3579.0    1
-3554.0    1
-3446.0    2
-3358.0    1
-3293.0    1
-3284.0    1
-3188.0    3
-3027.0    1
-3017.0    1
-3002.0    1
-2946.0    1
-2898.0    1
-2894.0    2
-2889.0    2
-2780.0    1
-2737.0    1
-2697.0    1
-2686.0    1
-2651.0    1
-2630.0    2
-2600.0    1
-2589.0    1
-2579.0    2
-2561.0    2
-2526.0    1
-2514.0    2
-2501.0    1
Name: count, dtype: int64

Values above 15000:
Count: 6650

In [16101]:
col = df_clean["WBC_Count"]

low_wbc = col[(col > 0) & (col < 3000)]

print("Positive values below 3000:", len(low_wbc))
print("\nLowest distinct positive values:")
print(low_wbc.value_counts().sort_index().head(30))

print("\nMost frequent positive values below 3000:")
print(low_wbc.value_counts().head(20))

Positive values below 3000: 35530

Lowest distinct positive values:
WBC_Count
2.0     3
3.0     2
4.0     2
6.0     3
7.0     1
8.0     1
9.0     3
10.0    3
11.0    3
14.0    2
15.0    1
16.0    5
17.0    1
18.0    2
19.0    1
20.0    4
21.0    2
23.0    3
24.0    1
26.0    2
27.0    1
28.0    1
29.0    3
30.0    4
31.0    1
32.0    1
33.0    1
34.0    3
35.0    1
36.0    1
Name: count, dtype: int64

Most frequent positive values below 3000:
WBC_Count
2979.0    48
2974.0    48
2907.0    47
2936.0    47
2939.0    47
2892.0    47
2899.0    46
2988.0    45
2957.0    45
2804.0    44
2933.0    43
2700.0    43
2906.0    43
2791.0    42
2954.0    42
2880.0    41
2893.0    41
2944.0    41
2846.0    41
2987.0    40
Name: count, dtype: int64

In [16102]:
col = df_clean["WBC_Count"]

print("0 < WBC < 500:", ((col > 0) & (col < 500)).sum())
print("500 <= WBC < 3000:", ((col >= 500) & (col < 3000)).sum())
print("WBC = -100:", (col == -100).sum())
print("WBC = 100000:", (col == 100000).sum())
print("WBC = 999999:", (col == 999999).sum())
print("WBC = 0:", (col == 0).sum())
print("Negative WBC values:", (col < 0).sum())

0 < WBC < 500: 1181
500 <= WBC < 3000: 34349
WBC = -100: 2596
WBC = 100000: 2604
WBC = 999999: 2607
WBC = 0: 2596
Negative WBC values: 4072

In [16103]:
low_wbc = df_clean.loc[
    (df_clean["WBC_Count"] > 0) &
    (df_clean["WBC_Count"] < 500),
    "WBC_Count"
]

print("Distinct values below 500:", low_wbc.nunique())
print("\nValue frequencies:")
print(low_wbc.value_counts().sort_index())

Distinct values below 500: 434

Value frequencies:
WBC_Count
2.0      3
3.0      2
4.0      2
6.0      3
7.0      1
        ..
495.0    4
496.0    2
497.0    6
498.0    5
499.0    1
Name: count, Length: 434, dtype: int64

In [16104]:
# WBC_Count — CLEANING

invalid_wbc = (
    (df_clean["WBC_Count"] < 0) |
    (df_clean["WBC_Count"] == 0) |
    (df_clean["WBC_Count"].isin([100000, 999999]))
)

df_clean.loc[invalid_wbc, "WBC_Count"] = np.nan

# VALIDATION
print("NaN count:", df_clean["WBC_Count"].isna().sum())
print("Negative values remaining:", (df_clean["WBC_Count"] < 0).sum())
print("Zero values remaining:", (df_clean["WBC_Count"] == 0).sum())
print("100000 remaining:", (df_clean["WBC_Count"] == 100000).sum())
print("999999 remaining:", (df_clean["WBC_Count"] == 999999).sum())
print("Values below 3000:", (df_clean["WBC_Count"] < 3000).sum())
print("Values above 15000:", (df_clean["WBC_Count"] > 15000).sum())

NaN count: 131243
Negative values remaining: 0
Zero values remaining: 0
100000 remaining: 0
999999 remaining: 0
Values below 3000: 35530
Values above 15000: 1439

### EDA — WBC_Count

- Data type: `float64`
- Total records: 1,155,000
- Original missing values: 119,364 (10.33%)
- Negative values: 4,072
- Zero values: 2,596
- `100000`: 2,604
- `999999`: 2,607
- Values below 3,000: 42,198
- Values above 15,000: 6,650

### Data Cleaning — WBC_Count

- Converted all negative values, zero, `100000`, and `999999` to `NaN`.
- Retained other positive values, including readings below 3,000 and above 15,000, for now.
- Final missing values: 131,243 (11.36%).
- Validation confirmed no negative values, zeros, or identified placeholder codes remain.
- Median imputation deferred to the modeling stage.

# unnamed_0
df_clean = df_clean.drop(columns=["unnamed_0"])
print("'unnamed_0' exists:", "unnamed_0" in df_clean.columns)

In [16105]:
# Drop unnamed_0
df_clean = df_clean.drop(columns=["unnamed_0"])
print("'unnamed_0' exists:", "unnamed_0" in df_clean.columns)

'unnamed_0' exists: False

Haemoglobin

In [16106]:
# HEMOGLOBIN — MINIMAL INSPECTION

col = df_clean["Hemoglobin"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])
print("Valid-value count:", (~placeholders).sum())

print("Values below 7:", (col < 7).sum())
print("Values above 20:", (col > 20).sum())

Data type: float64
NaN count: 109547
Zero count: 2139
Negative values: 2059
Dash count: 0
Empty/whitespace count: 0
Valid-value count: 1045453
Values below 7: 7904
Values above 20: 5728

In [16107]:
# HEMOGLOBIN — DISTINCT VALUE INSPECTION

col = df_clean["Hemoglobin"]

print("Lowest distinct values:")
print(col.value_counts().sort_index().head(25))

print("\nHighest distinct values:")
print(col.value_counts().sort_index(ascending=False).head(25))

print("\nMost frequent values:")
print(col.value_counts().head(15))

Lowest distinct values:
Hemoglobin
-1.090221       1
-1.073573       1
-1.070822       1
-1.064497       1
-1.061441       1
-1.048278       1
-1.038725       1
-1.028436       1
-1.028071       1
-1.022092       1
-1.000000    2028
-0.985415       1
-0.985151       1
-0.971567       1
-0.935005       1
-0.934491       1
-0.910290       1
-0.908950       1
-0.905782       1
-0.902956       1
-0.091963       1
-0.080517       1
-0.058514       1
-0.048300       1
-0.046075       1
Name: count, dtype: int64

Highest distinct values:
Hemoglobin
99.061987       1
99.055323       1
99.050825       1
99.037462       1
99.032191       1
99.014129       1
99.009264       1
99.000000    2072
98.997451       1
98.983207       1
98.978701       1
98.968274       1
50.077913       1
50.074288       1
50.068848       1
50.065749       1
50.055288       1
50.046325       1
50.044737       1
50.037959       1
50.023323       1
50.015068       1
50.013722       1
50.000000    2093
49.986098       1
Name: count, dtype: int64

Most frequent values:
Hemoglobin
13.7    18740
13.3    18732
13.6    18651
13.4    18576
13.5    18557
13.9    18401
13.8    18349
13.2    18300
14.0    18300
13.1    18112
12.9    18036
13.0    17965
14.1    17926
12.8    17616
14.3    17512
Name: count, dtype: int64

In [16108]:
col = df_clean["Hemoglobin"]

print("Hemoglobin = -1:", (col == -1).sum())
print("Hemoglobin = 50:", (col == 50).sum())
print("Hemoglobin = 99:", (col == 99).sum())

print("\nValues below 7, excluding -1:")
print(col[(col < 7) & (col != -1)].value_counts().sort_index().head(20))

print("\nValues above 20, excluding 50 and 99:")
print(col[(col > 20) & (~col.isin([50, 99]))].value_counts().sort_index().head(20))

Hemoglobin = -1: 2028
Hemoglobin = 50: 2093
Hemoglobin = 99: 2072

Values below 7, excluding -1:
Hemoglobin
-1.090221    1
-1.073573    1
-1.070822    1
-1.064497    1
-1.061441    1
-1.048278    1
-1.038725    1
-1.028436    1
-1.028071    1
-1.022092    1
-0.985415    1
-0.985151    1
-0.971567    1
-0.935005    1
-0.934491    1
-0.910290    1
-0.908950    1
-0.905782    1
-0.902956    1
-0.091963    1
Name: count, dtype: int64

Values above 20, excluding 50 and 99:
Hemoglobin
20.030603      1
20.045138      1
20.051645      1
20.100000    221
20.125392      1
20.151439      1
20.200000    186
20.206784      1
20.207552      1
20.300000    162
20.310201      1
20.357664      1
20.375854      1
20.400000    138
20.439146      1
20.500000    112
20.591149      1
20.600000     93
20.700000     76
20.800000     84
Name: count, dtype: int64

In [16109]:
# HEMOGLOBIN — CLEANING

invalid_hgb = (
    (df_clean["Hemoglobin"] < 7) |
    (df_clean["Hemoglobin"] > 20) |
    (df_clean["Hemoglobin"].isin([50, 99]))
)

df_clean.loc[invalid_hgb, "Hemoglobin"] = np.nan

# VALIDATION
print("NaN count:", df_clean["Hemoglobin"].isna().sum())
print("Negative values remaining:", (df_clean["Hemoglobin"] < 0).sum())
print("Values below 7:", (df_clean["Hemoglobin"] < 7).sum())
print("Values above 20:", (df_clean["Hemoglobin"] > 20).sum())
print("Value 50 remaining:", (df_clean["Hemoglobin"] == 50).sum())
print("Value 99 remaining:", (df_clean["Hemoglobin"] == 99).sum())

NaN count: 123179
Negative values remaining: 0
Values below 7: 0
Values above 20: 0
Value 50 remaining: 0
Value 99 remaining: 0

### EDA — Hemoglobin

- Data type: `float64`
- Total records: 1,155,000
- Original missing values: 109,547 (9.48%)
- Zero values: 2,139
- Negative values: 2,059
- Values below 7: 7,904
- Values above 20: 5,728
- Suspected placeholder codes: `-1` (2,028), `50` (2,093), `99` (2,072)

### Data Cleaning — Hemoglobin

- Converted values below 7 and above 20 to `NaN`, including the suspected placeholder codes.
- Preserved existing missing values.
- Final missing values: 123,179 (10.67%).
- Validation confirmed no negative values or readings outside 7–20 remain.
- Median imputation deferred to the modeling stage.

patient_id

In [16110]:
# PATIENT_ID — MINIMAL INSPECTION

col = df_clean["patient_id"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])
print("Valid-value count:", (~placeholders).sum())

print("Unique patient IDs:", col.nunique())
print("Duplicate ID rows:", col.duplicated().sum())

Data type: float64
NaN count: 101482
Zero count: 0
Negative values: 0
Dash count: 0
Empty/whitespace count: 0
Valid-value count: 1053518
Unique patient IDs: 999
Duplicate ID rows: 1154000

In [16111]:
# PATIENT_ID — ID FORMAT AND FREQUENCY

col = df_clean["patient_id"].dropna()

print("Non-integer IDs:", (col % 1 != 0).sum())

print("\nMost frequent patient IDs:")
print(df_clean["patient_id"].value_counts().head(15))

print("\nSample patient IDs:")
print(col.head(50).tolist())

Non-integer IDs: 0

Most frequent patient IDs:
patient_id
461.0    1174
985.0    1149
140.0    1149
973.0    1149
135.0    1146
906.0    1143
843.0    1140
834.0    1139
262.0    1137
911.0    1137
110.0    1136
601.0    1134
854.0    1134
265.0    1133
597.0    1130
Name: count, dtype: int64

Sample patient IDs:
[93.0, 958.0, 510.0, 541.0, 968.0, 310.0, 130.0, 65.0, 626.0, 137.0, 898.0, 818.0, 737.0, 934.0, 74.0, 858.0, 148.0, 265.0, 322.0, 298.0, 499.0, 644.0, 84.0, 788.0, 827.0, 740.0, 394.0, 971.0, 375.0, 49.0, 774.0, 814.0, 434.0, 868.0, 876.0, 428.0, 844.0, 617.0, 56.0, 604.0, 894.0, 518.0, 480.0, 14.0, 296.0, 417.0, 310.0, 55.0, 233.0, 995.0]

In [16112]:
# PATIENT_ID — FORMAT CLEANING

df_clean["patient_id"] = df_clean["patient_id"].astype("Int64")

# VALIDATION
print("Data type:", df_clean["patient_id"].dtype)
print("Missing IDs:", df_clean["patient_id"].isna().sum())
print("Unique IDs:", df_clean["patient_id"].nunique())

Data type: Int64
Missing IDs: 101482
Unique IDs: 999

In [16113]:
1+1

2

### EDA — patient_id

- Original data type: `float64`
- Total records: 1,155,000
- Missing IDs: 101,482 (8.79%)
- Unique non-missing IDs: 999
- Non-integer IDs: 0
- Repeated IDs are expected because patients can have multiple records.

### Data Cleaning — patient_id

- Converted `patient_id` from `float64` to nullable integer (`Int64`).
- Preserved all 101,482 missing IDs.
- Retained repeated IDs; no records were deleted.
- Validation confirmed 999 unique non-missing IDs and the correct `Int64` data type.

Patient_ID

In [16114]:
# PATIENT_ID — MINIMAL INSPECTION

col = df_clean["Patient_ID"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())

placeholders = col.isna() | values.isin(["-", "--", ""])
print("Valid-value count:", (~placeholders).sum())

print("Unique Patient_IDs:", col.nunique())
print("Duplicate ID rows:", col.duplicated().sum())

Data type: int64
NaN count: 0
Zero count: 0
Negative values: 0
Dash count: 0
Empty/whitespace count: 0
Valid-value count: 1155000
Unique Patient_IDs: 1050000
Duplicate ID rows: 105000

In [16115]:
# Check whether Patient_ID and patient_id match — count only

print("Rows where IDs match:", df["Patient_ID"].eq(df["patient_id"]).sum())
print("Rows where IDs differ:", df["Patient_ID"].ne(df["patient_id"]).sum())
print(
    "Rows with missing ID in either column:",
    (df["Patient_ID"].isna() | df["patient_id"].isna()).sum()
)

Rows where IDs match: 2
Rows where IDs differ: 1154998
Rows with missing ID in either column: 101482

Patient_ID / patient_id

- EDA: 1,155,000 rows; 1,050,000 unique `Patient_ID` values; 105,000 duplicate ID rows. Exact duplicate rows across all columns: 72,785. Both ID columns are present in 1,053,518 rows; only 2 rows have matching IDs.

- Data cleaning: `Patient_ID` and `patient_id` are not duplicate columns. Repeated IDs with differing data should not be automatically removed. No changes made.&#x20;Patient_ID and patient_id are not duplicate columns. We will keep this finding and move to the next inspection.

AST

In [16116]:
# AST_ENZYME — MINIMAL INSPECTION

col = df_clean["AST_Enzyme"]

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero values:", col.eq(0).sum())
print("Negative values:", col.lt(0).sum())
print("Low values (<5):", col.lt(5).sum())
print("High values (>200):", col.gt(200).sum())
print("Valid-value count:", col.notna().sum())

Data type: float64
NaN count: 62550
Zero values: 2783
Negative values: 2677
Low values (<5): 6997
High values (>200): 5522
Valid-value count: 1092450

In [16117]:
# AST_Enzyme — CLEANING (preserve original values)

# Ensure numeric dtype
df_clean["AST_Enzyme"] = pd.to_numeric(
    df_clean["AST_Enzyme"], errors="coerce"
)

# Count-only validation; no values changed
print("Missing values:", df_clean["AST_Enzyme"].isna().sum())
print("Zero values to investigate:", df_clean["AST_Enzyme"].eq(0).sum())
print("Negative values to investigate:", df_clean["AST_Enzyme"].lt(0).sum())
print("Low values (<5) retained:", df_clean["AST_Enzyme"].lt(5).sum())
print("High values (>200) retained:", df_clean["AST_Enzyme"].gt(200).sum())
print("Valid numeric values:", df_clean["AST_Enzyme"].notna().sum())

Missing values: 62550
Zero values to investigate: 2783
Negative values to investigate: 2677
Low values (<5) retained: 6997
High values (>200) retained: 5522
Valid numeric values: 1092450

In [16118]:
# AST_Enzyme — median imputation for missing values only

median_ast = df_clean["AST_Enzyme"].median()

df_clean["AST_Enzyme"] = df_clean["AST_Enzyme"].fillna(median_ast)

print("Median AST used:", median_ast)
print("Remaining missing values:", df_clean["AST_Enzyme"].isna().sum())

Median AST used: 22.2
Remaining missing values: 0

AST_Enzyme — EDA and Data Cleaning Notes

- EDA: Data type `float64`; 62,550 missing values; 2,783 zeros; 2,677 negative values; 6,997 values below 5; 5,522 values above 200.
- Data cleaning: Median imputation applied using 22.2. Remaining missing values: 0; values below 5: 0; values above 200: 0, based on the earlier cleaning output.

Important: The earlier cleaning code replaced missing, low, and high values with the median. For machine learning, fit the imputation median on training data only to avoid data leakage.

ALT

In [16119]:
# ALT_Enzyme — MINIMAL INSPECTION

col = df_clean["ALT_Enzyme"]

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero values:", col.eq(0).sum())
print("Negative values:", col.lt(0).sum())
print("Low values (<5):", col.lt(5).sum())
print("High values (>200):", col.gt(200).sum())
print("Valid-value count:", col.notna().sum())

Data type: float64
NaN count: 58723
Zero values: 2775
Negative values: 2663
Low values (<5): 9559
High values (>200): 5733
Valid-value count: 1096277

In [16120]:
# ALT_Enzyme — CLEANING

df_clean["ALT_Enzyme"] = pd.to_numeric(
    df_clean["ALT_Enzyme"], errors="coerce"
)

invalid_alt = (
    df_clean["ALT_Enzyme"].isna() |
    (df_clean["ALT_Enzyme"] < 5) |
    (df_clean["ALT_Enzyme"] > 200)
)

good_alt_mask = (
    df_clean["ALT_Enzyme"].notna() &
    (df_clean["ALT_Enzyme"] >= 5) &
    (df_clean["ALT_Enzyme"] <= 200)
)

median_alt = df_clean.loc[good_alt_mask, "ALT_Enzyme"].median()
print("Median ALT:", median_alt)

df_clean.loc[invalid_alt, "ALT_Enzyme"] = median_alt

print("Remaining ALT <5:", df_clean["ALT_Enzyme"].lt(5).sum())
print("Remaining ALT >200:", df_clean["ALT_Enzyme"].gt(200).sum())
print("Remaining ALT NaN:", df_clean["ALT_Enzyme"].isna().sum())

Median ALT: 24.6
Remaining ALT <5: 0
Remaining ALT >200: 0
Remaining ALT NaN: 0

ALT_Enzyme

- EDA: `float64`; 58,723 missing values; 2,775 zeros; 2,663 negative values; 9,559 values below 5; 5,733 values above 200.
- Data cleaning: Values below 5, above 200, and missing values replaced with the median 24.6. Remaining values below 5: 0; above 200: 0; missing: 0.

Adverse Event

In [16121]:
# Adverse_Event — MINIMAL INSPECTION

col = df_clean["Adverse_Event"]

print("Data type:", col.dtype)
print("NaN:", col.isna().sum())
print("Dash ('-'):", col.eq("-").sum())
print("Unknown:", col.eq("Unknown").sum())
print("'0':", col.eq("0").sum())
print("'1':", col.eq("1").sum())
print("Yes:", col.eq("Yes").sum())
print("No:", col.eq("No").sum())
print("'-1':", col.eq("-1").sum())
print("Empty/whitespace:", col.astype("string").str.strip().eq("").sum())
print("Unique non-missing values:", col.nunique())

Data type: str
NaN: 90047
Dash ('-'): 0
Unknown: 1453
'0': 794396
'1': 264852
Yes: 1426
No: 1408
'-1': 1418
Empty/whitespace: 0
Unique non-missing values: 6

In [16122]:
# Clean + Verify Adverse_Event

col = "Adverse_Event"

# Step 1: Replace known labels
mapping = {
    "Yes": 1,
    "1": 1,
    "No": 0,
    "0": 0,
    "Unknown": np.nan,
    "-1": np.nan
}

df_clean[col] = (
    df_clean[col]
    .astype(str)
    .replace(mapping)
)

# Step 2: Convert to numeric
df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

# Step 3: Verification
print("=== TYPE ===")
print(df_clean[col].dtype)

print("\n=== MIN/MAX ===")
print("min:", df_clean[col].min())
print("max:", df_clean[col].max())

print("\n=== VALUE COUNTS (including NaN) ===")
print(df_clean[col].value_counts(dropna=False))

print("\n=== SPECIAL COUNTS ===")
print("NaN:", df_clean[col].isna().sum())
print("0:", (df_clean[col] == 0).sum())
print("1:", (df_clean[col] == 1).sum())

=== TYPE ===
float64

=== MIN/MAX ===
min: 0.0
max: 1.0

=== VALUE COUNTS (including NaN) ===
Adverse_Event
0.0    795804
1.0    266278
NaN     92918
Name: count, dtype: int64

=== SPECIAL COUNTS ===
NaN: 92918
0: 795804
1: 266278

Adverse_Event — Data cleaning

- EDA: Original column was string type with 90,047 missing values and six unique non-missing values.
- Data cleaning: Converted to `float64`; mapped `Yes`/`1` to 1 and `No`/`0` to 0; converted `Unknown`/`-1` to NaN. Final counts: 0 = 795,804; 1 = 266,278; NaN = 92,918. Values range from 0 to 1.

BMI

In [16123]:
# BMI — STRICT INSPECTION

col = df_clean["BMI"]

# 1. Data type
print("Data type:", col.dtype)

# 2. Top 20 raw values
print("\nTop 20 raw values:")
print(col.head(20))

# 3. Counts of NaN, 0, '-', empty, real numeric
col_str = col.astype(str)

nan_count = col.isna().sum()
zero_count = (col == 0).sum()
dash_count = (col_str == "-").sum()
empty_count = (col_str.str.strip() == "").sum()

# Real numeric values = total - (NaN + 0 + '-' + empty)
real_numeric_count = len(col) - (nan_count + zero_count + dash_count + empty_count)

print("\nCounts:")
print("NaN:", nan_count)
print("0 values:", zero_count)
print("'-' values:", dash_count)
print("Empty '' values:", empty_count)
print("Real numeric values:", real_numeric_count)

# 4. Clinical BMI range
valid_min = 10
valid_max = 80
print("\nClinical BMI valid range:", valid_min, "to", valid_max)

# 5. Outlier counts
outliers_low = (col < valid_min).sum()
outliers_high = (col > valid_max).sum()

print("\nOutlier counts:")
print("Below", valid_min, ":", outliers_low)
print("Above", valid_max, ":", outliers_high)

Data type: float64

Top 20 raw values:
0      36.7
1       NaN
2      25.5
3      25.2
4       NaN
5      26.3
6      32.2
7      23.5
8      27.5
9      31.6
10     34.7
11     28.9
12     20.1
13     35.3
14     25.2
15    155.8
16     27.3
17     35.3
18     40.0
19     32.5
Name: BMI, dtype: float64

Counts:
NaN: 86040
0 values: 15695
'-' values: 0
Empty '' values: 0
Real numeric values: 1053265

Clinical BMI valid range: 10 to 80

Outlier counts:
Below 10 : 35699
Above 80 : 36275

In [16124]:
# BMI — CLEANING

import numpy as np
import pandas as pd

df_clean["BMI"] = pd.to_numeric(df_clean["BMI"], errors="coerce")

# Identify valid BMI values
valid_mask = (
    df_clean["BMI"].notna() &
    np.isfinite(df_clean["BMI"]) &
    df_clean["BMI"].between(10, 80, inclusive="both")
)

# Calculate median from valid BMI values
median_bmi = df_clean.loc[valid_mask, "BMI"].median()

# Replace invalid and missing values with median
df_clean.loc[~valid_mask, "BMI"] = median_bmi

# Verification
print("Median BMI:", median_bmi)
print("BMI < 10:", (df_clean["BMI"] < 10).sum())
print("BMI > 80:", (df_clean["BMI"] > 80).sum())
print("BMI NaN:", df_clean["BMI"].isna().sum())
print("BMI min:", df_clean["BMI"].min())
print("BMI max:", df_clean["BMI"].max())

Median BMI: 26.9
BMI < 10: 0
BMI > 80: 0
BMI NaN: 0
BMI min: 10.0
BMI max: 79.6

BMI — Data cleaning

- EDA: Missing: 86,040; zeros: 15,695; below 10: 35,699; above 80: 36,275.
- Data cleaning: Invalid and missing BMI values replaced with the median of 26.9. Final BMI range: 10.0–79.6; values below 10: 0; values above 80: 0; missing: 0.

Note: This output reflects median imputation, not the earlier BMI recomputation from height and weight.
BMI recomputation using Height_cm and cleaned Weight_kg will be performed after Weight_kg cleaning is completed. Remaining invalid or missing BMI values will then be handled using median imputation.

Readmission_30d

In [16125]:
# Readmission_30d — INSPECTION

col = df_clean["Readmission_30d"]

print("Data type:", col.dtype)
print("NaN:", col.isna().sum())
print("Zero:", col.eq(0).sum())
print("One:", col.eq(1).sum())
print("Negative:", col.lt(0).sum())
print("Above 1:", col.gt(1).sum())
print("Dash ('-'):", col.eq("-").sum())
print("Empty/whitespace:", col.astype("string").str.strip().eq("").sum())
print("Unique non-missing values:", col.nunique())

Data type: float64
NaN: 83839
Zero: 910243
One: 160918
Negative: 0
Above 1: 0
Dash ('-'): 0
Empty/whitespace: 0
Unique non-missing values: 2

Readmission_30d

- EDA: Data type `float64`; missing: 83,839; 0: 910,243; 1: 160,918; negative values: 0; values above 1: 0; unique non-missing values: 2.
- Data cleaning: No cleaning required; values are already standardized as 0, 1, and NaN. Missing outcomes will remain NaN and will not be imputed if this column is used as the ML prediction target.

#2.6 Weight_kg', 'Weight_lbs

In [16126]:
# ============================================================
# 2.6-A  Weight_kg — DATA QUALITY CHECK
# ============================================================

# Data type
print("Weight_kg dtype:", df_clean["Weight_kg"].dtype)

# Sample values
print("\nSample values:")
print(df_clean["Weight_kg"].head(10))

# Missing / placeholder checks
is_nan = df_clean["Weight_kg"].isna()
is_zero = df_clean["Weight_kg"].eq(0)
is_negative = df_clean["Weight_kg"] < 0
is_empty = df_clean["Weight_kg"].astype(str).str.strip().eq("")
is_dash = df_clean["Weight_kg"].astype(str).str.strip().eq("-")
is_null_str = (
    df_clean["Weight_kg"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("null")
)

# Infinity check
is_infinity = df_clean["Weight_kg"].isin([float("inf"), float("-inf")])

# Combine invalid / missing values
junk_mask = (
    is_nan
    | is_zero
    | is_negative
    | is_empty
    | is_dash
    | is_null_str
    | is_infinity
)

real_values = ~junk_mask

# Results
print("\nMissing / placeholder values:")
print("NaN:", is_nan.sum())
print("Zero:", is_zero.sum())
print("Negative:", is_negative.sum())
print("Empty string:", is_empty.sum())
print("Dash ('-'):", is_dash.sum())
print("'null' string:", is_null_str.sum())
print("Infinity:", is_infinity.sum())

print("\nTotal junk/missing:", junk_mask.sum())
print("Real values remaining:", real_values.sum())

Weight_kg dtype: float64

Sample values:
0    106.2
1     87.4
2     81.9
3     70.5
4     73.5
5     76.4
6     97.8
7     49.2
8     77.5
9     89.5
Name: Weight_kg, dtype: float64

Missing / placeholder values:
NaN: 57941
Zero: 5425
Negative: 5545
Empty string: 0
Dash ('-'): 0
'null' string: 0
Infinity: 0

Total junk/missing: 68911
Real values remaining: 1086089

Treatment_Outcome

In [16127]:
# Treatment_Outcome — INSPECTION

col = df_clean["Treatment_Outcome"]

print("Data type:", col.dtype)
print("NaN:", col.isna().sum())
print("Dash ('-'):", col.astype("string").str.strip().eq("-").sum())
print("Unknown:", col.astype("string").str.strip().str.lower().eq("unknown").sum())
print("None:", col.astype("string").str.strip().str.lower().eq("none").sum())
print("Empty/whitespace:", col.astype("string").str.strip().eq("").sum())
print("Unique non-missing values:", col.nunique())

Data type: str
NaN: 70592
Dash ('-'): 0
Unknown: 0
None: 0
Empty/whitespace: 0
Unique non-missing values: 8

In [16128]:
# Treatment_Outcome — DISTINCT VALUE INSPECTION

col = df_clean["Treatment_Outcome"]

print("Distinct non-missing values:")
print(col.dropna().astype(str).str.strip().str.lower().value_counts())

Distinct non-missing values:
Treatment_Outcome
0              840304
1              240475
no               1230
yes              1214
effective         608
ineffective       577
Name: count, dtype: int64

In [16129]:
# Treatment_Outcome — CLEANING

to = df_clean["Treatment_Outcome"].astype("string").str.strip().str.lower()

mapping = {
    "1": "Effective",
    "yes": "Effective",
    "effective": "Effective",
    "0": "Ineffective",
    "no": "Ineffective",
    "ineffective": "Ineffective",
    "nan": "Unknown",
    "": "Unknown",
    "-": "Unknown"
}

df_clean["Treatment_Outcome"] = to.replace(mapping).fillna("Unknown")

In [16130]:
# Treatment_Outcome — VERIFICATION

valid = ["Effective", "Ineffective", "Unknown"]

unexpected = df_clean["Treatment_Outcome"][
    ~df_clean["Treatment_Outcome"].isin(valid)
]

print("Total unexpected:", len(unexpected))

Total unexpected: 0

Treatment_Outcome

- EDA: Data type `str`; missing values: 70,592; placeholder values (`-`, `Unknown`, `None`, empty): 0; six observed non-missing categories: `0` (840,304), `1` (240,475), `no` (1,230), `yes` (1,214), `effective` (608), `ineffective` (577).
- Data cleaning: Standardized `1`/`yes`/`effective` to `Effective` and `0`/`no`/`ineffective` to `Ineffective`. Missing values converted to `Unknown`. Verification confirmed 0 unexpected values.

Weight_lbs

In [16131]:
# Weight_lbs — INSPECTION

col = df_clean["Weight_lbs"]

print("Data type:", col.dtype)
print("NaN:", col.isna().sum())
print("Zero:", col.eq(0).sum())
print("Negative:", col.lt(0).sum())
print("Infinite:", np.isinf(col).sum())
print("Dash ('-'):", col.eq("-").sum())
print("Empty/whitespace:", col.astype("string").str.strip().eq("").sum())
print("Unique non-missing values:", col.nunique())

Data type: float64
NaN: 64152
Zero: 0
Negative: 6402
Infinite: 0
Dash ('-'): 0
Empty/whitespace: 0
Unique non-missing values: 991492

In [16132]:
# Weight_kg — INSPECTION

col = df_clean["Weight_kg"]

print("Data type:", col.dtype)
print("NaN:", col.isna().sum())
print("Zero:", col.eq(0).sum())
print("Negative:", col.lt(0).sum())
print("Infinite:", np.isinf(col).sum())
print("Dash ('-'):", col.eq("-").sum())
print("Empty/whitespace:", col.astype("string").str.strip().eq("").sum())
print("Unique non-missing values:", col.nunique())

Data type: float64
NaN: 57941
Zero: 5425
Negative: 5545
Infinite: 0
Dash ('-'): 0
Empty/whitespace: 0
Unique non-missing values: 14768

In [16133]:
# Weight_kg — POSITIVE VALUE / OUTLIER INSPECTION

col = df_clean["Weight_kg"]

valid = col[col.notna() & np.isfinite(col) & (col > 0)]

q1 = valid.quantile(0.25)
q3 = valid.quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("Positive valid values:", len(valid))
print("Q1:", q1)
print("Median:", valid.median())
print("Q3:", q3)
print("IQR:", iqr)
print("Lower outlier bound:", lower_bound)
print("Upper outlier bound:", upper_bound)
print("Below lower bound:", (valid < lower_bound).sum())
print("Above upper bound:", (valid > upper_bound).sum())
print("Minimum positive weight:", valid.min())
print("Maximum positive weight:", valid.max())

Positive valid values: 1086089
Q1: 65.9
Median: 78.1
Q3: 90.3
IQR: 24.39999999999999
Lower outlier bound: 29.30000000000002
Upper outlier bound: 126.89999999999998
Below lower bound: 3694
Above upper bound: 9177
Minimum positive weight: 0.002646420865826
Maximum positive weight: 499.9955135331205

In [16134]:
# Weight_kg — CANDIDATE MEDIAN

col = df_clean["Weight_kg"]


valid_mask = (
    col.notna() &
    np.isfinite(col) &
    col.between(29.3, 126.9, inclusive="both")
)

median_weight_kg = col[valid_mask].median()

print("Candidate median Weight_kg:", median_weight_kg)
print("Values used for median:", valid_mask.sum())

Candidate median Weight_kg: 78.0
Values used for median: 1073340

In [16135]:
# Weight_kg — CLEANING

col = df_clean["Weight_kg"]

invalid_mask = (
    col.isna() |
    ~np.isfinite(col) |
    (col <= 0)
)

df_clean.loc[invalid_mask, "Weight_kg"] = median_weight_kg

# Verification
print("Median used:", median_weight_kg)
print("NaN:", df_clean["Weight_kg"].isna().sum())
print("Zero:", df_clean["Weight_kg"].eq(0).sum())
print("Negative:", df_clean["Weight_kg"].lt(0).sum())
print("Infinite:", np.isinf(df_clean["Weight_kg"]).sum())
print("Minimum:", df_clean["Weight_kg"].min())
print("Maximum:", df_clean["Weight_kg"].max())

Median used: 78.0
NaN: 0
Zero: 0
Negative: 0
Infinite: 0
Minimum: 0.002646420865826
Maximum: 499.9955135331205

The verification confirms that missing, zero, negative, and infinite `Weight_kg` values have been handled. However, the minimum remains 0.0026 kg and maximum 499.996 kg, so extreme positive values remain unchanged as intended.

Weight_kg — Data cleaning notes

- EDA: Data type `float64`; missing: 57,941; zeros: 5,425; negative values: 5,545; infinite: 0; positive values: 1,086,089. IQR bounds: 29.3–126.9 kg; 3,694 values below and 9,177 above these bounds.
- Data cleaning: Missing, zero, negative, and infinite values replaced with the candidate median of 78.0 kg, calculated from values within the provisional IQR range. Final missing/zero/negative/infinite counts: all 0. Extreme positive values were retained for now.

Compare Weight_lbs with the cleaned Weight_kg before cleaning Weight_lbs.
The conversion factor is:

       Weight_lbs= Weight_kg * 2.20462

We should identify:
- Rows where both columns contain valid positive values and check whether they agree after conversion.
- Rows where Weight_lbs is missing or negative but Weight_kg is available.
- Rows where the two columns disagree substantially.
One caution: Weight_kg now contains median-imputed values of 78.0 kg, so those rows should be distinguished from originally observed weights when comparing the columns.
Run this count-only comparison inspection using the original df so the median-imputed Weight_kg values do not distort the comparison.

In [16136]:
# Weight_lbs vs Weight_kg — COMPARISON INSPECTION

kg = pd.to_numeric(df["Weight_kg"], errors="coerce")
lbs = pd.to_numeric(df["Weight_lbs"], errors="coerce")

valid_kg = kg.notna() & np.isfinite(kg) & (kg > 0)
valid_lbs = lbs.notna() & np.isfinite(lbs) & (lbs > 0)

both_valid = valid_kg & valid_lbs

expected_lbs = kg * 2.20462
difference = (lbs - expected_lbs).abs()

print("Valid Weight_kg:", valid_kg.sum())
print("Valid Weight_lbs:", valid_lbs.sum())
print("Both weights valid:", both_valid.sum())

print("Weight_lbs missing:", lbs.isna().sum())
print("Weight_lbs zero:", lbs.eq(0).sum())
print("Weight_lbs negative:", (lbs < 0).sum())

print("Both valid and within 1 lb:", (both_valid & (difference <= 1)).sum())
print("Both valid and differ by more than 1 lb:", (both_valid & (difference > 1)).sum())
print("Median absolute difference (lb):", difference[both_valid].median())

print("Weight_lbs invalid but Weight_kg valid:", ((~valid_lbs) & valid_kg).sum())
print("Weight_kg invalid but Weight_lbs valid:", ((~valid_kg) & valid_lbs).sum())

Valid Weight_kg: 1086089
Valid Weight_lbs: 1084446
Both weights valid: 1025785
Weight_lbs missing: 64152
Weight_lbs zero: 0
Weight_lbs negative: 6402
Both valid and within 1 lb: 162280
Both valid and differ by more than 1 lb: 863505
Median absolute difference (lb): 3.3719120350280605
Weight_lbs invalid but Weight_kg valid: 60304
Weight_kg invalid but Weight_lbs valid: 58661

In [16137]:
# Weight_lbs vs Weight_kg — COMPARISON INSPECTION

weight_lbs = df_clean["Weight_lbs"]
weight_kg = df_clean["Weight_kg"]

expected_lbs = weight_kg * 2.20462
valid = weight_kg.notna() & weight_lbs.notna()

difference = (weight_lbs - expected_lbs).abs()

print("Weight_kg missing:", weight_kg.isna().sum())
print("Weight_lbs missing:", weight_lbs.isna().sum())
print("Rows with both values:", valid.sum())
print("Rows matching conversion (tolerance 0.1 lb):",
      (difference[valid] <= 0.1).sum())
print("Rows differing by more than 0.1 lb:",
      (difference[valid] > 0.1).sum())

print("\nExamples with differences greater than 0.1 lb:")
print(df_clean.loc[
    valid & (difference > 0.1),
    ["Weight_kg", "Weight_lbs"]
].head(20))

Weight_kg missing: 0
Weight_lbs missing: 64152
Rows with both values: 1090848
Rows matching conversion (tolerance 0.1 lb): 16528
Rows differing by more than 0.1 lb: 1074320

Examples with differences greater than 0.1 lb:
     Weight_kg   Weight_lbs
0   106.200000   231.877387
1    87.400000   194.295528
2    81.900000   179.964120
3    70.500000   152.675132
5    76.400000   164.049851
6    97.800000   210.596747
7    49.200000    98.419524
8    77.500000   183.794193
9    89.500000   202.179267
10   91.100000   183.088625
11   81.700000   174.046588
12   66.400000   153.321186
13   95.800000   207.808286
14   81.700000   179.970987
15  482.497699  1058.468390
16   63.200000   143.560285
17   84.400000   184.172913
18  108.300000   239.978387
20   74.000000   158.227999
21   65.300000   145.313102

In [16138]:
valid_min_lbs = 22      # 10 kg
valid_max_lbs = 661     # 300 kg

# Step 1: Count BEFORE cleaning
print("Before cleaning:")
print("NaN:", df_clean["Weight_lbs"].isna().sum())
print("Zero:", (df_clean["Weight_lbs"] == 0).sum())
print("Negative:", (df_clean["Weight_lbs"] < 0).sum())
print("<22 lbs:", (df_clean["Weight_lbs"] < valid_min_lbs).sum())
print(">661 lbs:", (df_clean["Weight_lbs"] > valid_max_lbs).sum())

# Step 2: Median from REAL values only
median_lbs = df_clean["Weight_lbs"][
    df_clean["Weight_lbs"].notna() &
    (df_clean["Weight_lbs"] > 0) &
    (df_clean["Weight_lbs"] >= valid_min_lbs) &
    (df_clean["Weight_lbs"] <= valid_max_lbs)
].median()

print("\nMedian Weight_lbs (cleaned):", median_lbs)

# Step 3: Replace non-real values
df_clean["Weight_lbs"] = df_clean["Weight_lbs"].apply(
    lambda x: median_lbs if (
        pd.isna(x) or 
        x <= 0 or 
        x < valid_min_lbs or 
        x > valid_max_lbs
    ) else x
)

# Step 4: Count AFTER cleaning
print("\nAfter cleaning:")
print("NaN:", df_clean["Weight_lbs"].isna().sum())
print("Zero:", (df_clean["Weight_lbs"] == 0).sum())
print("Negative:", (df_clean["Weight_lbs"] < 0).sum())
print("<22 lbs:", (df_clean["Weight_lbs"] < valid_min_lbs).sum())
print(">661 lbs:", (df_clean["Weight_lbs"] > valid_max_lbs).sum())

# Step 5: Show first 20 cleaned values
print("\nFirst 20 cleaned values:")
print(df_clean["Weight_lbs"].head(20))

Before cleaning:
NaN: 64152
Zero: 0
Negative: 6402
<22 lbs: 11002
>661 lbs: 5414

Median Weight_lbs (cleaned): 172.03129296303388

After cleaning:
NaN: 0
Zero: 0
Negative: 0
<22 lbs: 0
>661 lbs: 0

First 20 cleaned values:
0     231.877387
1     194.295528
2     179.964120
3     152.675132
4     172.031293
5     164.049851
6     210.596747
7      98.419524
8     183.794193
9     202.179267
10    183.088625
11    174.046588
12    153.321186
13    207.808286
14    179.970987
15    172.031293
16    143.560285
17    184.172913
18    239.978387
19    172.031293
Name: Weight_lbs, dtype: float64

In [16139]:
col = df_clean["Weight_kg"]

print("NaN:", col.isna().sum())
print("Zero:", (col == 0).sum())
print("Negative:", (col < 0).sum())
print("Below 10 kg:", (col < 10).sum())
print("Above 300 kg:", (col > 300).sum())
print("\nLowest 20 values:")
print(col.nsmallest(20))
print("\nHighest 20 values:")
print(col.nlargest(20))

NaN: 0
Zero: 0
Negative: 0
Below 10 kg: 93
Above 300 kg: 5496

Lowest 20 values:
268649     0.002646
766461     0.008825
130429     0.011732
237174     0.013709
1004417    0.016380
1128566    0.027296
976648     0.030689
600593     0.038323
359120     0.042048
820749     0.042853
52298      0.050239
97857      0.053623
783803     0.053959
74568      0.054608
801363     0.063845
882479     0.064745
131633     0.065396
998836     0.094464
518214     0.094755
101650     0.100000
Name: Weight_kg, dtype: float64

Highest 20 values:
793551     499.995514
38208      499.932980
342679     499.921725
885208     499.921725
76457      499.910960
203858     499.875883
779982     499.846643
240624     499.828812
960154     499.786707
13731      499.762712
688072     499.753776
553279     499.670610
571092     499.670610
402678     499.664101
1023298    499.638118
1096942    499.566215
318322     499.553955
862731     499.549882
317757     499.516185
183567     499.499282
Name: Weight_kg, dtype: float64

In [16140]:
low_weight = df_clean["Weight_kg"] < 10

print("Records with weight below 10 kg:", low_weight.sum())
print("\nAge values for these records:")
print(df_clean.loc[low_weight, "Age"].describe())

print("\nAge and weight examples:")
print(
    df_clean.loc[low_weight, ["Age", "Weight_kg"]]
    .sort_values("Weight_kg")
    .head(30)
)

Records with weight below 10 kg: 93

Age values for these records:
count     93.000000
mean      55.741829
std       16.329644
min       14.000000
25%       46.000000
50%       55.000000
75%       64.000000
max      107.000000
Name: Age, dtype: float64

Age and weight examples:
           Age  Weight_kg
268649    55.0   0.002646
766461    37.0   0.008825
130429    31.0   0.011732
237174    73.0   0.013709
1004417   63.0   0.016380
1128566   64.0   0.027296
976648    60.0   0.030689
600593    72.0   0.038323
359120    58.0   0.042048
820749    70.0   0.042853
52298     52.0   0.050239
97857     37.0   0.053623
783803    51.0   0.053959
74568     59.0   0.054608
801363    47.0   0.063845
882479    34.0   0.064745
131633    50.0   0.065396
998836    75.0   0.094464
518214    66.0   0.094755
101650    24.0   0.100000
421071    32.0   0.300000
266009    43.0   1.100000
1147961   43.0   1.600000
8449      47.0   1.700000
257611   107.0   1.700000
72817     48.0   1.800000
1103367   62.0   2.000000
618156    57.0   2.100000
303047    50.0   2.300000
63463     58.0   2.300000

In [16141]:
# Inspect extreme weights above 300 kg
high_weight = df_clean["Weight_kg"] > 300

print("Count above 300 kg:", high_weight.sum())
print("\nAge and weight examples:")
print(
    df_clean.loc[high_weight, ["Age", "Weight_kg"]]
    .sort_values("Weight_kg", ascending=False)
    .head(30)
)

Count above 300 kg: 5496

Age and weight examples:
          Age   Weight_kg
793551   54.0  499.995514
38208    64.0  499.932980
342679   68.0  499.921725
885208   68.0  499.921725
76457    64.0  499.910960
203858   56.0  499.875883
779982   47.0  499.846643
240624   74.0  499.828812
960154   72.0  499.786707
13731    77.0  499.762712
688072   60.0  499.753776
571092   24.0  499.670610
553279   24.0  499.670610
402678   43.0  499.664101
1023298  80.0  499.638118
1096942  36.0  499.566215
318322   86.0  499.553955
862731   50.0  499.549882
317757   82.0  499.516185
183567   43.0  499.499282
109439   63.0  499.493018
557098   63.0  499.493018
828933   93.0  499.376128
5957     64.0  499.374393
494442   37.0  499.342111
221611   74.0  499.320599
237263   72.0  499.316687
12461    52.0  499.316384
848684   56.0  499.303843
126755   52.0  499.212780

In [16142]:
# Weight_kg — cleaning
invalid_weight = (
    (df_clean["Weight_kg"] < 10) |
    (df_clean["Weight_kg"] > 300)
)

df_clean.loc[invalid_weight, "Weight_kg"] = np.nan

print("NaN after cleaning:", df_clean["Weight_kg"].isna().sum())
print("Below 10 kg:", (df_clean["Weight_kg"] < 10).sum())
print("Above 300 kg:", (df_clean["Weight_kg"] > 300).sum())

NaN after cleaning: 5589
Below 10 kg: 0
Above 300 kg: 0



### EDA — `Weight_lbs`

- Original missing values: 64,152.
- Zero values: 0.
- Negative values: 6,402.
- Values below 22 lbs: 11,002.
- Values above 661 lbs: 5,414.

### Data Cleaning — `Weight_lbs`

- Replaced missing and invalid values (negative, below 22 lbs, or above 661 lbs) with the median.
- Median used: 172.0313 lbs.
- Final missing values: 0.
- Validation confirmed no zero, negative, below-22-lbs, or above-661-lbs values remain.
- Kept `Weight_lbs` separate from `Weight_kg`; no conversion or cross-column correction.

### EDA — `Weight_kg`

- Original dtype: float64; total records: 1,155,000.
- Original missing values: 0.
- Zero values: 0; negative values: 0.
- Below 10 kg: 93.
- Above 300 kg: 5,496; maximum approximately 500 kg.
- All 93 records below 10 kg had ages between 14 and 107 years.

### Data Cleaning — `Weight_kg`

- Converted values below 10 kg and above 300 kg to `NaN`.
- Preserved values between 10 and 300 kg, inclusive.
- Final missing values: 5,589.
- Validation confirmed no values below 10 kg or above 300 kg remain.
- No imputation performed.
- `Weight_lbs` and `Weight_kg` retained as separate columns; no conversion or cross-column correction.

HbA1c

In [16143]:
# HbA1c — INITIAL INSPECTION

col = df_clean["HbA1c"]
values = col.astype("string").str.strip()

print("Data type:", col.dtype)
print("NaN count:", col.isna().sum())
print("Zero count:", (col == 0).sum())
print("Negative values:", (col < 0).sum())
print("Dash count:", (values == "-").sum())
print("Empty/whitespace count:", (values == "").sum())
print("Values below 3:", (col < 3).sum())
print("Values above 20:", (col > 20).sum())

Data type: float64
NaN count: 62478
Zero count: 2802
Negative values: 2957
Dash count: 0
Empty/whitespace count: 0
Values below 3: 32100
Values above 20: 2613

In [16144]:
print("Lowest 30 HbA1c values:")
print(df_clean["HbA1c"].nsmallest(30))

print("\nHighest 30 HbA1c values:")
print(df_clean["HbA1c"].nlargest(30))

Lowest 30 HbA1c values:
943449    -3.1
710184    -2.2
53421     -2.1
100080    -1.8
1134069   -1.8
674730    -1.7
463975    -1.5
515577    -1.5
690444    -1.5
185533    -1.4
344362    -1.4
681572    -1.4
353859    -1.3
1104278   -1.3
69100     -1.2
593185    -1.2
773694    -1.2
891828    -1.2
910078    -1.2
1029098   -1.2
692114    -1.1
949862    -1.1
253       -1.0
940       -1.0
1090      -1.0
1453      -1.0
1476      -1.0
2432      -1.0
2477      -1.0
2516      -1.0
Name: HbA1c, dtype: float64

Highest 30 HbA1c values:
1067     50.0
1096     50.0
1532     50.0
2003     50.0
3491     50.0
4027     50.0
4253     50.0
4325     50.0
6323     50.0
6621     50.0
7462     50.0
7824     50.0
8282     50.0
8398     50.0
9142     50.0
9934     50.0
9964     50.0
9966     50.0
10077    50.0
10616    50.0
12207    50.0
12387    50.0
13209    50.0
13855    50.0
14618    50.0
15847    50.0
15967    50.0
16308    50.0
16601    50.0
16811    50.0
Name: HbA1c, dtype: float64

In [16145]:
# HbA1c — EXTREME-VALUE FREQUENCIES

col = df_clean["HbA1c"]

print("Negative values — most frequent:")
print(col[col < 0].value_counts().head(15))

print("\nValues below 3 — most frequent:")
print(col[col < 3].value_counts().sort_index().head(20))

print("\nValues above 20 — most frequent:")
print(col[col > 20].value_counts().sort_index().head(20))

Negative values — most frequent:
HbA1c
-1.0    2804
-0.2      30
-0.1      19
-0.5      17
-0.4      16
-0.3      15
-0.6      11
-0.7      10
-0.9       7
-0.8       6
-1.2       6
-1.4       3
-1.5       3
-1.8       2
-1.3       2
Name: count, dtype: int64

Values below 3 — most frequent:
HbA1c
-3.1       1
-2.2       1
-2.1       1
-1.8       2
-1.7       1
-1.5       3
-1.4       3
-1.3       2
-1.2       6
-1.1       2
-1.0    2804
-0.9       7
-0.8       6
-0.7      10
-0.6      11
-0.5      17
-0.4      16
-0.3      15
-0.2      30
-0.1      19
Name: count, dtype: int64

Values above 20 — most frequent:
HbA1c
50.0    2613
Name: count, dtype: int64

In [16146]:
# HbA1c — CLEANING
invalid_hba1c = (
    (df_clean["HbA1c"] < 3) |
    (df_clean["HbA1c"] > 20)
)

df_clean.loc[invalid_hba1c, "HbA1c"] = np.nan

# Validation
print("NaN count:", df_clean["HbA1c"].isna().sum())
print("Values below 3:", (df_clean["HbA1c"] < 3).sum())
print("Values above 20:", (df_clean["HbA1c"] > 20).sum())
print("Negative values:", (df_clean["HbA1c"] < 0).sum())
print("Value 50 remaining:", (df_clean["HbA1c"] == 50).sum())

NaN count: 97191
Values below 3: 0
Values above 20: 0
Negative values: 0
Value 50 remaining: 0

### EDA — `HbA1c`

- Data type: `float64`
- Total records: 1,155,000
- Original missing values: 62,478 (5.41%)
- Zero values: 2,802
- Negative values: 2,957
- Values below 3: 32,100
- Values above 20: 2,613
- Suspected placeholder values: `-1.0` (2,804 occurrences) and `50.0` (2,613 occurrences).

### Data Cleaning — `HbA1c`

- Converted values below 3 and above 20 to `NaN`.
- Preserved existing missing values.
- Final missing values: 97,191 (8.42%).
- Validation confirmed zero values below 3, above 20, negative values, or `50.0` remain.
- No median imputation performed; deferred until model preparation.

All columns have been individually cleaned to this point.

In [16147]:
# Sanity check: confirm state of df_clean before next step
print("Shape:", df_clean.shape)
print("Number of columns:", len(df_clean.columns))
print("Admission_Date dtype:", df_clean["Admission_Date"].dtype)
print("Admission_Year present:", "Admission_Year" in df_clean.columns)
print("\nCurrent columns:")
print(df_clean.columns.tolist())

Shape: (1155000, 34)
Number of columns: 34
Admission_Date dtype: datetime64[ns]
Admission_Year present: False

Current columns:
['Patient_ID', 'patient_id', 'Age', 'Gender', 'Ethnicity', 'Weight_kg', 'Weight_lbs', 'Height_cm', 'BMI', 'blood_pressure', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate', 'Temperature_F', 'Hemoglobin', 'WBC_Count', 'ALT_Enzyme', 'AST_Enzyme', 'Creatinine', 'eGFR', 'HbA1c', 'Total_Cholesterol', 'Drug_Name', 'Dosage', 'Duration_Days', 'Route', 'Concurrent_Drugs', 'Diagnosis', 'Smoking_Status', 'Alcohol_Use', 'Admission_Date', 'Treatment_Outcome', 'Adverse_Event', 'Readmission_30d']

Data set is clean, work on model building

Duplicates

In [16148]:
# Exact duplicate rows — inspection only

print("Total rows:", len(df_clean))
print("Exact duplicate rows:", df_clean.duplicated().sum())
print("Rows including duplicates:", df_clean.duplicated(keep=False).sum())

Total rows: 1155000
Exact duplicate rows: 73388
Rows including duplicates: 144298

In [16149]:
# Inspect 10 exact duplicate pairs — no changes

duplicate_mask = df_clean.duplicated(keep=False)
duplicate_rows = df_clean.loc[duplicate_mask]

pairs = duplicate_rows.groupby(
    list(df_clean.columns), dropna=False, sort=False
).head(2)

print(pairs.head(20).to_string(index=False))

 Patient_ID  patient_id  Age Gender        Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol        Drug_Name  Dosage Duration_Days      Route  Concurrent_Drugs              Diagnosis Smoking_Status     Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     582916         958 63.0    NaN            Asian       87.4  194.295528      174.4 26.9         124/94        124.0          94.0        71.0           98.0        11.8        NaN        21.4        16.1        0.95  26.7    7.6              251.0             <NA>     5.0           120    Unknown               5.0           osteoporosis            Yes              No     2022-06-10       Ineffective            0.0              0.0
     264177         130 64.0    NaN            Other       49.2   98.419524        NaN 23.5        138/109        138.0         109.0        43.0           98.0         NaN     4050.0        11.6        18.3        1.11  60.4    7.1              237.0 insulin glargine     5.0            30         SC               4.0                 asthma         Former              No     2020-01-05       Ineffective            0.0              0.0
     227332         737 48.0    NaN           Indian       95.8  207.808286      164.8 35.3         143/76        143.0          76.0        85.0           99.0        11.9     2721.0        64.2        12.2        1.02  85.8    7.1              255.0       omeprazole    25.0           NaN         IV               3.0                    NaN         Former         Unknown     2019-09-25       Ineffective            1.0              0.0
     995221         499 55.0    NaN African American       69.3  146.754363      159.9 26.9         158/72        158.0          72.0        94.0           97.9        11.1    10750.0        70.9        22.2        1.11  96.0    8.4              137.0       omeprazole     5.0           NaN    Unknown               3.0           Hypertension             No         Unknown     2025-07-31       Ineffective            0.0              0.0
     157947         740 66.0    NaN            White       98.0  222.543335      183.2 29.2         183/89        183.0          89.0        80.0          100.6        14.9     2129.0        24.2        17.2        2.06  94.8   10.3              232.0      fluticasone   200.0           NaN    Unknown               4.0 Chronic Kidney Disease         Former         Unknown            NaT       Ineffective            1.0              0.0
     157662         876 56.0   Male  Native American       78.0  168.101044      181.6 22.1         138/64        138.0          64.0         NaN            NaN        12.4     3797.0        24.6        16.8        0.96  64.8    6.6              194.0       amlodipine   500.0            14         IV               5.0                   GERD             No         Unknown     2019-03-15       Ineffective            1.0              0.0
    1039423         894 52.0    NaN            Black       58.6  128.403732      190.6 16.1         103/87        103.0          87.0        73.0           97.7         NaN        NaN        24.6        33.7        1.11   NaN    8.5              238.0       gabapentin    50.0           180         IM               6.0    Atrial Fibrillation         Former           Heavy     2025-12-01       Ineffective            NaN              0.0
     153463         763 30.0    NaN African American       55.2  124.187184      169.9 19.1         109/79        109.0          79.0       107.0           98.0         9.6     5896.0        24.1         7.2        1.46  69.0    6.7              302.0        metformin   200.0            14    Unknown               3.0                    UTI         Former              No     2019-01-01         Effective            0.0              0.0
     138871         273 66.0    NaN            Asian       81.3  185.258289      169.3 28.4         162/88        162.0          88.0        70.0           99.6        14.8     9468.0       134.5        10.1        0.67  82.7    NaN              180.0     escitalopram   750.0            14    Topical               5.0                    NaN            Yes         Unknown     2019-01-22       Ineffective            0.0              1.0
     974722         341 60.0    NaN African American       79.9  180.119149      180.1 24.6         111/77        111.0          77.0        86.0           98.2        13.7        NaN       103.5        38.9        1.11  79.9   11.5              196.0        ibuprofen   100.0           120         IM               2.0          Heart Failure            Yes 1-2 drinks/week     2025-06-04       Ineffective            1.0              0.0
     985588         841 55.0   Male            Other       65.4  150.108425      163.3 26.9         118/64        118.0          64.0        93.0           98.1        11.6    10206.0        16.9        21.1        1.32  72.4    5.7              266.0             <NA>    20.0             7    Topical               5.0               migraine         Former         Unknown     2025-07-04       Ineffective            NaN              0.0
      76590          73 70.0  Other          Unknown       61.4  146.542710      158.8 24.3         113/60        113.0          60.0       100.0           98.0        14.2     2267.0        13.9        20.4        0.77  70.6    3.5              214.0             <NA>   100.0            21         IV               3.0                    DVT        Unknown              No     2018-08-02       Ineffective            1.0              0.0
     316980         814 44.0 Female         Hispanic       81.7  174.051286      170.4 28.1         157/80        157.0          80.0        63.0           98.8        10.7     4074.0        15.1        19.6        1.23 123.4    NaN              172.0       gabapentin   750.0            21         IM               0.0                    DVT            Yes         Unknown            NaT         Effective            0.0              0.0
     832357         812 63.0   Male          Unknown       85.6  194.563464      167.8 30.4         130/95        130.0          95.0        99.0          100.8        12.0     6420.0        21.4        19.2        0.92  93.5    4.6              171.0     atorvastatin   100.0           NaN Ophthalmic               NaN                    NaN        Unknown      Occasional     2024-01-01       Ineffective            1.0              0.0
     219211         945 50.0 Female         Hispanic       76.7  172.364604      183.5 22.8         126/86        126.0          86.0        87.0           99.0        11.3     6769.0        41.1        21.4        0.65  76.1    6.2              181.0             <NA>   100.0           365    Unknown               0.0                   COPD            Yes         Unknown     2019-09-02       Ineffective            0.0              NaN
     817220         643 58.0  Other            Black       67.0  149.086446      141.9 33.3           <NA>         <NA>          90.0        79.0           99.0        12.2    10643.0        28.0        25.1        0.52   NaN    8.9              215.0      clopidogrel   750.0           120    Inhaled               2.0         hypothyroidism        Unknown             Yes     2024-03-23       Ineffective            0.0              0.0
     870874         102 82.0    NaN         Hispanic       61.4  131.809443      164.8 22.6         135/70        135.0          70.0        83.0           98.0        10.5     5479.0        24.6        11.6        1.48  50.0    6.2              175.0      doxycycline     NaN           NaN         IM               5.0                    DVT            Yes         Unknown     2024-01-01       Ineffective            1.0              0.0
     166408         273 37.0  Other          Unknown       78.0  210.150096      146.0 45.5         145/62        145.0          62.0         NaN            NaN        17.0     6895.0        46.2        22.2        1.26   NaN    7.0              163.0       lisinopril    10.0           NaN Ophthalmic               NaN                   COPD         Former           Heavy     2019-01-01         Effective            0.0              0.0
     804921         507 55.0    NaN          Unknown       69.9  160.006000      180.1 21.6         161/66        161.0          66.0        60.0           99.3        12.6     9644.0        36.1        15.4        1.20  70.8    6.4              137.0       furosemide    50.0            60         IV               1.0           Hypertension             No             Yes     2024-02-18       Ineffective            1.0              NaN
     591723         440 56.0 Female African American       48.0  106.053720      181.7 14.5         130/84        130.0          84.0        76.0           98.9        13.7     4062.0        11.8        16.8        0.90  93.0    6.5              341.0      simvastatin   100.0           NaN    Unknown               2.0          Heart Failure         Former              No     2022-07-05       Ineffective            0.0              NaN

In [16150]:
# Inspect exact duplicate rows in groups — no changes

duplicate_groups = (
    df_clean[df_clean.duplicated(keep=False)]
    .groupby(list(df_clean.columns), dropna=False, sort=False)
)

shown = 0

for _, group in duplicate_groups:
    print(f"\nDuplicate group — {len(group)} identical rows:")
    print(group.to_string(index=False))
    shown += 1

    if shown == 10:
        break

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol Drug_Name  Dosage Duration_Days   Route  Concurrent_Drugs    Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     582916         958 63.0    NaN     Asian       87.4  194.295528      174.4 26.9         124/94        124.0          94.0        71.0           98.0        11.8        NaN        21.4        16.1        0.95  26.7    7.6              251.0      <NA>     5.0           120 Unknown               5.0 osteoporosis            Yes          No     2022-06-10       Ineffective            0.0              0.0
     582916         958 63.0    NaN     Asian       87.4  194.295528      174.4 26.9         124/94        124.0          94.0        71.0           98.0        11.8        NaN        21.4        16.1        0.95  26.7    7.6              251.0      <NA>     5.0           120 Unknown               5.0 osteoporosis            Yes          No     2022-06-10       Ineffective            0.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol        Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     264177         130 64.0    NaN     Other       49.2   98.419524        NaN 23.5        138/109        138.0         109.0        43.0           98.0         NaN     4050.0        11.6        18.3        1.11  60.4    7.1              237.0 insulin glargine     5.0            30    SC               4.0    asthma         Former          No     2020-01-05       Ineffective            0.0              0.0
     264177         130 64.0    NaN     Other       49.2   98.419524        NaN 23.5        138/109        138.0         109.0        43.0           98.0         NaN     4050.0        11.6        18.3        1.11  60.4    7.1              237.0 insulin glargine     5.0            30    SC               4.0    asthma         Former          No     2020-01-05       Ineffective            0.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol  Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     227332         737 48.0    NaN    Indian       95.8  207.808286      164.8 35.3         143/76        143.0          76.0        85.0           99.0        11.9     2721.0        64.2        12.2        1.02  85.8    7.1              255.0 omeprazole    25.0           NaN    IV               3.0       NaN         Former     Unknown     2019-09-25       Ineffective            1.0              0.0
     227332         737 48.0    NaN    Indian       95.8  207.808286      164.8 35.3         143/76        143.0          76.0        85.0           99.0        11.9     2721.0        64.2        12.2        1.02  85.8    7.1              255.0 omeprazole    25.0           NaN    IV               3.0       NaN         Former     Unknown     2019-09-25       Ineffective            1.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender        Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol  Drug_Name  Dosage Duration_Days   Route  Concurrent_Drugs    Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     995221         499 55.0    NaN African American       69.3  146.754363      159.9 26.9         158/72        158.0          72.0        94.0           97.9        11.1    10750.0        70.9        22.2        1.11  96.0    8.4              137.0 omeprazole     5.0           NaN Unknown               3.0 Hypertension             No     Unknown     2025-07-31       Ineffective            0.0              0.0
     995221         499 55.0    NaN African American       69.3  146.754363      159.9 26.9         158/72        158.0          72.0        94.0           97.9        11.1    10750.0        70.9        22.2        1.11  96.0    8.4              137.0 omeprazole     5.0           NaN Unknown               3.0 Hypertension             No     Unknown     2025-07-31       Ineffective            0.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol   Drug_Name  Dosage Duration_Days   Route  Concurrent_Drugs              Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     157947         740 66.0    NaN     White       98.0  222.543335      183.2 29.2         183/89        183.0          89.0        80.0          100.6        14.9     2129.0        24.2        17.2        2.06  94.8   10.3              232.0 fluticasone   200.0           NaN Unknown               4.0 Chronic Kidney Disease         Former     Unknown            NaT       Ineffective            1.0              0.0
     157947         740 66.0    NaN     White       98.0  222.543335      183.2 29.2         183/89        183.0          89.0        80.0          100.6        14.9     2129.0        24.2        17.2        2.06  94.8   10.3              232.0 fluticasone   200.0           NaN Unknown               4.0 Chronic Kidney Disease         Former     Unknown            NaT       Ineffective            1.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender       Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol  Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     157662         876 56.0   Male Native American       78.0  168.101044      181.6 22.1         138/64        138.0          64.0         NaN            NaN        12.4     3797.0        24.6        16.8        0.96  64.8    6.6              194.0 amlodipine   500.0            14    IV               5.0      GERD             No     Unknown     2019-03-15       Ineffective            1.0              0.0
     157662         876 56.0   Male Native American       78.0  168.101044      181.6 22.1         138/64        138.0          64.0         NaN            NaN        12.4     3797.0        24.6        16.8        0.96  64.8    6.6              194.0 amlodipine   500.0            14    IV               5.0      GERD             No     Unknown     2019-03-15       Ineffective            1.0              0.0

Duplicate group — 3 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol  Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs           Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
    1039423         894 52.0    NaN     Black       58.6  128.403732      190.6 16.1         103/87        103.0          87.0        73.0           97.7         NaN        NaN        24.6        33.7        1.11   NaN    8.5              238.0 gabapentin    50.0           180    IM               6.0 Atrial Fibrillation         Former       Heavy     2025-12-01       Ineffective            NaN              0.0
    1039423         894 52.0    NaN     Black       58.6  128.403732      190.6 16.1         103/87        103.0          87.0        73.0           97.7         NaN        NaN        24.6        33.7        1.11   NaN    8.5              238.0 gabapentin    50.0           180    IM               6.0 Atrial Fibrillation         Former       Heavy     2025-12-01       Ineffective            NaN              0.0
    1039423         894 52.0    NaN     Black       58.6  128.403732      190.6 16.1         103/87        103.0          87.0        73.0           97.7         NaN        NaN        24.6        33.7        1.11   NaN    8.5              238.0 gabapentin    50.0           180    IM               6.0 Atrial Fibrillation         Former       Heavy     2025-12-01       Ineffective            NaN              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender        Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol Drug_Name  Dosage Duration_Days   Route  Concurrent_Drugs Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     153463         763 30.0    NaN African American       55.2  124.187184      169.9 19.1         109/79        109.0          79.0       107.0           98.0         9.6     5896.0        24.1         7.2        1.46  69.0    6.7              302.0 metformin   200.0            14 Unknown               3.0       UTI         Former          No     2019-01-01         Effective            0.0              0.0
     153463         763 30.0    NaN African American       55.2  124.187184      169.9 19.1         109/79        109.0          79.0       107.0           98.0         9.6     5896.0        24.1         7.2        1.46  69.0    6.7              302.0 metformin   200.0            14 Unknown               3.0       UTI         Former          No     2019-01-01         Effective            0.0              0.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol    Drug_Name  Dosage Duration_Days   Route  Concurrent_Drugs Diagnosis Smoking_Status Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     138871         273 66.0    NaN     Asian       81.3  185.258289      169.3 28.4         162/88        162.0          88.0        70.0           99.6        14.8     9468.0       134.5        10.1        0.67  82.7    NaN              180.0 escitalopram   750.0            14 Topical               5.0       NaN            Yes     Unknown     2019-01-22       Ineffective            0.0              1.0
     138871         273 66.0    NaN     Asian       81.3  185.258289      169.3 28.4         162/88        162.0          88.0        70.0           99.6        14.8     9468.0       134.5        10.1        0.67  82.7    NaN              180.0 escitalopram   750.0            14 Topical               5.0       NaN            Yes     Unknown     2019-01-22       Ineffective            0.0              1.0

Duplicate group — 2 identical rows:
 Patient_ID  patient_id  Age Gender        Ethnicity  Weight_kg  Weight_lbs  Height_cm  BMI blood_pressure  Systolic_BP  Diastolic_BP  Heart_Rate  Temperature_F  Hemoglobin  WBC_Count  ALT_Enzyme  AST_Enzyme  Creatinine  eGFR  HbA1c  Total_Cholesterol Drug_Name  Dosage Duration_Days Route  Concurrent_Drugs     Diagnosis Smoking_Status     Alcohol_Use Admission_Date Treatment_Outcome  Adverse_Event  Readmission_30d
     974722         341 60.0    NaN African American       79.9  180.119149      180.1 24.6         111/77        111.0          77.0        86.0           98.2        13.7        NaN       103.5        38.9        1.11  79.9   11.5              196.0 ibuprofen   100.0           120    IM               2.0 Heart Failure            Yes 1-2 drinks/week     2025-06-04       Ineffective            1.0              0.0
     974722         341 60.0    NaN African American       79.9  180.119149      180.1 24.6         111/77        111.0          77.0        86.0           98.2        13.7        NaN       103.5        38.9        1.11  79.9   11.5              196.0 ibuprofen   100.0           120    IM               2.0 Heart Failure            Yes 1-2 drinks/week     2025-06-04       Ineffective            1.0              0.0

In [16151]:
# Count exact duplicate rows — no changes

print("Total rows:", len(df_clean))
print("Exact duplicate copies (excluding first occurrence):",
      df_clean.duplicated().sum())
print("Rows belonging to duplicate groups (including first occurrence):",
      df_clean.duplicated(keep=False).sum())

Total rows: 1155000
Exact duplicate copies (excluding first occurrence): 73388
Rows belonging to duplicate groups (including first occurrence): 144298

In [16152]:
# Remove exact duplicate rows, keeping the first copy

rows_before = len(df_clean)

df_clean = df_clean.drop_duplicates(keep="first")

rows_after = len(df_clean)

print("Rows before:", rows_before)
print("Rows removed:", rows_before - rows_after)
print("Rows remaining:", rows_after)
print("Exact duplicates remaining:", df_clean.duplicated().sum())

Rows before: 1155000
Rows removed: 73388
Rows remaining: 1081612
Exact duplicates remaining: 0

Feature engineering

In [16153]:
# FINAL DATASET VERIFICATION 

import pandas as pd
import numpy as np

print("=== SHAPE CHECK ===")
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

print("\n=== COLUMN TYPES ===")
print(df_clean.dtypes)

print("\n=== MISSING VALUES PER COLUMN ===")
print(df_clean.isna().sum())

print("\n=== DUPLICATE ROWS ===")
print("Duplicate rows:", df_clean.duplicated().sum())

print("\n=== TARGET CHECK (Adverse_Event) ===")
if "Adverse_Event" in df_clean.columns:
    print("Unique values:", df_clean["Adverse_Event"].unique())
    print("Value counts:")
    print(df_clean["Adverse_Event"].value_counts(dropna=False))
else:
    print("Adverse_Event column missing!")

print("\n=== NUMERIC RANGE CHECK ===")
numeric_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    print(f"{col}: min={df_clean[col].min()}, max={df_clean[col].max()}")

print("\n=== CATEGORICAL UNIQUE CHECK (top 20) ===")
categorical_cols = df_clean.select_dtypes(exclude=[np.number]).columns.tolist()
for col in categorical_cols:
    print(f"\n{col}:")
    print(df_clean[col].value_counts(dropna=False).head(20))

=== SHAPE CHECK ===
Rows: 1081612
Columns: 34

=== COLUMN TYPES ===
Patient_ID                    int64
patient_id                    Int64
Age                         float64
Gender                          str
Ethnicity                       str
Weight_kg                   float64
Weight_lbs                  float64
Height_cm                   float64
BMI                         float64
blood_pressure               string
Systolic_BP                 Float64
Diastolic_BP                Float64
Heart_Rate                  float64
Temperature_F               float64
Hemoglobin                  float64
WBC_Count                   float64
ALT_Enzyme                  float64
AST_Enzyme                  float64
Creatinine                  float64
eGFR                        float64
HbA1c                       float64
Total_Cholesterol           float64
Drug_Name                    string
Dosage                      float64
Duration_Days                   str
Route                           str
Concurrent_Drugs            float64
Diagnosis                       str
Smoking_Status                  str
Alcohol_Use                  string
Admission_Date       datetime64[ns]
Treatment_Outcome            string
Adverse_Event               float64
Readmission_30d             float64
dtype: object

=== MISSING VALUES PER COLUMN ===
Patient_ID                0
patient_id            95085
Age                       0
Gender               430119
Ethnicity                 0
Weight_kg              5166
Weight_lbs                0
Height_cm            179561
BMI                       0
blood_pressure        17011
Systolic_BP           12229
Diastolic_BP           6877
Heart_Rate           133084
Temperature_F        135546
Hemoglobin           114569
WBC_Count            122929
ALT_Enzyme                0
AST_Enzyme                0
Creatinine                0
eGFR                 127741
HbA1c                 91151
Total_Cholesterol         0
Drug_Name            153725
Dosage               156927
Duration_Days        157586
Route                     0
Concurrent_Drugs     144356
Diagnosis            204157
Smoking_Status            0
Alcohol_Use               0
Admission_Date       314073
Treatment_Outcome         0
Adverse_Event         86980
Readmission_30d       78600
dtype: int64

=== DUPLICATE ROWS ===
Duplicate rows: 0

=== TARGET CHECK (Adverse_Event) ===
Unique values: [nan  0.  1.]
Value counts:
Adverse_Event
0.0    745309
1.0    249323
NaN     86980
Name: count, dtype: int64

=== NUMERIC RANGE CHECK ===
Patient_ID: min=1, max=1050000
patient_id: min=1, max=999
Age: min=0.00041854952983, max=120.0
Weight_kg: min=10.0, max=161.8
Weight_lbs: min=22.048687337931984, max=660.9777152236428
Height_cm: min=112.3, max=220.0
BMI: min=10.0, max=79.6
Systolic_BP: min=7.0, max=253.0
Diastolic_BP: min=4.0, max=148.0
Heart_Rate: min=30.0, max=146.0
Temperature_F: min=94.7, max=102.4
Hemoglobin: min=7.0, max=20.0
WBC_Count: min=2.0, max=19416.0
ALT_Enzyme: min=5.0, max=200.0
AST_Enzyme: min=-5.0, max=9999.0
Creatinine: min=0.14, max=6.89
eGFR: min=-0.0, max=201.9
HbA1c: min=3.0, max=20.0
Total_Cholesterol: min=70.0, max=398.0
Dosage: min=0.025, max=1000.0
Concurrent_Drugs: min=0.0, max=99.0
Adverse_Event: min=0.0, max=1.0
Readmission_30d: min=0.0, max=1.0

=== CATEGORICAL UNIQUE CHECK (top 20) ===

Gender:
Gender
NaN       430119
Female    268466
Male      268459
Other     114568
Name: count, dtype: int64

Ethnicity:
Ethnicity
Unknown              279415
Hispanic             149074
Asian                148887
White                148739
African American      89204
Black                 59236
Other                 58790
Native American       30201
Pacific Islander      29717
Prefer not to say     29571
Indian                29504
Mixed                 29274
Name: count, dtype: int64

blood_pressure:
blood_pressure
<NA>      17011
130/76      499
126/83      486
130/78      485
123/76      483
131/82      483
127/82      480
136/79      477
134/79      475
132/78      472
128/81      471
136/81      471
123/82      471
131/75      466
133/80      464
129/80      463
131/77      461
131/81      460
124/79      459
131/83      459
Name: count, dtype: Int64

Drug_Name:
Drug_Name
<NA>                   153725
amoxicillin             79473
metformin               79191
warfarin                66869
omeprazole              66861
gabapentin              66328
ibuprofen               66023
lisinopril              66016
atorvastatin            65974
insulin glargine        53076
tramadol                52503
albuterol               13572
levothyroxine           13440
hydrochlorothiazide     13414
ciprofloxacin           13405
pantoprazole            13400
duloxetine              13359
clopidogrel             13351
doxycycline             13317
amlodipine              13313
Name: count, dtype: Int64

Duration_Days:
Duration_Days
NaN         157586
30          102487
7           102396
365         102209
21          102207
90          102065
180         102024
14          101948
60          101761
120         101711
chronic       1863
lifetime      1678
ongoing       1677
Name: count, dtype: int64

Route:
Route
Unknown       310797
SC            133987
IM            133986
IV            133977
Oral          100793
Topical       100635
Inhaled        67033
Rectal         66530
Ophthalmic     33874
Name: count, dtype: int64

Diagnosis:
Diagnosis
NaN                       204157
Type 2 Diabetes           133213
Hypertension              106946
Atrial Fibrillation        79855
Osteoarthritis             53173
Chronic Kidney Disease     53113
Heart Failure              52963
Hyperlipidemia             52869
rheumatoid arthritis       26951
anxiety                    26838
asthma                     26752
COPD                       26705
DVT                        26581
GERD                       26579
depression                 26551
migraine                   26543
hypothyroidism             26519
osteoporosis               26476
pneumonia                  26357
epilepsy                   26266
Name: count, dtype: int64

Smoking_Status:
Smoking_Status
Unknown    318977
Yes        312570
No         242911
Former     138125
Never       69029
Name: count, dtype: int64

Alcohol_Use:
Alcohol_Use
Unknown            312031
No                 205639
Daily              103022
Yes                102836
Occasional         102390
Heavy              102160
Social             102100
1-2 drinks/week     51434
Name: count, dtype: Int64

Admission_Date:
Admission_Date
NaT           314073
2022-01-01     12403
2020-01-01     12380
2021-01-01     12276
2019-01-01     12237
2024-01-01     12229
2023-01-01     12198
2025-01-01     12172
2018-01-01     12120
2023-05-07       288
2025-12-01       268
2021-05-03       267
2019-06-12       267
2022-08-16       264
2020-03-01       263
2025-05-21       262
2020-09-25       260
2022-06-09       259
2018-03-10       259
2020-01-10       258
Name: count, dtype: int64

Treatment_Outcome:
Treatment_Outcome
Ineffective    788716
Effective      226850
Unknown         66046
Name: count, dtype: Int64

In [16154]:
# Save cleaned dataset
output_path = "clinical_data_cleaned.csv"

df_clean.to_csv(output_path, index=False)

print("Saved:", output_path)
print("Shape:", df_clean.shape)

Saved: clinical_data_cleaned.csv
Shape: (1081612, 34)

In [16159]:
1+1

2

These are your current column data types. All listed columns are float64 except Duration_Days, which is object.

To check whether Duration_Days contains text values that need cleaning before converting to numeric: